import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOK1, TOK2, TOK3, SEP;
terminal SC, EQ, AND, OR, EXM, OP, CP;
terminal String VAR, TRUE_WD, FALSE_WD, AND_WD, OR_WD;
terminal String IF_WD, FI_WD, DO_WD, DONE_WD, PRINT_WD;
terminal String QSTRING;
// terminal Double test;
// terminal Integer test;

non terminal prog ;
non terminal HEADER, EXECUTION;
non terminal HEADER1, TOK2REP, TOK13, TOK13REP;
non terminal HEADER2, H2_TOK13;
non terminal COMMAND, COMMANDS, ASS, IF;
non terminal BOOL_EXP, OPR, OPER;
non terminal COMP_LIST, COMP, COMP_OP, PRINT; 
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left EXM;
// precedence left AND, OR;
// precedence left OP, CP;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP EXECUTION
;

// header
HEADER ::= HEADER1 | HEADER2
;

HEADER1 ::= TOK2 SC TOK2 SC TOK2 SC TOK2REP TOK13
;

TOK2REP ::= TOK2 SC TOK2 SC TOK2REP |
;

TOK13 ::= TOK13REP TOK13REP |
          TOK13REP TOK13REP TOK13REP |
          TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP
;

TOK13REP ::= TOK1 SC | TOK3 SC 
;

HEADER2 ::= TOK3 SC H2_TOK13 TOK3 SC H2_TOK13 TOK3 SC H2_TOK13
;

H2_TOK13 ::= TOK1 SC H2_TOK13 | TOK2 SC H2_TOK13 |
;

//#execution
EXECUTION ::= COMMAND COMMAND COMMAND COMMAND COMMAND COMMANDS |
;

COMMANDS ::=  COMMAND COMMAND COMMANDS |
;

COMMAND ::= ASS | IF
;

ASS ::= VAR EQ BOOL_EXP SC
;

BOOL_EXP ::= OPR | OPR OPER BOOL_EXP | OP BOOL_EXP CP
;

OPR ::= FALSE_WD | TRUE_WD | EXM FALSE_WD | EXM TRUE_WD | VAR |  EXM VAR
;

OPER ::= AND | OR
;

IF ::= IF_WD BOOL_EXP COMP_LIST FI_WD
;

COMP_LIST ::= COMP_LIST COMP | 
;

COMP ::= COMP_OP BOOL_EXP DO_WD PRINT DONE_WD
;

COMP_OP ::= AND_WD | OR_WD
;

PRINT ::= PRINT_WD QSTRING SC
;

//#endexecution

