import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, Boolean>();
:};

parser code {:
    public HashMap <String, Boolean>table;

    public void report_error(String message, Object info) {
        System.err.print("ERROR: Syntax error");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.print(" (line "+line+", column "+column+"): ");
            } else System.err.print(": ");
        else System.err.print(": ");
    }

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

:};
/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal SEP, TOK1 , TOK2, TOK3, EQ, AND, OR, NOT, TRUE_WD, FALSE_WD, IF_WD, FI_WD, OR_WD, AND_WD, DO_WD,PRINT_WD,DONE_WD,QSTRING,SC, CP, OP ;
terminal String VAR;


non terminal prog, HEADER, EXECUTION ;
non terminal HEADER1, HEADER2, TOK2REP, TOK13REP, TOK13,TOK12REP, TOK12 ;
non terminal COMMANDS, COMMAND, ASS, IF, LISTCOMP ;
non terminal Boolean BOOLEXP;
non terminal Object[] COMP;

precedence left AND, OR;
precedence left NOT;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP EXECUTION
;

HEADER ::= HEADER1 | HEADER2
;

HEADER1 ::= TOK2REP TOK13REP
;

TOK2REP ::= TOK2REP TOK2 TOK2 | TOK2 TOK2 TOK2
;

TOK13REP ::= TOK13 TOK13
            | TOK13 TOK13 TOK13 
            | TOK13 TOK13 TOK13 TOK13 TOK13 TOK13 TOK13 TOK13 TOK13 
;
TOK13 ::= TOK1 | TOK3
;

HEADER2 ::= TOK3 TOK12REP TOK3 TOK12REP TOK3 TOK12REP
;

TOK12REP ::= TOK12REP TOK12 |
;

TOK12 ::= TOK1 | TOK2
;

//EXECUTION

EXECUTION ::= COMMANDS |
;

COMMANDS ::= COMMANDS COMMAND COMMAND | COMMAND COMMAND COMMAND COMMAND COMMAND
;

COMMAND ::= ASS | IF
;

ASS ::= VAR:var EQ BOOLEXP:exp SC {:parser.table.put(var,exp);:}
;

BOOLEXP ::=     BOOLEXP:x AND BOOLEXP:y {:RESULT = x & y;:}
            |   BOOLEXP:x OR BOOLEXP:y {:RESULT = x | y;:}
            |   NOT BOOLEXP:x {:RESULT = !x;:}
            |   OP BOOLEXP:x CP {:RESULT = x;:}
            |   TRUE_WD {:RESULT = true;:}
            |   FALSE_WD {:RESULT = false;:}
            |   VAR:x {:RESULT = parser.table.get(x);:}
;

IF ::= IF_WD BOOLEXP:bool LISTCOMP FI_WD
;

LISTCOMP ::= LISTCOMP COMP:x{:
    Boolean secondexp = (Boolean)x[1];
    String comp = (String)x[0];
    String word = (String)x[2];
    if(comp == "or" ){
        if((Boolean)parser.stack(-2) | secondexp){
            System.out.println(word);
        };
    }else{
         if((Boolean)parser.stack(-2) & secondexp){
            System.out.println(word);
        };
    };
    :}  | COMP:x {:
    Boolean secondexp = (Boolean)x[1];
    String comp = (String)x[0];
    String word = (String)x[2];
    if(comp == "or" ){
        if((Boolean)parser.stack(-1) | secondexp){
            System.out.println(word);
        };
    }else{
         if((Boolean)parser.stack(-2) & secondexp){
            System.out.println(word);
        };
    };
    :}
;

COMP ::=    OR_WD BOOLEXP:x DO_WD PRINT_WD QSTRING:y SC DONE_WD  {:
Object [] arr = new Object[3];
arr[0] = "or";
arr[1] = x  ;
arr[2] = y;
RESULT = arr;
:}
        |   AND_WD BOOLEXP:x DO_WD PRINT_WD QSTRING:y SC DONE_WD  {:
Object [] arr = new Object[3];
arr[0] = "and";
arr[1] = x  ;
arr[2] = y;
RESULT = arr;
:}
;

