
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\051\000\002\002\004\000\002\002\005\000\002\003" +
    "\003\000\002\003\003\000\002\005\012\000\002\006\007" +
    "\000\002\006\002\000\002\007\004\000\002\007\005\000" +
    "\002\007\013\000\002\010\004\000\002\010\004\000\002" +
    "\011\013\000\002\012\005\000\002\012\005\000\002\012" +
    "\002\000\002\004\010\000\002\004\002\000\002\014\005" +
    "\000\002\014\002\000\002\013\003\000\002\013\003\000" +
    "\002\015\006\000\002\017\003\000\002\017\005\000\002" +
    "\017\005\000\002\020\003\000\002\020\003\000\002\020" +
    "\004\000\002\020\004\000\002\020\003\000\002\020\004" +
    "\000\002\021\003\000\002\021\003\000\002\016\006\000" +
    "\002\022\004\000\002\022\002\000\002\023\007\000\002" +
    "\024\003\000\002\024\003\000\002\025\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\136\000\006\005\006\006\004\001\002\000\004\010" +
    "\123\001\002\000\004\007\ufffe\001\002\000\004\010\072" +
    "\001\002\000\004\007\uffff\001\002\000\004\007\013\001" +
    "\002\000\004\002\012\001\002\000\004\002\001\001\002" +
    "\000\010\002\ufff0\017\014\024\017\001\002\000\004\011" +
    "\067\001\002\000\006\017\014\024\017\001\002\000\004" +
    "\002\000\001\002\000\014\014\027\015\023\017\022\020" +
    "\026\021\030\001\002\000\010\002\uffed\017\uffed\024\uffed" +
    "\001\002\000\010\002\uffec\017\uffec\024\uffec\001\002\000" +
    "\022\010\uffe3\012\uffe3\013\uffe3\016\uffe3\022\uffe3\023\uffe3" +
    "\025\uffe3\026\uffe3\001\002\000\014\014\027\015\023\017" +
    "\022\020\026\021\030\001\002\000\010\022\uffdd\023\uffdd" +
    "\025\uffdd\001\002\000\022\010\uffea\012\034\013\036\016" +
    "\uffea\022\uffea\023\uffea\025\uffea\026\uffea\001\002\000\022" +
    "\010\uffe6\012\uffe6\013\uffe6\016\uffe6\022\uffe6\023\uffe6\025" +
    "\uffe6\026\uffe6\001\002\000\010\017\031\020\032\021\033" +
    "\001\002\000\022\010\uffe7\012\uffe7\013\uffe7\016\uffe7\022" +
    "\uffe7\023\uffe7\025\uffe7\026\uffe7\001\002\000\022\010\uffe2" +
    "\012\uffe2\013\uffe2\016\uffe2\022\uffe2\023\uffe2\025\uffe2\026" +
    "\uffe2\001\002\000\022\010\uffe4\012\uffe4\013\uffe4\016\uffe4" +
    "\022\uffe4\023\uffe4\025\uffe4\026\uffe4\001\002\000\022\010" +
    "\uffe5\012\uffe5\013\uffe5\016\uffe5\022\uffe5\023\uffe5\025\uffe5" +
    "\026\uffe5\001\002\000\014\014\uffe1\015\uffe1\017\uffe1\020" +
    "\uffe1\021\uffe1\001\002\000\014\014\027\015\023\017\022" +
    "\020\026\021\030\001\002\000\014\014\uffe0\015\uffe0\017" +
    "\uffe0\020\uffe0\021\uffe0\001\002\000\016\010\uffe9\016\uffe9" +
    "\022\uffe9\023\uffe9\025\uffe9\026\uffe9\001\002\000\010\022" +
    "\041\023\044\025\042\001\002\000\014\014\uffdb\015\uffdb" +
    "\017\uffdb\020\uffdb\021\uffdb\001\002\000\010\002\uffdf\017" +
    "\uffdf\024\uffdf\001\002\000\010\022\uffde\023\uffde\025\uffde" +
    "\001\002\000\014\014\uffda\015\uffda\017\uffda\020\uffda\021" +
    "\uffda\001\002\000\014\014\027\015\023\017\022\020\026" +
    "\021\030\001\002\000\004\026\047\001\002\000\004\030" +
    "\051\001\002\000\004\027\054\001\002\000\004\031\052" +
    "\001\002\000\004\010\053\001\002\000\004\027\uffd9\001" +
    "\002\000\010\022\uffdc\023\uffdc\025\uffdc\001\002\000\004" +
    "\016\056\001\002\000\016\010\uffe8\016\uffe8\022\uffe8\023" +
    "\uffe8\025\uffe8\026\uffe8\001\002\000\006\017\014\024\017" +
    "\001\002\000\006\017\014\024\017\001\002\000\006\017" +
    "\014\024\017\001\002\000\010\002\uffee\017\014\024\017" +
    "\001\002\000\006\017\014\024\017\001\002\000\004\002" +
    "\ufff1\001\002\000\010\002\uffee\017\014\024\017\001\002" +
    "\000\004\002\uffef\001\002\000\014\014\027\015\023\017" +
    "\022\020\026\021\030\001\002\000\004\010\071\001\002" +
    "\000\010\002\uffeb\017\uffeb\024\uffeb\001\002\000\004\005" +
    "\073\001\002\000\004\010\074\001\002\000\004\005\075" +
    "\001\002\000\004\010\076\001\002\000\010\004\ufffb\005" +
    "\100\006\ufffb\001\002\000\006\004\107\006\106\001\002" +
    "\000\004\010\101\001\002\000\004\005\102\001\002\000" +
    "\004\010\103\001\002\000\010\004\ufffb\005\100\006\ufffb" +
    "\001\002\000\006\004\ufffc\006\ufffc\001\002\000\004\007" +
    "\ufffd\001\002\000\004\010\122\001\002\000\004\010\121" +
    "\001\002\000\006\004\107\006\106\001\002\000\010\004" +
    "\107\006\106\007\ufffa\001\002\000\010\004\107\006\106" +
    "\007\ufff9\001\002\000\006\004\107\006\106\001\002\000" +
    "\006\004\107\006\106\001\002\000\006\004\107\006\106" +
    "\001\002\000\006\004\107\006\106\001\002\000\006\004" +
    "\107\006\106\001\002\000\004\007\ufff8\001\002\000\010" +
    "\004\ufff7\006\ufff7\007\ufff7\001\002\000\010\004\ufff6\006" +
    "\ufff6\007\ufff6\001\002\000\010\004\126\005\125\006\ufff2" +
    "\001\002\000\004\006\133\001\002\000\004\010\131\001" +
    "\002\000\004\010\127\001\002\000\012\004\126\005\125" +
    "\006\ufff2\007\ufff2\001\002\000\006\006\ufff4\007\ufff4\001" +
    "\002\000\012\004\126\005\125\006\ufff2\007\ufff2\001\002" +
    "\000\006\006\ufff3\007\ufff3\001\002\000\004\010\134\001" +
    "\002\000\010\004\126\005\125\006\ufff2\001\002\000\004" +
    "\006\136\001\002\000\004\010\137\001\002\000\010\004" +
    "\126\005\125\007\ufff2\001\002\000\004\007\ufff5\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\136\000\012\002\010\003\007\005\006\011\004\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\004\015\013\014\015\017\016\020" +
    "\001\001\000\002\001\001\000\010\013\056\015\017\016" +
    "\020\001\001\000\002\001\001\000\006\017\023\020\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\017\054\020\024\001\001\000\004\022\037" +
    "\001\001\000\004\021\034\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\017" +
    "\036\020\024\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\023\042\024\044\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\017\045\020\024\001\001\000\002\001\001\000\004\025" +
    "\047\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\013\057\015\017\016\020" +
    "\001\001\000\010\013\060\015\017\016\020\001\001\000" +
    "\010\013\061\015\017\016\020\001\001\000\012\013\062" +
    "\014\063\015\017\016\020\001\001\000\010\013\064\015" +
    "\017\016\020\001\001\000\002\001\001\000\012\013\062" +
    "\014\065\015\017\016\020\001\001\000\002\001\001\000" +
    "\006\017\067\020\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\076\001\001\000\006" +
    "\007\104\010\107\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\103\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\110\001\001\000\004\010\111\001\001" +
    "\000\004\010\112\001\001\000\004\010\113\001\001\000" +
    "\004\010\114\001\001\000\004\010\115\001\001\000\004" +
    "\010\116\001\001\000\004\010\117\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\123" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\127\001\001\000\002\001\001\000\004" +
    "\012\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\012\134\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\137\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= HEADER SEP EXECUTION 
            { parser.Tree.reduce(3,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // HEADER ::= HEADER1 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // HEADER ::= HEADER2 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // HEADER1 ::= TOK2 SC TOK2 SC TOK2 SC TOK2REP TOK13 
            { parser.Tree.reduce(8,"HEADER1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER1",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // TOK2REP ::= TOK2 SC TOK2 SC TOK2REP 
            { parser.Tree.reduce(5,"TOK2REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2REP",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // TOK2REP ::= 
            { parser.Tree.reduce(0,"TOK2REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2REP",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TOK13 ::= TOK13REP TOK13REP 
            { parser.Tree.reduce(2,"TOK13",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK13",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TOK13 ::= TOK13REP TOK13REP TOK13REP 
            { parser.Tree.reduce(3,"TOK13",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK13",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // TOK13 ::= TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP TOK13REP 
            { parser.Tree.reduce(9,"TOK13",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK13",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // TOK13REP ::= TOK1 SC 
            { parser.Tree.reduce(2,"TOK13REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK13REP",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // TOK13REP ::= TOK3 SC 
            { parser.Tree.reduce(2,"TOK13REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK13REP",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // HEADER2 ::= TOK3 SC H2_TOK13 TOK3 SC H2_TOK13 TOK3 SC H2_TOK13 
            { parser.Tree.reduce(9,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // H2_TOK13 ::= TOK1 SC H2_TOK13 
            { parser.Tree.reduce(3,"H2_TOK13",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("H2_TOK13",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // H2_TOK13 ::= TOK2 SC H2_TOK13 
            { parser.Tree.reduce(3,"H2_TOK13",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("H2_TOK13",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // H2_TOK13 ::= 
            { parser.Tree.reduce(0,"H2_TOK13",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("H2_TOK13",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // EXECUTION ::= COMMAND COMMAND COMMAND COMMAND COMMAND COMMANDS 
            { parser.Tree.reduce(6,"EXECUTION",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXECUTION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // EXECUTION ::= 
            { parser.Tree.reduce(0,"EXECUTION",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXECUTION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // COMMANDS ::= COMMAND COMMAND COMMANDS 
            { parser.Tree.reduce(3,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // COMMANDS ::= 
            { parser.Tree.reduce(0,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // COMMAND ::= ASS 
            { parser.Tree.reduce(1,"COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMAND",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // COMMAND ::= IF 
            { parser.Tree.reduce(1,"COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMAND",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ASS ::= VAR EQ BOOL_EXP SC 
            { parser.Tree.reduce(4,"ASS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASS",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // BOOL_EXP ::= OPR 
            { parser.Tree.reduce(1,"BOOL_EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BOOL_EXP",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // BOOL_EXP ::= OPR OPER BOOL_EXP 
            { parser.Tree.reduce(3,"BOOL_EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BOOL_EXP",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // BOOL_EXP ::= OP BOOL_EXP CP 
            { parser.Tree.reduce(3,"BOOL_EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BOOL_EXP",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // OPR ::= FALSE_WD 
            { parser.Tree.reduce(1,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // OPR ::= TRUE_WD 
            { parser.Tree.reduce(1,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPR ::= EXM FALSE_WD 
            { parser.Tree.reduce(2,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPR ::= EXM TRUE_WD 
            { parser.Tree.reduce(2,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OPR ::= VAR 
            { parser.Tree.reduce(1,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // OPR ::= EXM VAR 
            { parser.Tree.reduce(2,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // OPER ::= AND 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // OPER ::= OR 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // IF ::= IF_WD BOOL_EXP COMP_LIST FI_WD 
            { parser.Tree.reduce(4,"IF",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IF",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // COMP_LIST ::= COMP_LIST COMP 
            { parser.Tree.reduce(2,"COMP_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP_LIST",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // COMP_LIST ::= 
            { parser.Tree.reduce(0,"COMP_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP_LIST",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // COMP ::= COMP_OP BOOL_EXP DO_WD PRINT DONE_WD 
            { parser.Tree.reduce(5,"COMP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // COMP_OP ::= AND_WD 
            { parser.Tree.reduce(1,"COMP_OP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP_OP",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // COMP_OP ::= OR_WD 
            { parser.Tree.reduce(1,"COMP_OP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP_OP",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // PRINT ::= PRINT_WD QSTRING SC 
            { parser.Tree.reduce(3,"PRINT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
