
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CP = 3;
  public static final int CO = 5;
  public static final int CM = 6;
  public static final int EURODAY_WD = 15;
  public static final int OP = 2;
  public static final int INUM = 10;
  public static final int EOF = 0;
  public static final int MIN_SUM_WD = 16;
  public static final int RNUM = 9;
  public static final int SEP = 14;
  public static final int error = 1;
  public static final int DOT = 4;
  public static final int TOKEN3 = 13;
  public static final int TOKEN2 = 12;
  public static final int TOKEN1 = 11;
  public static final int QSTRING = 8;
  public static final int SC = 7;
  public static final int E_WD = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OP",
  "CP",
  "DOT",
  "CO",
  "CM",
  "SC",
  "QSTRING",
  "RNUM",
  "INUM",
  "TOKEN1",
  "TOKEN2",
  "TOKEN3",
  "SEP",
  "EURODAY_WD",
  "MIN_SUM_WD",
  "E_WD"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[3]=new String("CP");
		TT[5]=new String("CO");
		TT[6]=new String("CM");
		TT[15]=new String("EURODAY_WD");
		TT[2]=new String("OP");
		TT[10]=new String("INUM");
		TT[0]=new String("EOF");
		TT[16]=new String("MIN_SUM_WD");
		TT[9]=new String("RNUM");
		TT[14]=new String("SEP");
		TT[1]=new String("error");
		TT[4]=new String("DOT");
		TT[13]=new String("TOKEN3");
		TT[12]=new String("TOKEN2");
		TT[11]=new String("TOKEN1");
		TT[8]=new String("QSTRING");
		TT[7]=new String("SC");
		TT[17]=new String("E_WD");
	}
public String getTT(int i){return TT[i];}
}

