import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal SEP, TOK1, TOK2, TOK3, SC, CM, EQ, OB, CB, GT ;
terminal String INIT_WD, HEIGHT_WD, SPEED_WD, SUM_WD, MUL_WD, COND_WD, UPDATE_WD, DONE_WD;
// terminal Double test;
terminal Integer INUM;

non terminal prog, HEADER, SIMULATION ;
non terminal TOKENOTHER , TOKEN1, TOKEN2, TOKEN3;
non terminal INIT, COMMANDS, SIM2, HEIGHTASS, SPEEDASS, EXPS, EXP, OPER, COND, COMPARISON, ASSES, COMPARISON_COMMAND ;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;
// precedence left PLUS, DASH;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;


prog ::= HEADER SEP SIMULATION
;

HEADER ::= 
            TOKENOTHER                                              |
            TOKENOTHER TOKEN3 TOKENOTHER                           |
            TOKENOTHER TOKEN3 TOKENOTHER TOKEN3 TOKENOTHER        
;


TOKENOTHER ::= TOKENOTHER  TOKEN1  | TOKENOTHER TOKEN2  | TOKEN1 | TOKEN2 
;

TOKEN1 ::=  TOK1 SC  
;

TOKEN2 ::=  TOK2 SC  
;

TOKEN3 ::= TOK3 SC
;

SIMULATION ::=  INIT COMMANDS
;

INIT ::= INIT_WD SIM2 SC    
;

SIM2 ::= HEIGHTASS CM SPEEDASS  |
         SPEEDASS CM HEIGHTASS  |
         HEIGHTASS |
         SPEEDASS |
;

HEIGHTASS ::= HEIGHT_WD EQ EXPS
;

SPEEDASS ::= SPEED_WD EQ EXPS
;

EXPS ::= EXPS OPER EXP | EXP
;

EXP ::= INUM | HEIGHT_WD | SPEED_WD
;

OPER ::= SUM_WD | MUL_WD
;

COMMANDS ::= HEIGHTASS SC COMMANDS | SPEEDASS SC COMMANDS | COND COMMANDS |
;

COND ::= COND_WD OB COMPARISON CB UPDATE_WD ASSES DONE_WD SC
;

ASSES ::= HEIGHTASS SC SPEEDASS SC  |
         SPEEDASS SC HEIGHTASS SC  |
         HEIGHTASS SC|
         SPEEDASS SC
;

COMPARISON ::=EXPS COMPARISON_COMMAND EXPS |
;
COMPARISON_COMMAND ::= GT | EQ
;