
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\051\000\002\002\004\000\002\002\005\000\002\003" +
    "\003\000\002\003\005\000\002\003\007\000\002\005\004" +
    "\000\002\005\004\000\002\005\003\000\002\005\003\000" +
    "\002\006\004\000\002\007\004\000\002\010\004\000\002" +
    "\004\004\000\002\011\005\000\002\013\005\000\002\013" +
    "\005\000\002\013\003\000\002\013\003\000\002\013\002" +
    "\000\002\014\005\000\002\015\005\000\002\016\005\000" +
    "\002\016\003\000\002\017\003\000\002\017\003\000\002" +
    "\017\003\000\002\020\003\000\002\020\003\000\002\012" +
    "\005\000\002\012\005\000\002\012\004\000\002\012\002" +
    "\000\002\021\012\000\002\023\006\000\002\023\006\000" +
    "\002\023\004\000\002\023\004\000\002\022\005\000\002" +
    "\022\002\000\002\024\003\000\002\024\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\113\000\006\005\005\006\004\001\002\000\004\010" +
    "\115\001\002\000\004\010\114\001\002\000\012\004\uffff" +
    "\005\005\006\004\007\104\001\002\000\004\004\014\001" +
    "\002\000\012\004\ufff9\005\ufff9\006\ufff9\007\ufff9\001\002" +
    "\000\004\002\013\001\002\000\012\004\ufffa\005\ufffa\006" +
    "\ufffa\007\ufffa\001\002\000\004\002\001\001\002\000\004" +
    "\016\017\001\002\000\004\002\000\001\002\000\012\002" +
    "\uffe2\017\024\020\022\023\046\001\002\000\010\010\uffef" +
    "\017\024\020\022\001\002\000\004\010\045\001\002\000" +
    "\006\010\ufff0\011\043\001\002\000\004\012\041\001\002" +
    "\000\006\010\ufff1\011\037\001\002\000\004\012\025\001" +
    "\002\000\010\017\032\020\031\026\026\001\002\000\020" +
    "\010\uffea\011\uffea\012\uffea\014\uffea\015\uffea\021\uffea\022" +
    "\uffea\001\002\000\012\010\uffee\011\uffee\021\033\022\035" +
    "\001\002\000\020\010\uffeb\011\uffeb\012\uffeb\014\uffeb\015" +
    "\uffeb\021\uffeb\022\uffeb\001\002\000\020\010\uffe8\011\uffe8" +
    "\012\uffe8\014\uffe8\015\uffe8\021\uffe8\022\uffe8\001\002\000" +
    "\020\010\uffe9\011\uffe9\012\uffe9\014\uffe9\015\uffe9\021\uffe9" +
    "\022\uffe9\001\002\000\010\017\uffe7\020\uffe7\026\uffe7\001" +
    "\002\000\010\017\032\020\031\026\026\001\002\000\010" +
    "\017\uffe6\020\uffe6\026\uffe6\001\002\000\020\010\uffec\011" +
    "\uffec\012\uffec\014\uffec\015\uffec\021\uffec\022\uffec\001\002" +
    "\000\004\020\022\001\002\000\004\010\ufff3\001\002\000" +
    "\010\017\032\020\031\026\026\001\002\000\012\010\uffed" +
    "\011\uffed\021\033\022\035\001\002\000\004\017\024\001" +
    "\002\000\004\010\ufff2\001\002\000\012\002\ufff4\017\ufff4" +
    "\020\ufff4\023\ufff4\001\002\000\004\013\060\001\002\000" +
    "\004\010\056\001\002\000\004\010\054\001\002\000\004" +
    "\002\ufff5\001\002\000\012\002\uffe2\017\024\020\022\023" +
    "\046\001\002\000\004\002\uffe3\001\002\000\012\002\uffe2" +
    "\017\024\020\022\023\046\001\002\000\004\002\uffe5\001" +
    "\002\000\012\002\uffe2\017\024\020\022\023\046\001\002" +
    "\000\004\002\uffe4\001\002\000\012\014\uffdb\017\032\020" +
    "\031\026\026\001\002\000\012\012\100\015\101\021\033" +
    "\022\035\001\002\000\004\014\063\001\002\000\004\024" +
    "\064\001\002\000\006\017\024\020\022\001\002\000\004" +
    "\010\075\001\002\000\004\025\073\001\002\000\004\010" +
    "\070\001\002\000\006\020\022\025\uffde\001\002\000\004" +
    "\010\072\001\002\000\004\025\uffe0\001\002\000\004\010" +
    "\074\001\002\000\012\002\uffe1\017\uffe1\020\uffe1\023\uffe1" +
    "\001\002\000\006\017\024\025\uffdd\001\002\000\004\010" +
    "\077\001\002\000\004\025\uffdf\001\002\000\010\017\uffd9" +
    "\020\uffd9\026\uffd9\001\002\000\010\017\uffda\020\uffda\026" +
    "\uffda\001\002\000\010\017\032\020\031\026\026\001\002" +
    "\000\010\014\uffdc\021\033\022\035\001\002\000\004\010" +
    "\113\001\002\000\006\005\005\006\004\001\002\000\012" +
    "\004\ufffb\005\ufffb\006\ufffb\007\ufffb\001\002\000\012\004" +
    "\ufffc\005\ufffc\006\ufffc\007\ufffc\001\002\000\012\004\ufffe" +
    "\005\005\006\004\007\104\001\002\000\006\005\005\006" +
    "\004\001\002\000\010\004\ufffd\005\005\006\004\001\002" +
    "\000\006\005\ufff6\006\ufff6\001\002\000\012\004\ufff8\005" +
    "\ufff8\006\ufff8\007\ufff8\001\002\000\012\004\ufff7\005\ufff7" +
    "\006\ufff7\007\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\113\000\014\002\010\003\006\005\005\006\011\007" +
    "\007\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\006\106\007\105\010\104\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\004\014\011\015\001\001\000\002\001" +
    "\001\000\012\012\050\014\047\015\046\021\051\001\001" +
    "\000\010\013\017\014\022\015\020\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\016\026\017\027\001\001\000" +
    "\002\001\001\000\004\020\033\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\017\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\015\037\001\001\000\002\001\001\000\006\016" +
    "\041\017\027\001\001\000\004\020\033\001\001\000\004" +
    "\014\043\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\012\052\014\047\015\046\021\051\001" +
    "\001\000\002\001\001\000\012\012\054\014\047\015\046" +
    "\021\051\001\001\000\002\001\001\000\012\012\056\014" +
    "\047\015\046\021\051\001\001\000\002\001\001\000\010" +
    "\016\060\017\027\022\061\001\001\000\006\020\033\024" +
    "\101\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\014\066\015\064\023\065\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\070\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\075\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\016\102\017\027\001\001\000\004\020\033\001\001" +
    "\000\002\001\001\000\010\005\107\006\011\007\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\006\106" +
    "\007\105\010\110\001\001\000\010\005\111\006\011\007" +
    "\007\001\001\000\006\006\106\007\105\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= HEADER SEP SIMULATION 
            { parser.Tree.reduce(3,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // HEADER ::= TOKENOTHER 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // HEADER ::= TOKENOTHER TOKEN3 TOKENOTHER 
            { parser.Tree.reduce(3,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // HEADER ::= TOKENOTHER TOKEN3 TOKENOTHER TOKEN3 TOKENOTHER 
            { parser.Tree.reduce(5,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // TOKENOTHER ::= TOKENOTHER TOKEN1 
            { parser.Tree.reduce(2,"TOKENOTHER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKENOTHER",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // TOKENOTHER ::= TOKENOTHER TOKEN2 
            { parser.Tree.reduce(2,"TOKENOTHER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKENOTHER",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TOKENOTHER ::= TOKEN1 
            { parser.Tree.reduce(1,"TOKENOTHER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKENOTHER",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TOKENOTHER ::= TOKEN2 
            { parser.Tree.reduce(1,"TOKENOTHER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKENOTHER",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // TOKEN1 ::= TOK1 SC 
            { parser.Tree.reduce(2,"TOKEN1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKEN1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // TOKEN2 ::= TOK2 SC 
            { parser.Tree.reduce(2,"TOKEN2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKEN2",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // TOKEN3 ::= TOK3 SC 
            { parser.Tree.reduce(2,"TOKEN3",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOKEN3",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SIMULATION ::= INIT COMMANDS 
            { parser.Tree.reduce(2,"SIMULATION",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIMULATION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // INIT ::= INIT_WD SIM2 SC 
            { parser.Tree.reduce(3,"INIT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("INIT",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SIM2 ::= HEIGHTASS CM SPEEDASS 
            { parser.Tree.reduce(3,"SIM2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIM2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SIM2 ::= SPEEDASS CM HEIGHTASS 
            { parser.Tree.reduce(3,"SIM2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIM2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SIM2 ::= HEIGHTASS 
            { parser.Tree.reduce(1,"SIM2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIM2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SIM2 ::= SPEEDASS 
            { parser.Tree.reduce(1,"SIM2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIM2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SIM2 ::= 
            { parser.Tree.reduce(0,"SIM2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIM2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // HEIGHTASS ::= HEIGHT_WD EQ EXPS 
            { parser.Tree.reduce(3,"HEIGHTASS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEIGHTASS",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // SPEEDASS ::= SPEED_WD EQ EXPS 
            { parser.Tree.reduce(3,"SPEEDASS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SPEEDASS",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EXPS ::= EXPS OPER EXP 
            { parser.Tree.reduce(3,"EXPS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPS",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXPS ::= EXP 
            { parser.Tree.reduce(1,"EXPS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPS",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXP ::= INUM 
            { parser.Tree.reduce(1,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // EXP ::= HEIGHT_WD 
            { parser.Tree.reduce(1,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // EXP ::= SPEED_WD 
            { parser.Tree.reduce(1,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // OPER ::= SUM_WD 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // OPER ::= MUL_WD 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // COMMANDS ::= HEIGHTASS SC COMMANDS 
            { parser.Tree.reduce(3,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // COMMANDS ::= SPEEDASS SC COMMANDS 
            { parser.Tree.reduce(3,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // COMMANDS ::= COND COMMANDS 
            { parser.Tree.reduce(2,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // COMMANDS ::= 
            { parser.Tree.reduce(0,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // COND ::= COND_WD OB COMPARISON CB UPDATE_WD ASSES DONE_WD SC 
            { parser.Tree.reduce(8,"COND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // ASSES ::= HEIGHTASS SC SPEEDASS SC 
            { parser.Tree.reduce(4,"ASSES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASSES",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // ASSES ::= SPEEDASS SC HEIGHTASS SC 
            { parser.Tree.reduce(4,"ASSES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASSES",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // ASSES ::= HEIGHTASS SC 
            { parser.Tree.reduce(2,"ASSES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASSES",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // ASSES ::= SPEEDASS SC 
            { parser.Tree.reduce(2,"ASSES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASSES",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // COMPARISON ::= EXPS COMPARISON_COMMAND EXPS 
            { parser.Tree.reduce(3,"COMPARISON",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPARISON",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // COMPARISON ::= 
            { parser.Tree.reduce(0,"COMPARISON",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPARISON",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // COMPARISON_COMMAND ::= GT 
            { parser.Tree.reduce(1,"COMPARISON_COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPARISON_COMMAND",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // COMPARISON_COMMAND ::= EQ 
            { parser.Tree.reduce(1,"COMPARISON_COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPARISON_COMMAND",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
