import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOK1, TOK2, TOK3, SC, SEP, CM, EQ, OB, CB;
terminal String INIT_WD, HEIGHT_WD, SPEED_WD, UPDATE_WD, DONE_WD, COND_WD;
// terminal Double test;
// terminal Integer test;

non terminal prog;
non terminal HEADER, HEADER1, TOKEN1, TOKEN2;
non terminal SIMULATION, HEIGHT_ASS, SPEED_ASS, EXP;
non terminal COND, COMPARE, ASS_LIST;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP SIMULATION
;

// header
HEADER ::= HEADER1 | 
           HEADER1 TOK3 SC HEADER1 |
           HEADER1 TOK3 SC HEADER1 TOK3 SC HEADER1
;
HEADER1 ::= HEADER1 TOKEN1 | HEADER1 TOKEN2 | TOKEN1 | TOKEN2
;

TOKEN1 ::=  TOK1 SC
;
TOKEN2 ::=  TOK2 SC
;

// simulation
SIMULATION ::= INIT_WD SC |
               INIT_WD HEIGHT_ASS SC |
               INIT_WD SPEED_ASS SC |
               INIT_WD HEIGHT_ASS CM SPEED_ASS |
               INIT_WD SPEED_ASS CM HEIGHT_ASS
;

HEIGHT_ASS ::= HEIGHT_WD EQ EXP
;
SPEED_ASS ::= SPEED_WD EQ EXP
;

EXP ::=
;

COND ::= COND_WD OB COMPARE CB UPDATE_WD ASS_LIST DONE_WD
;
ASS_LIST ::= SPEED_ASS COMPARE | HEIGHT_ASS COMPARE | SPEED_ASS | HEIGHT_ASS
;
