import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOK1, TOK2, TOK3, SC, SEP, CM, EQ, OB, CB, GT;
terminal String INIT_WD, HEIGHT_WD, SPEED_WD, UPDATE_WD, DONE_WD, COND_WD, SUM_WD, MUL_WD;
// terminal Double test;
terminal Integer INUM;

non terminal prog;
non terminal HEADER, HEADER1, TOKEN1, TOKEN2;
non terminal SIMULATION, INIT, COMMANDS, COMMAND, COMMAND_REP;
non terminal HEIGHT_ASS, SPEED_ASS, EXP, OPR, OPT;
non terminal COND, COMPARE, ASS_LIST, COM_OPT;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP SIMULATION
;

// header
HEADER ::= HEADER1 | 
           HEADER1 TOK3 SC HEADER1 |
           HEADER1 TOK3 SC HEADER1 TOK3 SC HEADER1
;
HEADER1 ::= HEADER1 TOKEN1 | HEADER1 TOKEN2 | TOKEN1 | TOKEN2
;

TOKEN1 ::=  TOK1 SC
;
TOKEN2 ::=  TOK2 SC
;

// simulation
SIMULATION ::= INIT COMMANDS
;

INIT ::= INIT_WD SC  |
         INIT_WD HEIGHT_ASS |
         INIT_WD SPEED_ASS |
         INIT_WD HEIGHT_WD EQ EXP CM SPEED_WD EQ EXP SC |
         INIT_WD SPEED_WD EQ EXP CM HEIGHT_WD EQ EXP SC  
;
COMMANDS ::= COMMAND COMMAND COMMAND 
;
COMMAND ::= HEIGHT_ASS | SPEED_ASS | COND
;

// height ass
HEIGHT_ASS ::= HEIGHT_WD EQ EXP SC 
;

//speed ass
SPEED_ASS ::= SPEED_WD EQ EXP SC 
;

// exp
EXP ::= EXP OPT OPR | OPR
;
OPT ::= SUM_WD | MUL_WD
;
OPR ::= INUM | SPEED_WD | HEIGHT_WD
;

// cond
COND ::= COND_WD OB COMPARE CB UPDATE_WD ASS_LIST DONE_WD SC | COND_WD OB CB UPDATE_WD ASS_LIST DONE_WD SC
;
ASS_LIST ::= SPEED_ASS ASS_LIST | HEIGHT_ASS ASS_LIST | SPEED_ASS | HEIGHT_ASS
;
COMPARE ::= EXP COM_OPT EXP
;
COM_OPT ::= GT | EQ
;