import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

// terminal TOK1, TOK2, SEP;
terminal TOK1, TOK2, TOK3, SEP;
terminal SC, CM, OP, CP, EQ, DOT;
terminal String HOUSE_WD, START_WD, END_WD, PRINT_WD, IF_WD, FI_WD, NOT_WD, QSTRING, THEN_WD, AND_WD, OR_WD;
// terminal Double test;
terminal Integer INUM;

non terminal prog ;
non terminal HEADER, HOUSES, PREF ;
non terminal HEAD1;
non terminal HOUSE, ROOM_LIST, ROOM, TYPE, ROOM_NAME, SIZE;
non terminal EXP, OPER, OPR, PRINT_LIST, PRINT, COMMAND, COMMANDS, ROOM_REF;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP HOUSES SEP PREF
;

// header

HEADER ::= HEAD1 TOK1 SC HEAD1 | HEAD1 TOK2 SC HEAD1 | HEAD1 TOK1 SC HEAD1 TOK2 SC HEAD1 | HEAD1 TOK2 SC HEAD1 TOK1 SC HEAD1 
;

HEAD1 ::= HEAD1 TOK3 SC |
;

// houses

HOUSES ::= HOUSES HOUSE HOUSE |
;

HOUSE ::= HOUSE_WD TYPE START_WD ROOM_LIST END_WD
;

TYPE ::= QSTRING
;

ROOM_LIST ::= ROOM_LIST CM ROOM | ROOM
;

ROOM ::= ROOM_NAME SIZE 
;

ROOM_NAME ::= QSTRING
;

SIZE ::= INUM
;

// pref

PREF ::= COMMANDS |
;

COMMANDS ::= COMMANDS COMMAND | COMMAND
;

COMMAND ::= IF_WD EXP THEN_WD PRINT_LIST FI_WD
;


EXP ::= OPR | OPR OPER EXP | OP EXP CP | NOT_WD EXP
;

OPER ::= AND_WD | OR_WD | NOT_WD
;

OPR ::= ROOM_REF |  ROOM_REF EQ EQ SIZE
;

ROOM_REF ::= TYPE DOT ROOM_NAME
;

PRINT_LIST ::= PRINT_LIST PRINT |
;

PRINT ::= PRINT_WD QSTRING SC
;