import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Integer>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Integer>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOKEN1, TOKEN2, TOKEN3, SEP;
terminal SC, CM, OP, CP, EQ, DOT;
terminal String HOUSE_WD, START_WD, END_WD, PRINT_WD, IF_WD, FI_WD, NOT_WD, QSTRING, THEN_WD, AND_WD, OR_WD;
// terminal Double test;
terminal Integer INUM;

non terminal prog ;
non terminal HEADER, TOK1, TOK2, TOK3, HOUSES, PREF, HEAD1;
non terminal HOUSE;
non terminal OPER, COMMAND, COMMANDS, ROOM_REF;
non terminal ArrayList PRINT_LIST;
non terminal String PRINT;
non terminal HashMap ROOM_LIST, ROOM;
non terminal Integer ;
// non terminal Double ;
non terminal Boolean OPR, EXP;


// precedence left ;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP HOUSES SEP PREF
;

TOK1 ::= TOKEN1 SC
;

TOK2 ::= TOKEN2 SC
;

TOK3 ::= TOKEN3 SC
;

// header

HEADER ::= HEAD1 TOK1 HEAD1 | HEAD1 TOK2 HEAD1 | HEAD1 TOK1 HEAD1 TOK2 HEAD1 | HEAD1 TOK2 HEAD1 TOK1 HEAD1 
;

HEAD1 ::= HEAD1 TOK3 |
;

// houses

HOUSES ::= HOUSES HOUSE HOUSE |
;

HOUSE ::= HOUSE_WD QSTRING:type START_WD ROOM_LIST:rl END_WD
{:
    table.put(type, rl);
    // System.out.println(rl);
:}
;


ROOM_LIST ::= ROOM_LIST:rl CM ROOM:room
{:
    rl.putAll(room);
    RESULT = rl;
:} 
| ROOM:room
{:
    RESULT = room;
:}
;

ROOM ::= QSTRING:ref INUM:size
{:
    HashMap room = new HashMap <String, Integer>();
    room.put(ref, size);
    RESULT = room;
:} 
;

// pref

PREF ::= COMMANDS |
;

COMMANDS ::= COMMANDS COMMAND | COMMAND
;

COMMAND ::= IF_WD EXP:exp THEN_WD PRINT_LIST:pl FI_WD
{:
    if(exp){
        for(int i=0; i<pl.size(); i++)
        {
            System.out.println(pl.get(i));
        }
    }
:}
;


EXP ::= OPR:opr
{:
    RESULT = opr;
:}
| OPR:opr AND_WD EXP:exp
{:
    // System.out.println(opr);
    // System.out.println(exp);
    // System.out.println("and");
    // System.out.println(opr && exp);
    RESULT = opr && exp;
:}
| OPR:opr OR_WD EXP:exp
{:
    // System.out.println(opr);
    // System.out.println(exp);
    // System.out.println("or");
    // System.out.println(opr || exp);
    RESULT = opr || exp;
:}
| OP EXP:exp CP
{:
    RESULT = exp;
:}
| NOT_WD EXP:exp
{:
    RESULT = !(exp);
:}
;

OPR ::= QSTRING:type DOT QSTRING:name EQ EQ INUM:comp_size
{:
    HashMap <String, Integer> room = table.get(type);
    Integer size = room.get(name);
    // System.out.println(size);
    // System.out.println(comp_size);
    // System.out.println(size==comp_size);
    // System.out.println(size.equals(comp_size));
    RESULT = size.equals(comp_size);
:}
;

PRINT_LIST ::= PRINT_LIST:pl PRINT:p
{:
    pl.add(p);
    RESULT = pl;
:}
| PRINT:p
{:
    ArrayList<String> pl = new ArrayList<String>();
    pl.add(p);
    RESULT = pl;
:}
;

PRINT ::= PRINT_WD QSTRING:q SC
{:
    RESULT = q;
:}
;