
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\043\000\002\002\004\000\002\002\007\000\002\003" +
    "\006\000\002\003\006\000\002\003\011\000\002\003\011" +
    "\000\002\006\005\000\002\006\002\000\002\004\005\000" +
    "\002\004\002\000\002\007\007\000\002\012\003\000\002" +
    "\010\005\000\002\010\003\000\002\011\004\000\002\013" +
    "\003\000\002\014\003\000\002\005\003\000\002\005\002" +
    "\000\002\023\004\000\002\023\003\000\002\022\007\000" +
    "\002\015\003\000\002\015\005\000\002\015\005\000\002" +
    "\015\004\000\002\016\003\000\002\016\003\000\002\016" +
    "\003\000\002\017\003\000\002\017\006\000\002\024\005" +
    "\000\002\020\004\000\002\020\002\000\002\021\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\104\000\010\004\ufffa\005\ufffa\006\ufffa\001\002\000" +
    "\004\007\026\001\002\000\010\004\012\005\011\006\010" +
    "\001\002\000\004\002\007\001\002\000\004\002\001\001" +
    "\002\000\004\010\025\001\002\000\004\010\020\001\002" +
    "\000\004\010\013\001\002\000\010\005\ufffa\006\ufffa\007" +
    "\ufffa\001\002\000\010\005\015\006\010\007\uffff\001\002" +
    "\000\004\010\016\001\002\000\006\006\ufffa\007\ufffa\001" +
    "\002\000\006\006\010\007\ufffd\001\002\000\010\004\ufffa" +
    "\006\ufffa\007\ufffa\001\002\000\010\004\022\006\010\007" +
    "\ufffe\001\002\000\004\010\023\001\002\000\006\006\ufffa" +
    "\007\ufffa\001\002\000\006\006\010\007\ufffc\001\002\000" +
    "\012\004\ufffb\005\ufffb\006\ufffb\007\ufffb\001\002\000\006" +
    "\007\ufff8\016\ufff8\001\002\000\006\007\030\016\032\001" +
    "\002\000\006\002\uffef\022\052\001\002\000\004\016\032" +
    "\001\002\000\004\025\033\001\002\000\006\015\ufff6\017" +
    "\ufff6\001\002\000\004\017\035\001\002\000\004\025\041" +
    "\001\002\000\004\031\045\001\002\000\006\011\ufff4\020" +
    "\ufff4\001\002\000\006\011\042\020\043\001\002\000\020" +
    "\013\ufff2\014\ufff2\024\ufff2\026\ufff2\027\ufff2\030\ufff2\031" +
    "\ufff2\001\002\000\004\025\041\001\002\000\006\007\ufff7" +
    "\016\ufff7\001\002\000\006\011\ufff5\020\ufff5\001\002\000" +
    "\020\011\ufff1\013\ufff1\020\ufff1\024\ufff1\026\ufff1\027\ufff1" +
    "\030\ufff1\001\002\000\006\011\ufff3\020\ufff3\001\002\000" +
    "\006\007\ufff9\016\ufff9\001\002\000\006\002\uffed\022\uffed" +
    "\001\002\000\004\002\000\001\002\000\010\012\055\024" +
    "\057\025\033\001\002\000\006\002\ufff0\022\052\001\002" +
    "\000\006\002\uffee\022\uffee\001\002\000\010\012\055\024" +
    "\057\025\033\001\002\000\014\013\uffeb\024\101\026\uffeb" +
    "\027\100\030\103\001\002\000\010\012\055\024\057\025" +
    "\033\001\002\000\004\026\070\001\002\000\016\013\uffe4" +
    "\014\065\024\uffe4\026\uffe4\027\uffe4\030\uffe4\001\002\000" +
    "\004\015\063\001\002\000\004\025\041\001\002\000\016" +
    "\013\uffe2\014\uffe2\024\uffe2\026\uffe2\027\uffe2\030\uffe2\001" +
    "\002\000\004\014\066\001\002\000\004\031\045\001\002" +
    "\000\014\013\uffe3\024\uffe3\026\uffe3\027\uffe3\030\uffe3\001" +
    "\002\000\006\021\uffe0\023\uffe0\001\002\000\006\021\074" +
    "\023\073\001\002\000\006\021\uffe1\023\uffe1\001\002\000" +
    "\006\002\uffec\022\uffec\001\002\000\004\025\075\001\002" +
    "\000\004\010\076\001\002\000\006\021\uffdf\023\uffdf\001" +
    "\002\000\006\013\uffe8\026\uffe8\001\002\000\010\012\uffe7" +
    "\024\uffe7\025\uffe7\001\002\000\010\012\uffe5\024\uffe5\025" +
    "\uffe5\001\002\000\010\012\055\024\057\025\033\001\002" +
    "\000\010\012\uffe6\024\uffe6\025\uffe6\001\002\000\006\013" +
    "\uffea\026\uffea\001\002\000\004\013\106\001\002\000\006" +
    "\013\uffe9\026\uffe9\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\104\000\010\002\005\003\003\006\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\013\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\006\016\001\001\000\002\001\001\000" +
    "\004\006\020\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\023\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\026\001\001\000\004\007\030\001\001" +
    "\000\010\005\050\022\047\023\052\001\001\000\004\007" +
    "\046\001\001\000\004\012\033\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\010\037\011\036\013\035\001" +
    "\001\000\004\014\045\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\011\043\013\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\012\061\015\057\017\055\024\060" +
    "\001\001\000\004\022\053\001\001\000\002\001\001\000" +
    "\012\012\061\015\104\017\055\024\060\001\001\000\004" +
    "\016\101\001\001\000\012\012\061\015\076\017\055\024" +
    "\060\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\063\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\066\001\001\000\002\001\001" +
    "\000\004\020\070\001\001\000\004\021\071\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\012\061\015\103\017\055" +
    "\024\060\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= HEADER SEP HOUSES SEP PREF 
            { parser.Tree.reduce(5,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // HEADER ::= HEAD1 TOK1 SC HEAD1 
            { parser.Tree.reduce(4,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // HEADER ::= HEAD1 TOK2 SC HEAD1 
            { parser.Tree.reduce(4,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // HEADER ::= HEAD1 TOK1 SC HEAD1 TOK2 SC HEAD1 
            { parser.Tree.reduce(7,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // HEADER ::= HEAD1 TOK2 SC HEAD1 TOK1 SC HEAD1 
            { parser.Tree.reduce(7,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // HEAD1 ::= HEAD1 TOK3 SC 
            { parser.Tree.reduce(3,"HEAD1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // HEAD1 ::= 
            { parser.Tree.reduce(0,"HEAD1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // HOUSES ::= HOUSES HOUSE HOUSE 
            { parser.Tree.reduce(3,"HOUSES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HOUSES",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // HOUSES ::= 
            { parser.Tree.reduce(0,"HOUSES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HOUSES",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // HOUSE ::= HOUSE_WD TYPE START_WD ROOM_LIST END_WD 
            { parser.Tree.reduce(5,"HOUSE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HOUSE",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // TYPE ::= QSTRING 
            { parser.Tree.reduce(1,"TYPE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TYPE",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ROOM_LIST ::= ROOM_LIST CM ROOM 
            { parser.Tree.reduce(3,"ROOM_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ROOM_LIST",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ROOM_LIST ::= ROOM 
            { parser.Tree.reduce(1,"ROOM_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ROOM_LIST",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ROOM ::= ROOM_NAME SIZE 
            { parser.Tree.reduce(2,"ROOM",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ROOM",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ROOM_NAME ::= QSTRING 
            { parser.Tree.reduce(1,"ROOM_NAME",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ROOM_NAME",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SIZE ::= INUM 
            { parser.Tree.reduce(1,"SIZE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SIZE",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // PREF ::= COMMANDS 
            { parser.Tree.reduce(1,"PREF",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PREF",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // PREF ::= 
            { parser.Tree.reduce(0,"PREF",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PREF",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // COMMANDS ::= COMMANDS COMMAND 
            { parser.Tree.reduce(2,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // COMMANDS ::= COMMAND 
            { parser.Tree.reduce(1,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // COMMAND ::= IF_WD EXP THEN_WD PRINT_LIST FI_WD 
            { parser.Tree.reduce(5,"COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMAND",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // EXP ::= OPR 
            { parser.Tree.reduce(1,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // EXP ::= OPR OPER EXP 
            { parser.Tree.reduce(3,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // EXP ::= OP EXP CP 
            { parser.Tree.reduce(3,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // EXP ::= NOT_WD EXP 
            { parser.Tree.reduce(2,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // OPER ::= AND_WD 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // OPER ::= OR_WD 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPER ::= NOT_WD 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPR ::= ROOM_REF 
            { parser.Tree.reduce(1,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OPR ::= ROOM_REF EQ EQ SIZE 
            { parser.Tree.reduce(4,"OPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPR",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ROOM_REF ::= TYPE DOT ROOM_NAME 
            { parser.Tree.reduce(3,"ROOM_REF",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ROOM_REF",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // PRINT_LIST ::= PRINT_LIST PRINT 
            { parser.Tree.reduce(2,"PRINT_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT_LIST",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // PRINT_LIST ::= 
            { parser.Tree.reduce(0,"PRINT_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT_LIST",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // PRINT ::= PRINT_WD QSTRING SC 
            { parser.Tree.reduce(3,"PRINT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
