import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Integer>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Integer>>table;

    public void report_error(String message, Object info) {
        System.err.print("ERROR: Syntax error");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.print(" (line "+line+", column "+column+"): ");
            } else System.err.print(": ");
        else System.err.print(": ");
    }

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

:};


 //     //  DEBUG: Print the stack content
    // for (int i = 0; i < 15; i++) {
    //     try {
    //         Object obj = parser.stack(-i);
    //         System.out.println("parser.stack(" + (-i) + ") = " + obj);
    //     } catch (Exception e) {
    //         break;
    //     }
    // };

/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal SEP, TOK1, TOK2, TOK3, HOUSE_WD ,START_WD, END_WD, CM, IF_WD, FI_WD, THEN_WD, AND, OR, NOT, OP, CP, DOT, EQQ, PRINT_WD, SC ;
terminal String QSTRING;
// terminal Double test;
terminal Integer INUM;

non terminal prog, HEADER, TOK3REP ;
non terminal HOUSES, HOUSE ;
non terminal PREFRENCES, IF,PRINT_LIST ;
non terminal HashMap <String, Integer> ROOM_LIST ;
non terminal Boolean BOOL_EXP;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

precedence left AND, OR ;
precedence left NOT;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP HOUSES SEP PREFRENCES
;

HEADER ::= TOK3REP TOK1 TOK3REP TOK2 TOK3REP | TOK3REP TOK2 TOK3REP TOK1 TOK3REP
;

TOK3REP ::= TOK3REP TOK3 |
;

HOUSES ::= HOUSES HOUSE HOUSE | HOUSE HOUSE 
;

HOUSE ::= HOUSE_WD QSTRING:x START_WD ROOM_LIST:tab END_WD {:parser.table.put(x,tab);:}
;

ROOM_LIST ::= ROOM_LIST:tab CM QSTRING:x INUM:y {:
tab.put(x,y);
RESULT = tab;
:}
| QSTRING:x INUM:y {:
HashMap <String, Integer> tab = new HashMap <String, Integer>();
tab.put(x,y);
RESULT = tab;
:}
;


//PREFRENCES


PREFRENCES ::= PREFRENCES IF | 
;

IF ::= IF_WD BOOL_EXP THEN_WD PRINT_LIST FI_WD
;

BOOL_EXP ::=    BOOL_EXP:x AND BOOL_EXP:y {:RESULT = x & y;:}
            |   BOOL_EXP:x OR BOOL_EXP:y {:RESULT = x | y;:}
            |   NOT BOOL_EXP:x {:RESULT = !x;:}
            |   OP BOOL_EXP:x CP {:RESULT = x;:}
            |   QSTRING:first DOT QSTRING:second EQQ INUM:number {:
            HashMap <String, Integer> list = parser.table.get(first);
            Integer num = list.get(second);
            if(num.equals(number)){
                RESULT = true;
            };
            if(!num.equals(number)){
                RESULT = false;
            };
            :}
;

PRINT_LIST ::= PRINT_LIST PRINT_WD QSTRING:x SC {:
Boolean myBool = (Boolean)parser.stack(-5);
if(myBool == true){
    System.out.println(x);
};
:}
| PRINT_WD QSTRING:x SC  {:
Boolean myBool = (Boolean)parser.stack(-4);
if(myBool == true){
    System.out.println(x);
};
:}
;