
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CP = 9;
  public static final int THEN_WD = 20;
  public static final int CM = 7;
  public static final int IF_WD = 16;
  public static final int OP = 8;
  public static final int AND_WD = 21;
  public static final int INUM = 23;
  public static final int NOT_WD = 18;
  public static final int EOF = 0;
  public static final int TOK3 = 4;
  public static final int START_WD = 13;
  public static final int OR_WD = 22;
  public static final int TOK2 = 3;
  public static final int SEP = 5;
  public static final int TOK1 = 2;
  public static final int error = 1;
  public static final int DOT = 11;
  public static final int EQ = 10;
  public static final int FI_WD = 17;
  public static final int END_WD = 14;
  public static final int QSTRING = 19;
  public static final int SC = 6;
  public static final int PRINT_WD = 15;
  public static final int HOUSE_WD = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOK1",
  "TOK2",
  "TOK3",
  "SEP",
  "SC",
  "CM",
  "OP",
  "CP",
  "EQ",
  "DOT",
  "HOUSE_WD",
  "START_WD",
  "END_WD",
  "PRINT_WD",
  "IF_WD",
  "FI_WD",
  "NOT_WD",
  "QSTRING",
  "THEN_WD",
  "AND_WD",
  "OR_WD",
  "INUM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[9]=new String("CP");
		TT[20]=new String("THEN_WD");
		TT[7]=new String("CM");
		TT[16]=new String("IF_WD");
		TT[8]=new String("OP");
		TT[21]=new String("AND_WD");
		TT[23]=new String("INUM");
		TT[18]=new String("NOT_WD");
		TT[0]=new String("EOF");
		TT[4]=new String("TOK3");
		TT[13]=new String("START_WD");
		TT[22]=new String("OR_WD");
		TT[3]=new String("TOK2");
		TT[5]=new String("SEP");
		TT[2]=new String("TOK1");
		TT[1]=new String("error");
		TT[11]=new String("DOT");
		TT[10]=new String("EQ");
		TT[17]=new String("FI_WD");
		TT[14]=new String("END_WD");
		TT[19]=new String("QSTRING");
		TT[6]=new String("SC");
		TT[15]=new String("PRINT_WD");
		TT[12]=new String("HOUSE_WD");
	}
public String getTT(int i){return TT[i];}
}

