import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOK1, TOK2;
terminal SEP, SC, CM, OC, CC, CO;
terminal String EURO_KG_WD, KG_WD, EURO_WD, QSTRING;
terminal Double FNUM;
terminal Integer INUM;

non terminal prog, HEADER, WAREHOUSE, PRODUCTS;
non terminal HEADER1, HEAD1_TOK1_REP, HEAD1_TOK2, HEAD1_TOK2_SET3;
non terminal HEADER2, HEAD2_TOK1;
non terminal MATERIAL_TYPES, MATERIAL_TYPE, MATERIAL_LIST, MATERIAL, MAT_TYPE_NAME, MAT_NAME;
non terminal PRODUCT, PRODUCT_NAME, TAX, ELEMENT_LIST, ELEMENT, COMPONENT_LIST, COMPONENT, QUANTITY;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP WAREHOUSE SEP PRODUCTS
;

// header
HEADER ::= HEADER1 | HEADER2
;

//header1
HEADER1 ::= TOK1 SC TOK1 SC HEAD1_TOK1_REP HEAD1_TOK2
;
HEAD1_TOK1_REP ::= TOK1 SC TOK1 SC | HEAD1_TOK1_REP TOK1 SC TOK1 SC
;
HEAD1_TOK2 ::= HEAD1_TOK2_SET3 | HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 |
HEAD1_TOK2_SET3  HEAD1_TOK2_SET3  HEAD1_TOK2_SET3  HEAD1_TOK2_SET3 
;
HEAD1_TOK2_SET3 ::= TOK2 SC TOK2 SC TOK2 SC
;

//header2
HEADER2 ::= TOK2 SC  HEAD2_TOK1 TOK2 SC HEAD2_TOK1 TOK2 SC HEAD2_TOK1 |
            TOK2 SC  HEAD2_TOK1 TOK2 SC HEAD2_TOK1
;
HEAD2_TOK1 ::=  HEAD2_TOK1 SC | TOK1 SC | 
;

//warehouse
WAREHOUSE ::= MATERIAL_TYPE MATERIAL_TYPE MATERIAL_TYPES
;
MATERIAL_TYPES ::= MATERIAL_TYPE MATERIAL_TYPE MATERIAL_TYPES |
;
MATERIAL_TYPE ::= OC MATERIAL_LIST CC MAT_TYPE_NAME SC
;
MATERIAL_LIST ::= MATERIAL | MATERIAL CM MATERIAL_LIST
;
MATERIAL ::= MAT_NAME FNUM EURO_KG_WD
;
MAT_NAME ::= QSTRING
;
MAT_TYPE_NAME ::= QSTRING
;

//products
PRODUCTS ::= PRODUCTS PRODUCT | PRODUCT |
;
PRODUCT ::= TAX EURO_WD PRODUCT_NAME CO ELEMENT_LIST SC
;
TAX ::= FNUM
;
PRODUCT_NAME ::= QSTRING
;
ELEMENT_LIST ::= ELEMENT_LIST CM ELEMENT | ELEMENT
;
ELEMENT ::= MAT_TYPE_NAME OC COMPONENT_LIST CC
;
COMPONENT_LIST ::= COMPONENT_LIST CM COMPONENT | COMPONENT
;
COMPONENT ::= MAT_NAME QUANTITY KG_WD
;
QUANTITY ::= INUM
;