import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////


terminal TOK1, TOK2, SC, SEP, CM, OC, CC, CO;
terminal String EURO_KG_WD, KG_WD, QSTRING, EURO_WD;
terminal Double FNUM;
terminal Integer INUM;

non terminal prog ;
non terminal HEADER, WAREHOUSE, PRODUCTS ;
non terminal HEADER1,HEADER2 ,TOK1REP ,TOK2REP, TOK1REP2, TOK1SC,TOK2SC;
non terminal MATERIAL_TYPES, MATERIAL_TYPE, MATERIAL_LIST, MATERIAL;
non terminal PRODUCT, ELEMENT_LISTS, ELEMENT_LIST, COMPONENTS, COMPONENT;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;
// precedence left PLUS, DASH;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP WAREHOUSE SEP PRODUCTS
;

HEADER ::= HEADER1 | HEADER2
;

HEADER1 ::= TOK1 TOK1 TOK1REP TOK2REP
;

TOK1REP ::= TOK1SC TOK1SC 
;

TOK2REP ::= TOK2SC TOK2SC TOK2SC |
            TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC |
            TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC 
;

HEADER2 ::=  TOK2SC TOK1REP2 TOK2SC TOK1REP2 |
                TOK2SC TOK1REP2 TOK2SC TOK1REP2 TOK2SC TOK1REP2
;

TOK1REP2 ::= TOK1REP2 SC |TOK1 SC |
;

TOK2SC ::= TOK2 SC
;

//

WAREHOUSE ::= MATERIAL_TYPES
;

MATERIAL_TYPES ::= MATERIAL_TYPE MATERIAL_TYPE  | MATERIAL_TYPE MATERIAL_TYPE MATERIAL_TYPES
;

MATERIAL_TYPE ::= OC MATERIAL_LIST CC QSTRING SC
;

MATERIAL_LIST ::= MATERIAL | MATERIAL_LIST CM MATERIAL  
;

MATERIAL ::= QSTRING FNUM EURO_KG_WD
;

//

PRODUCTS ::= PRODUCTS PRODUCT | 
;

PRODUCT ::= FNUM EURO_WD QSTRING CO ELEMENT_LISTS SC
;

ELEMENT_LISTS ::= ELEMENT_LIST | ELEMENT_LISTS CM ELEMENT_LIST 
;

ELEMENT_LIST ::= QSTRING OC COMPONENTS CC
;

COMPONENTS ::=COMPONENT | COMPONENTS CM COMPONENT |
;

COMPONENT ::= QSTRING INUM KG_WD
;
