
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\031\000\002\002\004\000\002\002\007\000\002\003" +
    "\003\000\002\003\003\000\002\006\010\000\002\007\006" +
    "\000\002\007\007\000\002\010\003\000\002\010\005\000" +
    "\002\010\006\000\002\011\010\000\002\012\013\000\002" +
    "\012\010\000\002\013\004\000\002\013\004\000\002\013" +
    "\002\000\002\004\005\000\002\014\005\000\002\014\002" +
    "\000\002\015\007\000\002\016\003\000\002\016\005\000" +
    "\002\017\005\000\002\021\003\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\101\000\006\004\006\005\005\001\002\000\004\006" +
    "\ufffe\001\002\000\004\007\071\001\002\000\004\007\042" +
    "\001\002\000\004\006\uffff\001\002\000\004\006\013\001" +
    "\002\000\004\002\012\001\002\000\004\002\001\001\002" +
    "\000\004\011\014\001\002\000\004\015\031\001\002\000" +
    "\004\006\024\001\002\000\004\011\014\001\002\000\006" +
    "\006\uffef\011\014\001\002\000\004\006\ufff1\001\002\000" +
    "\004\011\014\001\002\000\006\006\uffef\011\014\001\002" +
    "\000\004\006\ufff0\001\002\000\002\001\002\000\004\002" +
    "\000\001\002\000\004\012\036\001\002\000\004\016\034" +
    "\001\002\000\006\010\032\012\uffed\001\002\000\004\016" +
    "\uffea\001\002\000\004\015\031\001\002\000\004\012\uffec" +
    "\001\002\000\004\013\035\001\002\000\006\010\uffeb\012" +
    "\uffeb\001\002\000\004\015\040\001\002\000\004\007\041" +
    "\001\002\000\004\007\uffe9\001\002\000\006\006\uffee\011" +
    "\uffee\001\002\000\004\004\043\001\002\000\004\007\044" +
    "\001\002\000\004\004\045\001\002\000\004\007\066\001" +
    "\002\000\006\004\052\005\051\001\002\000\004\006\ufffd" +
    "\001\002\000\006\005\051\006\ufffa\001\002\000\004\007" +
    "\056\001\002\000\004\007\053\001\002\000\004\004\054" +
    "\001\002\000\004\007\055\001\002\000\006\004\ufffb\005" +
    "\ufffb\001\002\000\004\005\057\001\002\000\004\007\060" +
    "\001\002\000\004\005\061\001\002\000\004\007\062\001" +
    "\002\000\006\005\ufff7\006\ufff7\001\002\000\004\005\051" +
    "\001\002\000\006\005\051\006\ufff9\001\002\000\004\006" +
    "\ufff8\001\002\000\004\004\067\001\002\000\004\007\070" +
    "\001\002\000\006\004\ufffc\005\ufffc\001\002\000\010\004" +
    "\073\005\ufff2\007\ufff2\001\002\000\006\005\075\007\076" +
    "\001\002\000\004\007\074\001\002\000\010\005\ufff3\006" +
    "\ufff3\007\ufff3\001\002\000\004\007\077\001\002\000\010" +
    "\005\ufff4\006\ufff4\007\ufff4\001\002\000\012\004\073\005" +
    "\ufff2\006\ufff2\007\ufff2\001\002\000\010\005\101\006\ufff5" +
    "\007\076\001\002\000\004\007\102\001\002\000\010\004" +
    "\073\006\ufff2\007\ufff2\001\002\000\006\006\ufff6\007\076" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\101\000\012\002\010\003\007\006\006\012\003\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\014\015\015\001\001\000\010" +
    "\016\025\017\027\021\026\001\001\000\002\001\001\000" +
    "\004\015\016\001\001\000\006\014\017\015\020\001\001" +
    "\000\002\001\001\000\004\015\021\001\001\000\006\014" +
    "\022\015\020\001\001\000\002\001\001\000\004\005\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\016\032" +
    "\017\027\021\026\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\020\036\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\045\001\001\000\002" +
    "\001\001\000\006\010\046\011\047\001\001\000\002\001" +
    "\001\000\004\011\062\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\063\001" +
    "\001\000\004\011\064\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\071\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\077\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\102\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= HEADER SEP WAREHOUSE SEP PRODUCTS 
            { parser.Tree.reduce(5,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // HEADER ::= HEADER1 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // HEADER ::= HEADER2 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // HEADER1 ::= TOK1 SC TOK1 SC HEAD1_TOK1_REP HEAD1_TOK2 
            { parser.Tree.reduce(6,"HEADER1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // HEAD1_TOK1_REP ::= TOK1 SC TOK1 SC 
            { parser.Tree.reduce(4,"HEAD1_TOK1_REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1_TOK1_REP",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // HEAD1_TOK1_REP ::= HEAD1_TOK1_REP TOK1 SC TOK1 SC 
            { parser.Tree.reduce(5,"HEAD1_TOK1_REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1_TOK1_REP",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // HEAD1_TOK2 ::= HEAD1_TOK2_SET3 
            { parser.Tree.reduce(1,"HEAD1_TOK2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1_TOK2",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // HEAD1_TOK2 ::= HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 
            { parser.Tree.reduce(3,"HEAD1_TOK2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1_TOK2",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // HEAD1_TOK2 ::= HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 HEAD1_TOK2_SET3 
            { parser.Tree.reduce(4,"HEAD1_TOK2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1_TOK2",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // HEAD1_TOK2_SET3 ::= TOK2 SC TOK2 SC TOK2 SC 
            { parser.Tree.reduce(6,"HEAD1_TOK2_SET3",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD1_TOK2_SET3",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // HEADER2 ::= TOK2 SC HEAD2_TOK1 TOK2 SC HEAD2_TOK1 TOK2 SC HEAD2_TOK1 
            { parser.Tree.reduce(9,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // HEADER2 ::= TOK2 SC HEAD2_TOK1 TOK2 SC HEAD2_TOK1 
            { parser.Tree.reduce(6,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // HEAD2_TOK1 ::= HEAD2_TOK1 SC 
            { parser.Tree.reduce(2,"HEAD2_TOK1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD2_TOK1",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // HEAD2_TOK1 ::= TOK1 SC 
            { parser.Tree.reduce(2,"HEAD2_TOK1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD2_TOK1",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // HEAD2_TOK1 ::= 
            { parser.Tree.reduce(0,"HEAD2_TOK1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEAD2_TOK1",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // WAREHOUSE ::= MATERIAL_TYPE MATERIAL_TYPE MATERIAL_TYPES 
            { parser.Tree.reduce(3,"WAREHOUSE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("WAREHOUSE",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // MATERIAL_TYPES ::= MATERIAL_TYPE MATERIAL_TYPE MATERIAL_TYPES 
            { parser.Tree.reduce(3,"MATERIAL_TYPES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_TYPES",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // MATERIAL_TYPES ::= 
            { parser.Tree.reduce(0,"MATERIAL_TYPES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_TYPES",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // MATERIAL_TYPE ::= OC MATERIAL_LIST CC MAT_TYPE_NAME SC 
            { parser.Tree.reduce(5,"MATERIAL_TYPE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_TYPE",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // MATERIAL_LIST ::= MATERIAL 
            { parser.Tree.reduce(1,"MATERIAL_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_LIST",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // MATERIAL_LIST ::= MATERIAL CM MATERIAL_LIST 
            { parser.Tree.reduce(3,"MATERIAL_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_LIST",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // MATERIAL ::= MAT_NAME FNUM EURO_KG_WD 
            { parser.Tree.reduce(3,"MATERIAL",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // MAT_NAME ::= QSTRING 
            { parser.Tree.reduce(1,"MAT_NAME",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MAT_NAME",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // MAT_TYPE_NAME ::= QSTRING 
            { parser.Tree.reduce(1,"MAT_TYPE_NAME",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MAT_TYPE_NAME",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
