
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\002\004\000\002\002\007\000\002\003" +
    "\003\000\002\003\003\000\002\006\006\000\002\010\004" +
    "\000\002\011\005\000\002\011\013\000\002\011\016\000" +
    "\002\007\006\000\002\007\010\000\002\012\004\000\002" +
    "\012\004\000\002\012\002\000\002\014\004\000\002\004" +
    "\003\000\002\015\004\000\002\015\005\000\002\016\007" +
    "\000\002\017\003\000\002\017\005\000\002\020\005\000" +
    "\002\005\004\000\002\005\002\000\002\021\010\000\002" +
    "\022\003\000\002\022\005\000\002\023\006\000\002\024" +
    "\003\000\002\024\005\000\002\024\002\000\002\025\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\112\000\006\004\006\005\005\001\002\000\004\007" +
    "\ufffe\001\002\000\004\006\114\001\002\000\004\004\073" +
    "\001\002\000\004\007\uffff\001\002\000\004\007\024\001" +
    "\002\000\004\002\023\001\002\000\010\004\013\005\ufff4" +
    "\006\ufff4\001\002\000\004\006\022\001\002\000\006\005" +
    "\005\006\015\001\002\000\010\005\ufff6\006\ufff6\007\ufff6" +
    "\001\002\000\012\004\013\005\ufff4\006\ufff4\007\ufff4\001" +
    "\002\000\010\005\005\006\015\007\ufff8\001\002\000\010" +
    "\004\013\006\ufff4\007\ufff4\001\002\000\006\006\015\007" +
    "\ufff7\001\002\000\010\005\ufff5\006\ufff5\007\ufff5\001\002" +
    "\000\004\002\001\001\002\000\004\011\025\001\002\000" +
    "\004\016\063\001\002\000\004\007\ufff2\001\002\000\004" +
    "\007\033\001\002\000\004\011\025\001\002\000\006\007" +
    "\ufff1\011\025\001\002\000\004\007\ufff0\001\002\000\006" +
    "\002\uffea\020\uffea\001\002\000\006\002\000\020\036\001" +
    "\002\000\006\002\uffeb\020\uffeb\001\002\000\004\017\037" +
    "\001\002\000\004\016\040\001\002\000\004\013\041\001" +
    "\002\000\004\016\044\001\002\000\006\006\uffe8\010\uffe8" +
    "\001\002\000\006\006\057\010\056\001\002\000\004\011" +
    "\045\001\002\000\010\010\uffe3\012\uffe3\016\050\001\002" +
    "\000\006\010\054\012\053\001\002\000\006\010\uffe5\012" +
    "\uffe5\001\002\000\004\021\051\001\002\000\004\015\052" +
    "\001\002\000\006\010\uffe2\012\uffe2\001\002\000\006\006" +
    "\uffe6\010\uffe6\001\002\000\004\016\050\001\002\000\006" +
    "\010\uffe4\012\uffe4\001\002\000\004\016\044\001\002\000" +
    "\006\002\uffe9\020\uffe9\001\002\000\006\006\uffe7\010\uffe7" +
    "\001\002\000\006\010\067\012\066\001\002\000\006\010" +
    "\uffee\012\uffee\001\002\000\004\020\064\001\002\000\004" +
    "\014\065\001\002\000\006\010\uffec\012\uffec\001\002\000" +
    "\004\016\071\001\002\000\004\016\063\001\002\000\006" +
    "\010\uffed\012\uffed\001\002\000\004\006\072\001\002\000" +
    "\006\007\uffef\011\uffef\001\002\000\002\001\002\000\002" +
    "\001\002\000\004\005\005\001\002\000\004\007\ufffd\001" +
    "\002\000\004\005\005\001\002\000\004\005\005\001\002" +
    "\000\006\005\005\007\ufffb\001\002\000\004\005\005\001" +
    "\002\000\004\005\005\001\002\000\004\005\005\001\002" +
    "\000\004\005\005\001\002\000\004\005\005\001\002\000" +
    "\006\005\005\007\ufffa\001\002\000\004\005\005\001\002" +
    "\000\004\005\005\001\002\000\004\007\ufff9\001\002\000" +
    "\004\005\ufffc\001\002\000\012\004\ufff3\005\ufff3\006\ufff3" +
    "\007\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\112\000\014\002\010\003\007\006\006\007\003\014" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\013\001\001\000\002\001\001\000\004" +
    "\014\015\001\001\000\002\001\001\000\004\012\016\001" +
    "\001\000\004\014\017\001\001\000\004\012\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\004\026\015\025\016\027\001\001\000\006\017\060" +
    "\020\061\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\016\030\001\001\000\006\015\031\016\027\001\001" +
    "\000\002\001\001\000\004\005\033\001\001\000\004\021" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\022\042\023\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\024\045\025\046\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\025\054\001\001\000" +
    "\002\001\001\000\004\023\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\020\067\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\010\074\013\073" +
    "\001\001\000\004\013\112\001\001\000\006\011\075\014" +
    "\076\001\001\000\002\001\001\000\004\014\077\001\001" +
    "\000\004\014\100\001\001\000\004\014\101\001\001\000" +
    "\004\014\102\001\001\000\004\014\103\001\001\000\004" +
    "\014\104\001\001\000\004\014\105\001\001\000\004\014" +
    "\106\001\001\000\004\014\107\001\001\000\004\014\110" +
    "\001\001\000\004\014\111\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= HEADER SEP WAREHOUSE SEP PRODUCTS 
            { parser.Tree.reduce(5,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // HEADER ::= HEADER1 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // HEADER ::= HEADER2 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // HEADER1 ::= TOK1 TOK1 TOK1REP TOK2REP 
            { parser.Tree.reduce(4,"HEADER1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // TOK1REP ::= TOK1SC TOK1SC 
            { parser.Tree.reduce(2,"TOK1REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1REP",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // TOK2REP ::= TOK2SC TOK2SC TOK2SC 
            { parser.Tree.reduce(3,"TOK2REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2REP",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TOK2REP ::= TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC 
            { parser.Tree.reduce(9,"TOK2REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2REP",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TOK2REP ::= TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC TOK2SC 
            { parser.Tree.reduce(12,"TOK2REP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2REP",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // HEADER2 ::= TOK2SC TOK1REP2 TOK2SC TOK1REP2 
            { parser.Tree.reduce(4,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // HEADER2 ::= TOK2SC TOK1REP2 TOK2SC TOK1REP2 TOK2SC TOK1REP2 
            { parser.Tree.reduce(6,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // TOK1REP2 ::= TOK1REP2 SC 
            { parser.Tree.reduce(2,"TOK1REP2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1REP2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // TOK1REP2 ::= TOK1 SC 
            { parser.Tree.reduce(2,"TOK1REP2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1REP2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // TOK1REP2 ::= 
            { parser.Tree.reduce(0,"TOK1REP2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1REP2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // TOK2SC ::= TOK2 SC 
            { parser.Tree.reduce(2,"TOK2SC",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2SC",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // WAREHOUSE ::= MATERIAL_TYPES 
            { parser.Tree.reduce(1,"WAREHOUSE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("WAREHOUSE",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // MATERIAL_TYPES ::= MATERIAL_TYPE MATERIAL_TYPE 
            { parser.Tree.reduce(2,"MATERIAL_TYPES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_TYPES",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // MATERIAL_TYPES ::= MATERIAL_TYPE MATERIAL_TYPE MATERIAL_TYPES 
            { parser.Tree.reduce(3,"MATERIAL_TYPES",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_TYPES",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // MATERIAL_TYPE ::= OC MATERIAL_LIST CC QSTRING SC 
            { parser.Tree.reduce(5,"MATERIAL_TYPE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_TYPE",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // MATERIAL_LIST ::= MATERIAL 
            { parser.Tree.reduce(1,"MATERIAL_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_LIST",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // MATERIAL_LIST ::= MATERIAL_LIST CM MATERIAL 
            { parser.Tree.reduce(3,"MATERIAL_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL_LIST",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // MATERIAL ::= QSTRING FNUM EURO_KG_WD 
            { parser.Tree.reduce(3,"MATERIAL",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATERIAL",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // PRODUCTS ::= PRODUCTS PRODUCT 
            { parser.Tree.reduce(2,"PRODUCTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRODUCTS",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // PRODUCTS ::= 
            { parser.Tree.reduce(0,"PRODUCTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRODUCTS",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // PRODUCT ::= FNUM EURO_WD QSTRING CO ELEMENT_LISTS SC 
            { parser.Tree.reduce(6,"PRODUCT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRODUCT",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // ELEMENT_LISTS ::= ELEMENT_LIST 
            { parser.Tree.reduce(1,"ELEMENT_LISTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ELEMENT_LISTS",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ELEMENT_LISTS ::= ELEMENT_LISTS CM ELEMENT_LIST 
            { parser.Tree.reduce(3,"ELEMENT_LISTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ELEMENT_LISTS",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ELEMENT_LIST ::= QSTRING OC COMPONENTS CC 
            { parser.Tree.reduce(4,"ELEMENT_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ELEMENT_LIST",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // COMPONENTS ::= COMPONENT 
            { parser.Tree.reduce(1,"COMPONENTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPONENTS",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // COMPONENTS ::= COMPONENTS CM COMPONENT 
            { parser.Tree.reduce(3,"COMPONENTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPONENTS",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // COMPONENTS ::= 
            { parser.Tree.reduce(0,"COMPONENTS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPONENTS",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // COMPONENT ::= QSTRING INUM KG_WD 
            { parser.Tree.reduce(3,"COMPONENT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPONENT",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
