
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\037\000\002\002\004\000\002\002\007\000\002\003" +
    "\004\000\002\004\004\000\002\005\004\000\002\006\003" +
    "\000\002\006\003\000\002\007\007\000\002\010\005\000" +
    "\002\010\002\000\002\011\005\000\002\011\013\000\002" +
    "\011\014\000\002\012\004\000\002\012\006\000\002\013" +
    "\004\000\002\013\004\000\002\013\002\000\002\014\006" +
    "\000\002\015\005\000\002\015\002\000\002\016\006\000" +
    "\002\023\005\000\002\023\003\000\002\024\006\000\002" +
    "\020\004\000\002\020\003\000\002\021\010\000\002\026" +
    "\005\000\002\026\003\000\002\025\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\106\000\006\013\012\014\010\001\002\000\012\013" +
    "\ufff0\014\ufff0\015\ufff0\016\ufff0\001\002\000\004\016\ufffb" +
    "\001\002\000\004\013\012\001\002\000\004\016\ufffc\001" +
    "\002\000\004\007\061\001\002\000\004\002\060\001\002" +
    "\000\004\007\057\001\002\000\004\016\014\001\002\000" +
    "\004\010\017\001\002\000\004\016\040\001\002\000\004" +
    "\010\017\001\002\000\004\005\020\001\002\000\004\012" +
    "\022\001\002\000\006\006\uffea\007\uffea\001\002\000\004" +
    "\010\027\001\002\000\006\006\024\007\025\001\002\000" +
    "\004\012\022\001\002\000\006\010\uffec\016\uffec\001\002" +
    "\000\006\006\uffeb\007\uffeb\001\002\000\004\011\030\001" +
    "\002\000\004\017\031\001\002\000\006\006\uffe9\007\uffe9" +
    "\001\002\000\004\010\017\001\002\000\006\010\017\016" +
    "\uffed\001\002\000\004\016\uffef\001\002\000\004\010\017" +
    "\001\002\000\006\010\017\016\uffed\001\002\000\004\016" +
    "\uffee\001\002\000\004\010\043\001\002\000\006\002\uffe7" +
    "\010\043\001\002\000\004\002\000\001\002\000\004\012" +
    "\044\001\002\000\004\004\045\001\002\000\004\005\046" +
    "\001\002\000\004\010\051\001\002\000\006\006\uffe4\007" +
    "\uffe4\001\002\000\006\006\053\007\054\001\002\000\004" +
    "\012\052\001\002\000\006\006\uffe3\007\uffe3\001\002\000" +
    "\004\010\051\001\002\000\006\002\uffe6\010\uffe6\001\002" +
    "\000\006\006\uffe5\007\uffe5\001\002\000\004\002\uffe8\001" +
    "\002\000\012\013\uffff\014\uffff\015\uffff\016\uffff\001\002" +
    "\000\004\002\001\001\002\000\012\013\ufffe\014\ufffe\015" +
    "\ufffe\016\ufffe\001\002\000\004\013\012\001\002\000\006" +
    "\013\ufff8\014\ufff8\001\002\000\006\013\012\014\010\001" +
    "\002\000\004\016\ufffa\001\002\000\004\014\010\001\002" +
    "\000\004\013\012\001\002\000\006\013\ufff9\014\ufff9\001" +
    "\002\000\004\014\010\001\002\000\006\014\010\016\ufff7" +
    "\001\002\000\004\014\010\001\002\000\004\014\010\001" +
    "\002\000\004\014\010\001\002\000\004\014\010\001\002" +
    "\000\004\014\010\001\002\000\006\014\010\016\ufff6\001" +
    "\002\000\004\016\ufff5\001\002\000\012\013\012\014\010" +
    "\015\106\016\ufff4\001\002\000\012\013\ufff1\014\ufff1\015" +
    "\ufff1\016\ufff1\001\002\000\010\013\ufff0\015\ufff0\016\ufff0" +
    "\001\002\000\012\013\ufff2\014\ufff2\015\ufff2\016\ufff2\001" +
    "\002\000\004\007\107\001\002\000\012\013\ufffd\014\ufffd" +
    "\015\ufffd\016\ufffd\001\002\000\010\013\012\015\106\016" +
    "\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\106\000\016\002\010\003\005\004\003\006\012\007" +
    "\006\012\004\001\001\000\004\013\101\001\001\000\002" +
    "\001\001\000\004\003\061\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\014\014\016\015\001\001\000\002\001" +
    "\001\000\004\016\031\001\001\000\002\001\001\000\006" +
    "\023\022\024\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\024\025\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\016\032\001\001\000\006" +
    "\015\033\016\034\001\001\000\002\001\001\000\004\016" +
    "\035\001\001\000\006\015\036\016\034\001\001\000\002" +
    "\001\001\000\006\020\041\021\040\001\001\000\006\020" +
    "\055\021\040\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\025\046\026" +
    "\047\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\025\054\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\062\001\001\000\004\010\063\001\001\000\010\003\066" +
    "\004\065\011\064\001\001\000\002\001\001\000\004\004" +
    "\070\001\001\000\004\003\067\001\001\000\002\001\001" +
    "\000\004\004\071\001\001\000\004\004\072\001\001\000" +
    "\004\004\073\001\001\000\004\004\074\001\001\000\004" +
    "\004\075\001\001\000\004\004\076\001\001\000\004\004" +
    "\077\001\001\000\004\004\100\001\001\000\002\001\001" +
    "\000\010\003\104\004\103\005\102\001\001\000\002\001" +
    "\001\000\004\013\107\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\104\005\102\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
    
    public void printStatck(){
        System.out.println("---Stack---");
        for(int position=0; position<10; position++){
            Object obj = (((Symbol)stack.elementAt(tos + -position)).value);
            System.out.println("Element: " + obj + " At position: " + -position );
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= header SEP dresses SEP shopping 
            { parser.Tree.reduce(5,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // TOK1 ::= TOKEN1 SC 
            { parser.Tree.reduce(2,"TOK1",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // TOK2 ::= TOKEN2 SC 
            { parser.Tree.reduce(2,"TOK2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // TOK3 ::= TOKEN3 SC 
            { parser.Tree.reduce(2,"TOK3",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK3",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // header ::= head1 
            { parser.Tree.reduce(1,"header",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // header ::= head2 
            { parser.Tree.reduce(1,"header",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // head1 ::= TOK1 TOK1 TOK1 head1_tok1 head1_tok2 
            { parser.Tree.reduce(5,"head1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // head1_tok1 ::= head1_tok1 TOK1 TOK1 
            { parser.Tree.reduce(3,"head1_tok1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok1",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // head1_tok1 ::= 
            { parser.Tree.reduce(0,"head1_tok1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok1",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // head1_tok2 ::= TOK2 TOK2 TOK2 
            { parser.Tree.reduce(3,"head1_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok2",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // head1_tok2 ::= TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 
            { parser.Tree.reduce(9,"head1_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok2",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // head1_tok2 ::= TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 
            { parser.Tree.reduce(10,"head1_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok2",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // head2 ::= TOK2 head2_tok 
            { parser.Tree.reduce(2,"head2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // head2 ::= TOK2 head2_tok TOK2 head2_tok 
            { parser.Tree.reduce(4,"head2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // head2_tok ::= head2_tok TOK1 
            { parser.Tree.reduce(2,"head2_tok",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2_tok",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // head2_tok ::= head2_tok TOK3 
            { parser.Tree.reduce(2,"head2_tok",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2_tok",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // head2_tok ::= 
            { parser.Tree.reduce(0,"head2_tok",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2_tok",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // dresses ::= cloth cloth cloth clothes 
            { parser.Tree.reduce(4,"dresses",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("dresses",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // clothes ::= cloth cloth clothes 
            { parser.Tree.reduce(3,"clothes",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("clothes",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // clothes ::= 
            { parser.Tree.reduce(0,"clothes",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("clothes",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // cloth ::= QSTRING DASH prod_list SC 
            { parser.Tree.reduce(4,"cloth",0);
              Object RESULT =null;
		int dress_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int dress_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String dress_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int prod_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int prod_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		HashMap prod_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    parser.table.put(dress_name, prod_list);
    // System.out.println(prod_list);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cloth",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // prod_list ::= prod_list CM prod 
            { parser.Tree.reduce(3,"prod_list",0);
              HashMap RESULT =null;
		int prod_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int prod_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		HashMap prod_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int prodleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int prodright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap prod = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
  prod_list.putAll(prod);
  RESULT = prod_list;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prod_list",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // prod_list ::= prod 
            { parser.Tree.reduce(1,"prod_list",0);
              HashMap RESULT =null;
		int prodleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int prodright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap prod = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
  RESULT = prod;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prod_list",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // prod ::= INUM QSTRING FNUM EURO_WD 
            { parser.Tree.reduce(4,"prod",0);
              HashMap RESULT =null;
		int prod_idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int prod_idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Integer prod_id = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int prod_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int prod_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String prod_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int prod_costleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int prod_costright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Double prod_cost = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    HashMap prod = new HashMap<String, Double>();
    prod.put(prod_name, prod_cost);
    RESULT = prod;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prod",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // shopping ::= purchase shopping 
            { parser.Tree.reduce(2,"shopping",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("shopping",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // shopping ::= purchase 
            { parser.Tree.reduce(1,"shopping",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("shopping",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // purchase ::= QSTRING INUM PAM DASH purch_prod_list SC 
            { parser.Tree.reduce(6,"purchase",0);
              Object RESULT =null;
		int dress_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int dress_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String dress_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int percentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int percentright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer percent = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int purchasesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int purchasesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		HashMap purchases = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    System.out.println(dress_name);
    HashMap prods = parser.table.get(dress_name);
    // System.out.println(prods);
    Double totalPrice = 0.0;
    Integer totalProdsCount = 0;
    for (Object prodName : purchases.keySet()) {
        Integer quantity = (Integer) purchases.get(prodName);
        totalProdsCount += quantity;
        Double prodCost = (Double) prods.get(prodName);
        // System.out.println(prodCost);
        // System.out.println(quantity);
        // System.out.println(percent);
        // System.out.println(quantity * prodCost * percent/100);
        Double discountPrice = quantity * prodCost * percent/100;
        System.out.println(prodName + " " + discountPrice + " euro");
        totalPrice += discountPrice;
    }
    System.out.println("TOTAL: " + totalPrice + " euro N_PROD: " + totalProdsCount);


              CUP$parser$result = parser.getSymbolFactory().newSymbol("purchase",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // purch_prod_list ::= purch_prod_list CM purch_prod 
            { parser.Tree.reduce(3,"purch_prod_list",0);
              HashMap RESULT =null;
		int purchase_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int purchase_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		HashMap purchase_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int purcahseleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int purcahseright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap purcahse = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    purchase_list.putAll(purcahse);
    RESULT = purchase_list;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("purch_prod_list",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // purch_prod_list ::= purch_prod 
            { parser.Tree.reduce(1,"purch_prod_list",0);
              HashMap RESULT =null;
		int purchaseleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int purchaseright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap purchase = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = purchase;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("purch_prod_list",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // purch_prod ::= QSTRING INUM 
            { parser.Tree.reduce(2,"purch_prod",0);
              HashMap RESULT =null;
		int prod_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int prod_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String prod_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int quantityleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int quantityright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer quantity = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
    HashMap purchase = new HashMap<String, Integer>();
    purchase.put(prod_name, quantity);
    RESULT = purchase;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("purch_prod",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
