import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};

// expression
// E ::= E PLUS E
// | E MINUS E
// | E STAR E
// | E DIV E
// | MINUS E    %prec uminus
// | OP E CP
// | INTEGER
// ;

/////////////////////////////
//// Symbols Delaration
////////////////////////////

// terminal QUM;
// terminal EXM;
// terminal ATM;
// terminal HAM;
// terminal DOM;
terminal PAM;
// terminal CIM;
// terminal AND;
// terminal STAR;
terminal DASH;
// terminal EQ;
// terminal PLUS;
// terminal OP;
// terminal CP;
// terminal OB;
// terminal CB;
// terminal OC;
// terminal CC;
// terminal GT;
// terminal LT;
// terminal SL;
// terminal BSL;
// terminal DOT;
// terminal CO;
terminal CM;
terminal SC;
// terminal QU;
// terminal DQU;
// terminal GRAVE;
// terminal TIL;
// terminal OR;
// terminal US;

// terminal String VAR;
terminal String QSTRING;
terminal Double FNUM;
terminal Integer INUM;
// terminal Integer SINUM;

// terminal TOK1, TOK2, SEP;
terminal TOK1, TOK2, TOK3, SEP;
terminal String EURO_WD;


non terminal prog ;
non terminal header, head1, head1_tok1, head1_tok2, head2, head2_tok;
non terminal dresses, clothes, cloth, prod, prod_id, prod_name;
non terminal shopping, purchasing, purchase, purch_prod_list, purch_prod, quantity, percent;
// non terminal ;
non terminal String dress_name;
non terminal HashMap prod_list;
// non terminal Integer ;
non terminal Double prod_cost;

// precedence left PLUS, DASH;
// precedence left STAR, SL;
// precedence left CIM;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= header SEP dresses SEP shopping
;

// header

header ::= head1 | head2
;

head1 ::= TOK1 SC TOK1 SC TOK1 SC head1_tok1 head1_tok2
;

head1_tok1 ::= head1_tok1 TOK1 SC TOK1 SC | 
;

head1_tok2 ::= TOK2 SC TOK2 SC TOK2 SC |
               TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC |
               TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC TOK2 SC  
;

head2 ::= TOK2 SC head2_tok |
          TOK2 SC head2_tok TOK2 SC head2_tok
;

head2_tok ::= head2_tok TOK1 SC | head2_tok TOK3 SC |
;

// dresses
dresses ::= cloth cloth cloth clothes
;

clothes ::= cloth cloth clothes |
;

cloth ::= dress_name:dress_name DASH prod_list:prod_list SC
{:
    parser.table.put(dress_name, prod_list);
:}
;

dress_name ::= QSTRING:res
{: RESULT = res; :}
;

prod_list ::= prod_list CM prod | prod
;

prod ::= prod_id prod_name:prod_name prod_cost:prod_cost EURO_WD
{:
    HashMap prod = new HashMap<String, Double>();
    prod.put(prod_name, prod_cost);
    RESULT = prod;
:}
;

prod_id ::= INUM
;

prod_name ::= QSTRING:res
{: RESULT = res; :}
;

prod_cost ::= INUM | FNUM
;

// shopping
shopping ::= purchasing
;

purchasing ::= purchasing purchase | purchase
;

purchase ::= dress_name:dress_name percent PAM DASH purch_prod_list SC
{:
    System.out.println(dress_name);
:}
;

percent ::= INUM
;

purch_prod_list ::= purch_prod_list CM purch_prod
{:
    
:}
| purch_prod
;

purch_prod ::= prod_name:prod_name quantity
{: 
    System.out.println(prod_name);
:}
;

quantity ::= INUM:res
{: RESULT = res; :}
;