import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>>table;

    public void report_error(String message, Object info) {
        System.err.print("ERROR: Syntax error");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.print(" (line "+line+", column "+column+"): ");
            } else System.err.print(": ");
        else System.err.print(": ");
    }

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

:};

/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal SEP, TOK1, TOK2, TOK3,  DASH, SC, CM, EURO_WD, PAM ;
terminal String QSTRING;
terminal Double REAL_NUM;
terminal Integer INUM;

non terminal prog, HEADER, DRESSES, SHOPPING ;
non terminal HEADER1, HEADER2, TOK1S, TOK2S,TOK13S, TOK13;
non terminal DRESS;
non terminal HashMap <String, Double> PROD_LIST;
non terminal PURCHASE ;
non terminal Object [] PURCH_PRODS;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP DRESSES SEP SHOPPING
;


HEADER ::= HEADER1 | HEADER2
;

HEADER1 ::= TOK1S TOK2S
;

TOK1S ::= TOK1S TOK1 TOK1 | TOK1 TOK1 TOK1
;

TOK2S ::= TOK2 TOK2 TOK2 
        |   TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 
        |   TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2
;

HEADER2 ::= TOK2 TOK13S | TOK2 TOK13S TOK2 TOK13S
;

TOK13S ::= TOK13S TOK13 | 
;

TOK13 ::= TOK1 | TOK3
;

//DRESSES

DRESSES ::= DRESSES DRESS DRESS | DRESS DRESS DRESS 
;

DRESS ::= QSTRING:var DASH PROD_LIST:tab SC {:parser.table.put(var, tab);:}
; 

PROD_LIST ::= PROD_LIST:tab CM INUM:quan QSTRING:name REAL_NUM:price EURO_WD{:
tab.put(name, price);
RESULT = tab;:} 
| INUM QSTRING:name REAL_NUM:price EURO_WD {:
HashMap <String, Double> tab = new HashMap <String, Double>();
tab.put(name, price);
RESULT = tab;
:}
;

//SHOPPING

SHOPPING ::= SHOPPING PURCHASE | PURCHASE
;

PURCHASE ::= QSTRING:dress {:System.out.println(dress);:} INUM PAM DASH PURCH_PRODS:x SC {:
System.out.println("TOTAL: " + x[0] + " euro N_PROD: " + x[1]);
:}
;

PURCH_PRODS ::= PURCH_PRODS:ex CM QSTRING:name INUM:quan {:
String prodName = (String)parser.stack(-8);
Integer percent = (Integer) parser.stack(-6);
HashMap <String, Double> tab = parser.table.get(prodName);
Double price = tab.get(name);
Double res = percent * quan * price / 100;
System.out.println(name + " " + res+ " euro");
ex[0] = (Double)ex[0] + res;
ex[1] = (Integer)ex[1] + quan;
RESULT = ex;
:}
| QSTRING:name INUM:quan {:
String prodName = (String)parser.stack(-6);
Integer percent = (Integer) parser.stack(-4);
HashMap <String, Double> tab = parser.table.get(prodName);
Double price = tab.get(name);
Double res = percent * quan * price / 100;
System.out.println(name + " " + res+ " euro");
Object [] arr = new Object[2];
arr[0] = res;
arr[1] = quan;
RESULT = arr;
:}
;


