
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\050\000\002\002\004\000\002\003\004\000\002\004" +
    "\004\000\002\002\007\000\002\005\003\000\002\005\003" +
    "\000\002\010\010\000\002\011\004\000\002\011\002\000" +
    "\002\012\015\000\002\012\026\000\002\013\005\000\002" +
    "\013\002\000\002\006\006\000\002\015\005\000\002\015" +
    "\002\000\002\014\006\000\002\022\005\000\002\022\003" +
    "\000\002\021\004\000\002\026\005\000\002\026\005\000" +
    "\002\026\005\000\002\026\005\000\002\026\004\000\002" +
    "\026\005\000\002\026\003\000\002\007\004\000\002\007" +
    "\002\000\002\016\003\000\002\016\002\000\002\017\010" +
    "\000\002\020\003\000\002\020\002\000\002\024\005\000" +
    "\002\024\003\000\002\023\005\000\002\025\003\000\002" +
    "\025\003\000\002\025\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\006\020\012\021\010\001\002\000\004\021" +
    "\010\001\002\000\006\020\ufff9\021\ufff9\001\002\000\004" +
    "\022\ufffc\001\002\000\004\022\ufffd\001\002\000\004\014" +
    "\102\001\002\000\004\002\101\001\002\000\004\014\100" +
    "\001\002\000\004\022\014\001\002\000\004\015\017\001" +
    "\002\000\004\022\053\001\002\000\004\015\017\001\002" +
    "\000\004\012\020\001\002\000\004\015\023\001\002\000" +
    "\006\013\044\014\uffef\001\002\000\004\014\043\001\002" +
    "\000\010\005\025\007\024\016\027\001\002\000\010\005" +
    "\025\007\024\016\027\001\002\000\010\005\025\007\024" +
    "\016\027\001\002\000\016\004\030\005\032\006\033\011" +
    "\031\013\uffee\014\uffee\001\002\000\020\004\uffe7\005\uffe7" +
    "\006\uffe7\010\uffe7\011\uffe7\013\uffe7\014\uffe7\001\002\000" +
    "\010\005\025\007\024\016\027\001\002\000\010\005\025" +
    "\007\024\016\027\001\002\000\010\005\025\007\024\016" +
    "\027\001\002\000\010\005\025\007\024\016\027\001\002" +
    "\000\020\004\030\005\uffed\006\uffed\010\uffed\011\031\013" +
    "\uffed\014\uffed\001\002\000\020\004\030\005\uffec\006\uffec" +
    "\010\uffec\011\031\013\uffec\014\uffec\001\002\000\020\004" +
    "\uffea\005\uffea\006\uffea\010\uffea\011\uffea\013\uffea\014\uffea" +
    "\001\002\000\020\004\uffeb\005\uffeb\006\uffeb\010\uffeb\011" +
    "\uffeb\013\uffeb\014\uffeb\001\002\000\020\004\030\005\uffe9" +
    "\006\uffe9\010\uffe9\011\031\013\uffe9\014\uffe9\001\002\000" +
    "\014\004\030\005\032\006\033\010\042\011\031\001\002" +
    "\000\020\004\uffe8\005\uffe8\006\uffe8\010\uffe8\011\uffe8\013" +
    "\uffe8\014\uffe8\001\002\000\006\015\ufff1\022\ufff1\001\002" +
    "\000\004\015\023\001\002\000\004\014\ufff0\001\002\000" +
    "\004\015\017\001\002\000\006\015\ufff2\022\ufff2\001\002" +
    "\000\006\015\017\022\ufff4\001\002\000\004\015\017\001" +
    "\002\000\006\015\ufff3\022\ufff3\001\002\000\006\002\uffe5" +
    "\015\056\001\002\000\006\002\uffe3\015\056\001\002\000" +
    "\004\002\ufffe\001\002\000\004\016\057\001\002\000\006" +
    "\012\uffe0\023\060\001\002\000\004\012\uffe1\001\002\000" +
    "\004\012\062\001\002\000\004\016\065\001\002\000\006" +
    "\013\073\014\074\001\002\000\006\013\uffde\014\uffde\001" +
    "\002\000\004\015\066\001\002\000\010\024\070\025\067" +
    "\026\071\001\002\000\006\013\uffda\014\uffda\001\002\000" +
    "\006\013\uffdb\014\uffdb\001\002\000\006\013\uffdc\014\uffdc" +
    "\001\002\000\006\013\uffdd\014\uffdd\001\002\000\004\016" +
    "\065\001\002\000\006\002\uffe2\015\uffe2\001\002\000\006" +
    "\013\uffdf\014\uffdf\001\002\000\004\002\uffe4\001\002\000" +
    "\004\002\uffe6\001\002\000\010\020\000\021\000\022\000" +
    "\001\002\000\004\002\001\001\002\000\010\020\uffff\021" +
    "\uffff\022\uffff\001\002\000\006\020\012\021\010\001\002" +
    "\000\010\020\ufffa\021\ufffa\022\ufffa\001\002\000\006\020" +
    "\ufff9\021\ufff9\001\002\000\006\020\012\021\010\001\002" +
    "\000\006\021\ufff9\022\ufff9\001\002\000\006\021\010\022" +
    "\ufffb\001\002\000\004\021\010\001\002\000\004\021\010" +
    "\001\002\000\004\021\010\001\002\000\004\021\010\001" +
    "\002\000\006\020\ufff5\021\ufff5\001\002\000\006\020\012" +
    "\021\010\001\002\000\004\021\010\001\002\000\004\020" +
    "\012\001\002\000\004\020\012\001\002\000\004\020\012" +
    "\001\002\000\006\020\012\022\ufff8\001\002\000\004\020" +
    "\012\001\002\000\004\020\012\001\002\000\004\020\012" +
    "\001\002\000\004\020\012\001\002\000\004\020\012\001" +
    "\002\000\004\020\012\001\002\000\004\020\012\001\002" +
    "\000\004\020\012\001\002\000\004\022\ufff7\001\002\000" +
    "\006\020\ufff6\021\ufff6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\016\002\010\003\004\004\003\005\012\010" +
    "\006\012\005\001\001\000\004\004\110\001\001\000\004" +
    "\011\102\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\014\014\015\001\001\000\002\001" +
    "\001\000\004\014\045\001\001\000\002\001\001\000\006" +
    "\021\020\022\021\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\026\025\001\001\000\004\026\040\001\001" +
    "\000\004\026\037\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\026\036\001\001\000\004\026\035\001\001" +
    "\000\004\026\034\001\001\000\004\026\033\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\021\020\022\044\001\001" +
    "\000\002\001\001\000\004\014\046\001\001\000\004\015" +
    "\047\001\001\000\004\014\050\001\001\000\004\014\051" +
    "\001\001\000\002\001\001\000\006\007\054\017\053\001" +
    "\001\000\006\016\076\017\075\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\060\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\023\063\024\062\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\025\071\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\023\074\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\003\104\004\103\001\001\000\002" +
    "\001\001\000\004\011\105\001\001\000\006\003\106\004" +
    "\103\001\001\000\004\011\107\001\001\000\004\004\103" +
    "\001\001\000\004\004\111\001\001\000\004\004\112\001" +
    "\001\000\004\004\113\001\001\000\004\004\114\001\001" +
    "\000\004\013\115\001\001\000\006\003\117\004\116\001" +
    "\001\000\004\004\134\001\001\000\004\003\120\001\001" +
    "\000\004\003\121\001\001\000\004\003\122\001\001\000" +
    "\004\003\123\001\001\000\004\003\124\001\001\000\004" +
    "\003\125\001\001\000\004\003\126\001\001\000\004\003" +
    "\127\001\001\000\004\003\130\001\001\000\004\003\131" +
    "\001\001\000\004\003\132\001\001\000\004\003\133\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
    public void printStatck(){
        System.out.println("---Stack---");
        for(int position=0; position<10; position++){
            Object obj = (((Symbol)stack.elementAt(tos + -position)).value);
            System.out.println("Element: " + obj + " At position: " + -position );
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // TOK1 ::= TOKEN1 SC 
            { parser.Tree.reduce(2,"TOK1",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // TOK2 ::= TOKEN2 SC 
            { parser.Tree.reduce(2,"TOK2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // prog ::= header SEP athletes SEP evaluation 
            { parser.Tree.reduce(5,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // header ::= head1 
            { parser.Tree.reduce(1,"header",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // header ::= head2 
            { parser.Tree.reduce(1,"header",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // head1 ::= TOK1 head1_tok2 TOK1 head1_tok2 TOK1 head1_tok2 
            { parser.Tree.reduce(6,"head1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // head1_tok2 ::= head1_tok2 TOK2 
            { parser.Tree.reduce(2,"head1_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok2",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // head1_tok2 ::= 
            { parser.Tree.reduce(0,"head1_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1_tok2",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // head2 ::= TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 head2_tok2 TOK1 TOK1 TOK1 TOK1 
            { parser.Tree.reduce(11,"head2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // head2 ::= TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 head2_tok2 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 TOK1 
            { parser.Tree.reduce(20,"head2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-19)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // head2_tok2 ::= head2_tok2 TOK2 TOK2 
            { parser.Tree.reduce(3,"head2_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2_tok2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // head2_tok2 ::= 
            { parser.Tree.reduce(0,"head2_tok2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head2_tok2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // athletes ::= athlete athlete athlete athlete_list 
            { parser.Tree.reduce(4,"athletes",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("athletes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // athlete_list ::= athlete_list athlete athlete 
            { parser.Tree.reduce(3,"athlete_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("athlete_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // athlete_list ::= 
            { parser.Tree.reduce(0,"athlete_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("athlete_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // athlete ::= QSTRING CO attr_list SC 
            { parser.Tree.reduce(4,"athlete",0);
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int attr_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attr_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		HashMap attr_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    table.put(name, attr_list);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("athlete",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // attr_list ::= attr CM attr_list 
            { parser.Tree.reduce(3,"attr_list",0);
              HashMap RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		HashMap attr = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attr_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attr_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap attr_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
   HashMap<String, Double> res = new HashMap<String, Double>();
   res.putAll(attr_list);
   res.putAll(attr);
   RESULT = res;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("attr_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // attr_list ::= attr 
            { parser.Tree.reduce(1,"attr_list",0);
              HashMap RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap attr = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = attr;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("attr_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // attr ::= QSTRING exp 
            { parser.Tree.reduce(2,"attr",0);
              HashMap RESULT =null;
		int attr_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attr_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
   HashMap<String, Double> res = new HashMap<String, Double>();
   res.put(attr_name,e);
   RESULT = res;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("attr",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // exp ::= exp PLUS exp 
            { parser.Tree.reduce(3,"exp",0);
              Double RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double el = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int erleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int erright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double er = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = el + er;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // exp ::= exp DASH exp 
            { parser.Tree.reduce(3,"exp",0);
              Double RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double el = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int erleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int erright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double er = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = el - er;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // exp ::= exp STAR exp 
            { parser.Tree.reduce(3,"exp",0);
              Double RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double el = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int erleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int erright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double er = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = el * er;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // exp ::= exp SL exp 
            { parser.Tree.reduce(3,"exp",0);
              Double RESULT =null;
		int elleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int elright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double el = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int erleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int erright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double er = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = el / er;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // exp ::= DASH exp 
            { parser.Tree.reduce(2,"exp",0);
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = -e;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // exp ::= OP exp CP 
            { parser.Tree.reduce(3,"exp",0);
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
RESULT = e;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // exp ::= FNUM 
            { parser.Tree.reduce(1,"exp",0);
              Double RESULT =null;
		int fnumleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fnumright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double fnum = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = fnum;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // evaluation ::= eval eval_list 
            { parser.Tree.reduce(2,"evaluation",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("evaluation",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // evaluation ::= 
            { parser.Tree.reduce(0,"evaluation",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("evaluation",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // eval_list ::= eval 
            { parser.Tree.reduce(1,"eval_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("eval_list",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // eval_list ::= 
            { parser.Tree.reduce(0,"eval_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("eval_list",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // eval ::= QSTRING FNUM points CO val_list SC 
            { parser.Tree.reduce(6,"eval",0);
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int multleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int multright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Double mult = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int val_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int val_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		HashMap val_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    System.out.println(name);
    Double total = 0.0;
    for (Object key : val_list.keySet()) {
        Double value = (Double)val_list.get(key);
        total += value;
        System.out.println(key + " " + value);
    }
    System.out.println("TOTAL: " + total);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("eval",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // points ::= POINTS_WD 
            { parser.Tree.reduce(1,"points",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("points",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // points ::= 
            { parser.Tree.reduce(0,"points",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("points",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // val_list ::= val_list CM val 
            { parser.Tree.reduce(3,"val_list",0);
              HashMap RESULT =null;
		int val_listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int val_listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		HashMap val_list = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap val = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
   HashMap<String, Double> res = new HashMap<String, Double>();
   res.putAll(val_list);
   res.putAll(val);
   RESULT = res;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("val_list",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // val_list ::= val 
            { parser.Tree.reduce(1,"val_list",0);
              HashMap RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap val = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
RESULT = val;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("val_list",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // val ::= FNUM QSTRING score 
            { parser.Tree.reduce(3,"val",0);
              HashMap RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double val = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attr_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attr_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int scoreleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int scoreright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double score = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
// parser.printStatck();
String athlete = (String)parser.stack(-8);
Double mult = (Double)parser.stack(-7);
if (athlete == null){
    athlete = (String)parser.stack(-6);
    mult = (Double)parser.stack(-5);
}

HashMap <String, Double> attrs = table.get(athlete); 
Double attr_val = (Double)attrs.get(attr_name);

Double sub = mult * val * attr_val * score;
HashMap <String, Double> res = new HashMap <String, Double>();
res.put(attr_name, sub);
RESULT = res;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("val",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // score ::= LOW_WD 
            { parser.Tree.reduce(1,"score",0);
              Double RESULT =null;
		
RESULT = 0.0;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("score",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // score ::= MEDIUM_WD 
            { parser.Tree.reduce(1,"score",0);
              Double RESULT =null;
		
RESULT = 1.0;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("score",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // score ::= HIGH_WD 
            { parser.Tree.reduce(1,"score",0);
              Double RESULT =null;
		
RESULT = 2.0;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("score",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
