
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MEDIUM_WD = 18;
  public static final int CP = 6;
  public static final int PLUS = 4;
  public static final int CO = 8;
  public static final int CM = 9;
  public static final int OP = 5;
  public static final int STAR = 2;
  public static final int INUM = 13;
  public static final int POINTS_WD = 17;
  public static final int LOW_WD = 20;
  public static final int EOF = 0;
  public static final int SL = 7;
  public static final int SEP = 16;
  public static final int error = 1;
  public static final int TOKEN2 = 15;
  public static final int TOKEN1 = 14;
  public static final int DASH = 3;
  public static final int QSTRING = 11;
  public static final int SC = 10;
  public static final int FNUM = 12;
  public static final int HIGH_WD = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STAR",
  "DASH",
  "PLUS",
  "OP",
  "CP",
  "SL",
  "CO",
  "CM",
  "SC",
  "QSTRING",
  "FNUM",
  "INUM",
  "TOKEN1",
  "TOKEN2",
  "SEP",
  "POINTS_WD",
  "MEDIUM_WD",
  "HIGH_WD",
  "LOW_WD"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[18]=new String("MEDIUM_WD");
		TT[6]=new String("CP");
		TT[4]=new String("PLUS");
		TT[8]=new String("CO");
		TT[9]=new String("CM");
		TT[5]=new String("OP");
		TT[2]=new String("STAR");
		TT[13]=new String("INUM");
		TT[17]=new String("POINTS_WD");
		TT[20]=new String("LOW_WD");
		TT[0]=new String("EOF");
		TT[7]=new String("SL");
		TT[16]=new String("SEP");
		TT[1]=new String("error");
		TT[15]=new String("TOKEN2");
		TT[14]=new String("TOKEN1");
		TT[3]=new String("DASH");
		TT[11]=new String("QSTRING");
		TT[10]=new String("SC");
		TT[12]=new String("FNUM");
		TT[19]=new String("HIGH_WD");
	}
public String getTT(int i){return TT[i];}
}

