import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};

// expression
// E ::= E PLUS E
// | E MINUS E
// | E STAR E
// | E DIV E
// | MINUS E    %prec uminus
// | OP E CP
// | INTEGER
// ;

/////////////////////////////
//// Symbols Delaration
////////////////////////////

// terminal QUM;
// terminal EXM;
// terminal ATM;
// terminal HAM;
// terminal DOM;
// terminal PAM;
// terminal CIM;
// terminal AND;
// terminal STAR;
// terminal DASH;
// terminal EQ;
// terminal PLUS;
// terminal OP;
// terminal CP;
// terminal OB;
// terminal CB;
// terminal OC;
// terminal CC;
// terminal GT;
// terminal LT;
// terminal SL;
// terminal BSL;
// terminal DOT;
// terminal CO;
// terminal CM;
// terminal SC;
// terminal QU;
// terminal DQU;
// terminal GRAVE;
// terminal TIL;
// terminal OR;
// terminal US;

// terminal String VAR;
// terminal String QSTRING;
// terminal Double FNUM;
// terminal Integer INUM;
// terminal Integer SINUM;

terminal TOK1, TOK2, SEP;
// terminal TOK1, TOK2, TOK3, SEP;


non terminal prog ;
non terminal header ;
// non terminal ;
// non terminal ;
// non terminal ;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left PLUS, DASH;
// precedence left STAR, SL;
// precedence left CIM;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= header SEP
;

// header

