import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

    public void printStatck(){
        System.out.println("---Stack---");
        for(int position=0; position<10; position++){
            Object obj = (((Symbol)stack.elementAt(tos + -position)).value);
            System.out.println("Element: " + obj + " At position: " + -position );
        }
    }
:};

// expression
// exp ::= exp PLUS exp
// | exp DASH exp
// | exp STAR exp
// | exp SL exp
// | DASH exp    %prec uminus
// | OP exp CP
// | INUM
// ;

/////////////////////////////
//// Symbols Delaration
////////////////////////////

// terminal QUM;
// terminal EXM;
// terminal ATM;
// terminal HAM;
// terminal DOM;
// terminal PAM;
// terminal CIM;
// terminal AND;
// terminal STAR;
// terminal DASH;
// terminal EQ;
// terminal PLUS;
// terminal OP;
// terminal CP;
// terminal OB;
// terminal CB;
// terminal OC;
// terminal CC;
// terminal GT;
// terminal LT;
// terminal SL;
// terminal BSL;
// terminal DOT;
// terminal CO;
// terminal CM;
terminal SC;
// terminal QU;
// terminal DQU;
// terminal GRAVE;
// terminal TIL;
// terminal OR;
// terminal US;

// terminal String VAR;
// terminal String QSTRING;
// terminal Double FNUM;
// terminal Integer INUM;
// terminal Integer SINUM;

// terminal TOKEN1, TOKEN2, SEP;
// terminal TOKEN1, TOKEN2, TOKEN3, SEP;
// terminal String ;


non terminal prog;
non terminal header, TOK1, TOK2;
// non terminal ;
// non terminal ;
// non terminal ;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left PLUS, DASH;
// precedence left STAR, SL;
// precedence left CIM;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= header SEP
;

TOK1 ::= TOKEN1 SC
;

TOK2 ::= TOKEN2 SC
;

// header

header ::= 
;