
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\054\000\002\002\004\000\002\002\007\000\002\004" +
    "\004\000\002\005\004\000\002\003\004\000\002\003\004" +
    "\000\002\003\005\000\002\003\005\000\002\003\005\000" +
    "\002\003\005\000\002\003\006\000\002\003\006\000\002" +
    "\003\006\000\002\003\007\000\002\006\004\000\002\006" +
    "\003\000\002\007\005\000\002\007\004\000\002\010\007" +
    "\000\002\017\005\000\002\017\003\000\002\016\004\000" +
    "\002\011\004\000\002\011\002\000\002\012\004\000\002" +
    "\012\003\000\002\013\007\000\002\025\003\000\002\025" +
    "\005\000\002\025\006\000\002\024\005\000\002\024\005" +
    "\000\002\024\004\000\002\020\005\000\002\015\003\000" +
    "\002\015\003\000\002\014\004\000\002\014\004\000\002" +
    "\014\003\000\002\014\003\000\002\023\004\000\002\022" +
    "\004\000\002\021\005\000\002\021\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\006\015\011\016\007\001\002\000\010\015" +
    "\ufff2\016\ufff2\017\ufff2\001\002\000\006\015\011\016\007" +
    "\001\002\000\006\015\011\016\007\001\002\000\004\012" +
    "\106\001\002\000\004\002\105\001\002\000\004\012\104" +
    "\001\002\000\004\017\013\001\002\000\004\020\015\001" +
    "\002\000\004\020\015\001\002\000\004\013\074\001\002" +
    "\000\006\017\017\020\015\001\002\000\006\002\uffea\004" +
    "\025\001\002\000\004\020\015\001\002\000\006\017\ufff1" +
    "\020\ufff1\001\002\000\004\004\025\001\002\000\004\002" +
    "\000\001\002\000\004\004\uffe8\001\002\000\006\013\032" +
    "\027\026\001\002\000\010\006\064\013\032\027\065\001" +
    "\002\000\006\030\061\031\060\001\002\000\014\007\uffe6" +
    "\023\uffe6\024\uffe6\025\055\026\054\001\002\000\006\023" +
    "\041\024\037\001\002\000\004\010\033\001\002\000\004" +
    "\013\034\001\002\000\006\030\uffe0\031\uffe0\001\002\000" +
    "\006\005\uffda\024\037\001\002\000\004\005\051\001\002" +
    "\000\004\032\043\001\002\000\006\005\uffdb\023\041\001" +
    "\002\000\004\032\043\001\002\000\010\005\uffd9\024\uffd9" +
    "\032\045\001\002\000\004\013\044\001\002\000\012\005" +
    "\uffd6\023\uffd6\024\uffd6\032\uffd6\001\002\000\004\013\046" +
    "\001\002\000\012\005\uffd7\023\uffd7\024\uffd7\032\uffd7\001" +
    "\002\000\004\005\uffdc\001\002\000\010\005\uffd8\023\uffd8" +
    "\032\045\001\002\000\004\004\052\001\002\000\006\002" +
    "\uffe7\004\uffe7\001\002\000\004\005\uffdd\001\002\000\006" +
    "\013\uffde\027\uffde\001\002\000\006\013\uffdf\027\uffdf\001" +
    "\002\000\006\013\032\027\026\001\002\000\010\007\uffe5" +
    "\023\uffe5\024\uffe5\001\002\000\004\014\063\001\002\000" +
    "\004\014\062\001\002\000\014\007\uffe3\023\uffe3\024\uffe3" +
    "\025\uffe3\026\uffe3\001\002\000\014\007\uffe2\023\uffe2\024" +
    "\uffe2\025\uffe2\026\uffe2\001\002\000\006\013\032\027\026" +
    "\001\002\000\006\013\032\027\065\001\002\000\014\007" +
    "\uffe1\023\uffe1\024\uffe1\025\uffe1\026\uffe1\001\002\000\004" +
    "\007\070\001\002\000\010\007\uffe4\023\uffe4\024\uffe4\001" +
    "\002\000\006\002\uffeb\004\uffe9\001\002\000\006\011\uffed" +
    "\022\uffed\001\002\000\006\011\076\022\077\001\002\000" +
    "\004\014\075\001\002\000\006\011\uffec\022\uffec\001\002" +
    "\000\004\013\074\001\002\000\004\013\100\001\002\000" +
    "\004\021\101\001\002\000\006\017\uffef\020\uffef\001\002" +
    "\000\006\011\uffee\022\uffee\001\002\000\006\017\ufff0\020" +
    "\ufff0\001\002\000\010\015\uffff\016\uffff\017\uffff\001\002" +
    "\000\004\002\001\001\002\000\010\015\ufffe\016\ufffe\017" +
    "\ufffe\001\002\000\010\015\ufff3\016\ufff3\017\ufff3\001\002" +
    "\000\010\015\011\016\007\017\ufffc\001\002\000\006\016" +
    "\007\017\ufffa\001\002\000\010\015\011\016\007\017\ufffb" +
    "\001\002\000\006\016\007\017\ufff7\001\002\000\006\016" +
    "\007\017\ufff4\001\002\000\006\016\007\017\ufff6\001\002" +
    "\000\004\016\007\001\002\000\010\015\011\016\007\017" +
    "\ufffd\001\002\000\006\016\007\017\ufff9\001\002\000\006" +
    "\016\007\017\ufff5\001\002\000\006\016\007\017\ufff8\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\014\002\007\003\011\004\004\005\003\006" +
    "\005\001\001\000\002\001\001\000\010\004\115\005\003" +
    "\006\116\001\001\000\006\004\107\005\106\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\007\015\010\013\001\001\000\004\010" +
    "\102\001\001\000\006\016\071\017\072\001\001\000\004" +
    "\010\017\001\001\000\010\011\022\012\021\013\023\001" +
    "\001\000\004\010\020\001\001\000\002\001\001\000\004" +
    "\013\070\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\020\026\024\027\025\030\001\001\000\006\020\026" +
    "\024\065\001\001\000\002\001\001\000\004\015\055\001" +
    "\001\000\010\014\035\022\037\023\034\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\022" +
    "\052\001\001\000\002\001\001\000\004\021\047\001\001" +
    "\000\004\023\046\001\001\000\004\021\041\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\020\026\024" +
    "\027\025\056\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\020\026\024\027\025\066\001\001\000\006\020\026" +
    "\024\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\101\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\004\110\005\003\006\111\001\001\000\006\005" +
    "\003\006\114\001\001\000\006\004\112\005\106\001\001" +
    "\000\006\005\003\006\113\001\001\000\004\005\106\001" +
    "\001\000\004\005\106\001\001\000\006\005\003\006\121" +
    "\001\001\000\006\004\117\005\106\001\001\000\006\005" +
    "\003\006\120\001\001\000\004\005\106\001\001\000\004" +
    "\005\106\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Integer>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Integer>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

    public void printStatck(){
        System.out.println("---Stack---");
        for(int position=0; position<10; position++){
            Object obj = (((Symbol)stack.elementAt(tos + -position)).value);
            System.out.println("Element: " + obj + " At position: " + -position );
        }
    }

    public void test(){
        HashMap hm1 = new HashMap<String, Integer>();
        hm1.put("x", 1);
        HashMap hm2 = new HashMap<String, Integer>();
        hm2.put("y", 2);
        
        hm1.putAll(hm2);
        System.out.println("hm1: " + hm1);
        
        for (Object key : hm1.keySet()) {
            Integer value = (Integer) hm1.get(key);
            System.out.println("Key: " + key + " Value: " + value);
        }

        ArrayList<Integer> arr = new ArrayList<>();
        arr.add(1);
        arr.add(1);
        Integer index0 = arr.get(0);
        Integer index1 = arr.get(1);
        System.out.println("arr: " + arr);
        System.out.println("arr.size(): " + arr.size());
        System.out.println("arr.get(0): " + arr.get(0));
        System.out.println("compare equal: " + index0.equals(index1));
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= header SEP objs SEP queries 
            { parser.Tree.reduce(5,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // TOK1 ::= TOKEN1 SC 
            { parser.Tree.reduce(2,"TOK1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // TOK2 ::= TOKEN2 SC 
            { parser.Tree.reduce(2,"TOK2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // header ::= TOK1 head1 
            { parser.Tree.reduce(2,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // header ::= head1 TOK1 
            { parser.Tree.reduce(2,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // header ::= head1 TOK1 head1 
            { parser.Tree.reduce(3,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // header ::= head1 TOK1 TOK1 
            { parser.Tree.reduce(3,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // header ::= TOK1 head1 TOK1 
            { parser.Tree.reduce(3,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // header ::= TOK1 TOK1 head1 
            { parser.Tree.reduce(3,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // header ::= head1 TOK1 head1 TOK1 
            { parser.Tree.reduce(4,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // header ::= head1 TOK1 TOK1 head1 
            { parser.Tree.reduce(4,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // header ::= TOK1 head1 TOK1 head1 
            { parser.Tree.reduce(4,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // header ::= head1 TOK1 head1 TOK1 head1 
            { parser.Tree.reduce(5,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // head1 ::= head1 TOK2 
            { parser.Tree.reduce(2,"head1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // head1 ::= TOK2 
            { parser.Tree.reduce(1,"head1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // objs ::= objs obj obj 
            { parser.Tree.reduce(3,"objs",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("objs",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // objs ::= obj obj 
            { parser.Tree.reduce(2,"objs",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("objs",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // obj ::= OBJ_WD attrs NAME_WD QSTRING END_WD 
            { parser.Tree.reduce(5,"obj",0);
              Object RESULT =null;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		HashMap attrs = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int obj_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int obj_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String obj_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
    parser.table.put(obj_name,attrs);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("obj",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // attrs ::= attrs CM attr 
            { parser.Tree.reduce(3,"attrs",0);
              HashMap RESULT =null;
		int attrsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attrsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		HashMap attrs = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap attr = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    attrs.putAll(attr);
    RESULT = attrs;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("attrs",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // attrs ::= attr 
            { parser.Tree.reduce(1,"attrs",0);
              HashMap RESULT =null;
		int attrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		HashMap attr = (HashMap)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = attr; 

              CUP$parser$result = parser.getSymbolFactory().newSymbol("attrs",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // attr ::= QSTRING INUM 
            { parser.Tree.reduce(2,"attr",0);
              HashMap RESULT =null;
		int attr_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attr_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String attr_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int attr_valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attr_valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer attr_value = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    HashMap hm = new HashMap<String, Integer>();
    hm.put(attr_name,  attr_value);
    RESULT = hm;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("attr",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // queries ::= cmds cmd 
            { parser.Tree.reduce(2,"queries",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("queries",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // queries ::= 
            { parser.Tree.reduce(0,"queries",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("queries",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cmds ::= cmds cmd 
            { parser.Tree.reduce(2,"cmds",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmds",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // cmds ::= cmd 
            { parser.Tree.reduce(1,"cmds",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmds",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // cmd ::= QUM exp print_fn DASH QUM 
            { parser.Tree.reduce(5,"cmd",0);
              Object RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Boolean exp = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmd",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // exp ::= opr 
            { parser.Tree.reduce(1,"exp",0);
              Boolean RESULT =null;
		int opr_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int opr_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean opr_val = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
   RESULT = opr_val;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // exp ::= opr oper exp 
            { parser.Tree.reduce(3,"exp",0);
              Boolean RESULT =null;
		int opr_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int opr_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Boolean opr_val = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean e_val = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    if(op=="and"){
        RESULT = opr_val && e_val; 
    }
    if (op=="or"){
        RESULT = opr_val || e_val; 
    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // exp ::= NOT_WD OP exp CP 
            { parser.Tree.reduce(4,"exp",0);
              Boolean RESULT =null;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Boolean exp = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
  RESULT = !exp;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // opr ::= obj_ref DEQ_WD INUM 
            { parser.Tree.reduce(3,"opr",0);
              Boolean RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attr_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attr_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer attr_val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = val.equals(attr_val);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opr",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // opr ::= obj_ref DNEQ_WD INUM 
            { parser.Tree.reduce(3,"opr",0);
              Boolean RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attr_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attr_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer attr_val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = !val.equals(attr_val);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opr",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // opr ::= NOT_WD opr 
            { parser.Tree.reduce(2,"opr",0);
              Boolean RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Boolean val = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = !val;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opr",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // obj_ref ::= QSTRING DOT QSTRING 
            { parser.Tree.reduce(3,"obj_ref",0);
              Integer RESULT =null;
		int obj_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int obj_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String obj_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attr_nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attr_nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attr_name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Integer val = (Integer) parser.table.get(obj_name).get(attr_name);
    RESULT = val;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("obj_ref",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // oper ::= OR_WD 
            { parser.Tree.reduce(1,"oper",0);
              String RESULT =null;
		
    RESULT = "or";

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oper",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // oper ::= AND_WD 
            { parser.Tree.reduce(1,"oper",0);
              String RESULT =null;
		
    RESULT = "and";

              CUP$parser$result = parser.getSymbolFactory().newSymbol("oper",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // print_fn ::= print_t print_f 
            { parser.Tree.reduce(2,"print_fn",0);
              Object RESULT =null;
		int pltleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int pltright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList plt = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int plfleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int plfright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList plf = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Boolean exp = (Boolean) parser.stack(-2);
    if(exp){
        for(int i=0; i<plt.size(); i++){
            System.out.println(plt.get(i));
        }
    }else{
        for(int i=0; i<plf.size(); i++){
            System.out.println(plf.get(i));
        }
    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_fn",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // print_fn ::= print_f print_t 
            { parser.Tree.reduce(2,"print_fn",0);
              Object RESULT =null;
		int plfleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int plfright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList plf = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int pltleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pltright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList plt = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Boolean exp = (Boolean) parser.stack(-2);
    if(exp){
        for(int i=0; i<plt.size(); i++){
            System.out.println(plt.get(i));
        }
    }else{
        for(int i=0; i<plf.size(); i++){
            System.out.println(plf.get(i));
        }
    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_fn",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // print_fn ::= print_f 
            { parser.Tree.reduce(1,"print_fn",0);
              Object RESULT =null;
		int plfleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int plfright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList plf = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Boolean exp = (Boolean) parser.stack(-1);
    if(!exp)
    {
        for(int i=0; i<plf.size(); i++){
            System.out.println(plf.get(i));
        }
    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_fn",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // print_fn ::= print_t 
            { parser.Tree.reduce(1,"print_fn",0);
              Object RESULT =null;
		int pltleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int pltright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList plt = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    Boolean exp = (Boolean) parser.stack(-1);
    if(!exp){
        for(int i=0; i<plt.size(); i++){
            System.out.println(plt.get(i));
        }
    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_fn",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // print_t ::= IS_TRUE_WD print_list 
            { parser.Tree.reduce(2,"print_t",0);
              ArrayList RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int plright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList pl = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = pl;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_t",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // print_f ::= IS_FALSE_WD print_list 
            { parser.Tree.reduce(2,"print_f",0);
              ArrayList RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int plright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList pl = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    RESULT = pl;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_f",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // print_list ::= print_list PRINT_WD QSTRING 
            { parser.Tree.reduce(3,"print_list",0);
              ArrayList RESULT =null;
		int plleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int plright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList pl = (ArrayList)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    pl.add(str);
    RESULT = pl;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_list",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // print_list ::= PRINT_WD QSTRING 
            { parser.Tree.reduce(2,"print_list",0);
              ArrayList RESULT =null;
		int strleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int strright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String str = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
    ArrayList<String> pl = new ArrayList<>();
    pl.add(str);
    RESULT = pl;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("print_list",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
