
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int QUM = 10;
  public static final int CP = 16;
  public static final int ISF_WD = 20;
  public static final int CM = 9;
  public static final int OP = 15;
  public static final int IST_WD = 21;
  public static final int NAME_WD = 7;
  public static final int AND_WD = 12;
  public static final int INUM = 24;
  public static final int EQ_WD = 17;
  public static final int NOT_WD = 14;
  public static final int MQUM = 11;
  public static final int EOF = 0;
  public static final int TOK2 = 3;
  public static final int OR_WD = 13;
  public static final int SEP = 4;
  public static final int TOK1 = 2;
  public static final int DOT = 19;
  public static final int error = 1;
  public static final int NEQ_WD = 18;
  public static final int END_WD = 8;
  public static final int QSTRING = 23;
  public static final int PRINT_WD = 22;
  public static final int SC = 5;
  public static final int OBJ_WD = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOK1",
  "TOK2",
  "SEP",
  "SC",
  "OBJ_WD",
  "NAME_WD",
  "END_WD",
  "CM",
  "QUM",
  "MQUM",
  "AND_WD",
  "OR_WD",
  "NOT_WD",
  "OP",
  "CP",
  "EQ_WD",
  "NEQ_WD",
  "DOT",
  "ISF_WD",
  "IST_WD",
  "PRINT_WD",
  "QSTRING",
  "INUM"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[10]=new String("QUM");
		TT[16]=new String("CP");
		TT[20]=new String("ISF_WD");
		TT[9]=new String("CM");
		TT[15]=new String("OP");
		TT[21]=new String("IST_WD");
		TT[7]=new String("NAME_WD");
		TT[12]=new String("AND_WD");
		TT[24]=new String("INUM");
		TT[17]=new String("EQ_WD");
		TT[14]=new String("NOT_WD");
		TT[11]=new String("MQUM");
		TT[0]=new String("EOF");
		TT[3]=new String("TOK2");
		TT[13]=new String("OR_WD");
		TT[4]=new String("SEP");
		TT[2]=new String("TOK1");
		TT[19]=new String("DOT");
		TT[1]=new String("error");
		TT[18]=new String("NEQ_WD");
		TT[8]=new String("END_WD");
		TT[23]=new String("QSTRING");
		TT[22]=new String("PRINT_WD");
		TT[5]=new String("SC");
		TT[6]=new String("OBJ_WD");
	}
public String getTT(int i){return TT[i];}
}

