
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\033\000\002\002\004\000\002\002\005\000\002\003" +
    "\011\000\002\003\011\000\002\003\014\000\002\003\014" +
    "\000\002\003\014\000\002\004\005\000\002\004\002\000" +
    "\002\005\007\000\002\007\005\000\002\007\002\000\002" +
    "\014\005\000\002\014\005\000\002\014\005\000\002\014" +
    "\005\000\002\014\004\000\002\014\005\000\002\014\003" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\010\005\000\002\011\005\000\002\011\011\000\002" +
    "\012\007\000\002\012\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\121\000\010\017\ufff9\020\ufff9\021\ufff9\001\002\000" +
    "\010\017\074\020\073\021\072\001\002\000\004\002\071" +
    "\001\002\000\004\022\007\001\002\000\010\023\013\024" +
    "\012\025\011\001\002\000\004\002\000\001\002\000\004" +
    "\013\060\001\002\000\004\013\047\001\002\000\004\013" +
    "\025\001\002\000\010\023\013\024\012\025\011\001\002" +
    "\000\010\023\013\024\012\025\011\001\002\000\010\023" +
    "\013\024\012\025\011\001\002\000\012\002\ufff6\023\013" +
    "\024\012\025\011\001\002\000\004\002\ufff8\001\002\000" +
    "\010\023\013\024\012\025\011\001\002\000\012\002\ufff6" +
    "\023\013\024\012\025\011\001\002\000\004\002\ufff7\001" +
    "\002\000\004\007\046\001\002\000\010\004\026\011\030" +
    "\016\027\001\002\000\010\004\026\011\030\016\027\001" +
    "\002\000\016\005\uffef\010\uffef\011\uffef\012\uffef\014\uffef" +
    "\015\uffef\001\002\000\010\004\026\011\030\016\027\001" +
    "\002\000\014\010\032\011\035\012\036\014\033\015\034" +
    "\001\002\000\010\004\026\011\030\016\027\001\002\000" +
    "\004\007\uffeb\001\002\000\010\004\026\011\030\016\027" +
    "\001\002\000\010\004\026\011\030\016\027\001\002\000" +
    "\010\004\026\011\030\016\027\001\002\000\016\005\ufff5" +
    "\010\032\011\ufff5\012\ufff5\014\ufff5\015\034\001\002\000" +
    "\016\005\ufff4\010\032\011\ufff4\012\ufff4\014\ufff4\015\034" +
    "\001\002\000\016\005\ufff2\010\ufff2\011\ufff2\012\ufff2\014" +
    "\ufff2\015\ufff2\001\002\000\016\005\ufff3\010\ufff3\011\ufff3" +
    "\012\ufff3\014\ufff3\015\ufff3\001\002\000\016\005\ufff1\010" +
    "\032\011\ufff1\012\ufff1\014\ufff1\015\034\001\002\000\014" +
    "\005\045\010\032\011\035\012\036\015\034\001\002\000" +
    "\016\005\ufff0\010\ufff0\011\ufff0\012\ufff0\014\ufff0\015\ufff0" +
    "\001\002\000\012\002\uffee\023\uffee\024\uffee\025\uffee\001" +
    "\002\000\010\004\026\011\030\016\027\001\002\000\004" +
    "\007\051\001\002\000\012\002\uffed\023\uffed\024\uffed\025" +
    "\uffed\001\002\000\014\010\032\011\035\012\036\014\053" +
    "\015\034\001\002\000\006\006\054\007\uffea\001\002\000" +
    "\004\013\055\001\002\000\010\004\026\011\030\016\027" +
    "\001\002\000\014\010\032\011\035\012\036\014\057\015" +
    "\034\001\002\000\004\007\uffe9\001\002\000\010\004\026" +
    "\011\030\016\027\001\002\000\006\006\062\007\063\001" +
    "\002\000\004\013\064\001\002\000\012\002\uffec\023\uffec" +
    "\024\uffec\025\uffec\001\002\000\010\004\026\011\030\016" +
    "\027\001\002\000\014\010\032\011\035\012\036\014\066" +
    "\015\034\001\002\000\006\006\uffe8\007\uffe8\001\002\000" +
    "\014\010\032\011\035\012\036\014\070\015\034\001\002" +
    "\000\006\006\uffe7\007\uffe7\001\002\000\004\002\001\001" +
    "\002\000\004\007\123\001\002\000\004\007\105\001\002" +
    "\000\004\007\075\001\002\000\006\020\ufff9\021\ufff9\001" +
    "\002\000\006\020\077\021\072\001\002\000\004\007\100" +
    "\001\002\000\010\020\ufff9\021\ufff9\022\ufff9\001\002\000" +
    "\010\020\102\021\072\022\uffff\001\002\000\004\007\103" +
    "\001\002\000\006\021\ufff9\022\ufff9\001\002\000\006\021" +
    "\072\022\ufffd\001\002\000\010\017\ufff9\020\ufff9\021\ufff9" +
    "\001\002\000\010\017\110\020\107\021\072\001\002\000" +
    "\004\007\116\001\002\000\004\007\111\001\002\000\010" +
    "\020\ufff9\021\ufff9\022\ufff9\001\002\000\010\020\113\021" +
    "\072\022\ufffe\001\002\000\004\007\114\001\002\000\006" +
    "\021\ufff9\022\ufff9\001\002\000\006\021\072\022\ufffc\001" +
    "\002\000\006\017\ufff9\021\ufff9\001\002\000\006\017\120" +
    "\021\072\001\002\000\004\007\121\001\002\000\006\021" +
    "\ufff9\022\ufff9\001\002\000\006\021\072\022\ufffb\001\002" +
    "\000\012\017\ufffa\020\ufffa\021\ufffa\022\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\121\000\010\002\004\003\005\004\003\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\005\007\006\013\001\001\000\002\001\001\000\004\012" +
    "\060\001\001\000\004\011\047\001\001\000\004\010\023" +
    "\001\001\000\004\006\014\001\001\000\004\006\015\001" +
    "\001\000\004\006\016\001\001\000\006\006\020\007\017" +
    "\001\001\000\002\001\001\000\004\006\021\001\001\000" +
    "\006\006\020\007\022\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\030\001\001\000\004\014\043\001" +
    "\001\000\002\001\001\000\004\014\042\001\001\000\002" +
    "\001\001\000\004\014\041\001\001\000\002\001\001\000" +
    "\004\014\040\001\001\000\004\014\037\001\001\000\004" +
    "\014\036\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\051\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\055\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\066\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\064\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\075\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\100\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\103\001\001\000\002\001" +
    "\001\000\004\004\105\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\004\111\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\114\001\001" +
    "\000\002\001\001\000\004\004\116\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\121\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= header SEP commands 
            { parser.Tree.reduce(3,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // header ::= head_tok3 TOK1 SC head_tok3 TOK2 SC head_tok3 
            { parser.Tree.reduce(7,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // header ::= head_tok3 TOK2 SC head_tok3 TOK1 SC head_tok3 
            { parser.Tree.reduce(7,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // header ::= head_tok3 TOK1 SC head_tok3 TOK2 SC head_tok3 TOK2 SC head_tok3 
            { parser.Tree.reduce(10,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // header ::= head_tok3 TOK2 SC head_tok3 TOK1 SC head_tok3 TOK2 SC head_tok3 
            { parser.Tree.reduce(10,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // header ::= head_tok3 TOK2 SC head_tok3 TOK2 SC head_tok3 TOK1 SC head_tok3 
            { parser.Tree.reduce(10,"header",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("header",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // head_tok3 ::= head_tok3 TOK3 SC 
            { parser.Tree.reduce(3,"head_tok3",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head_tok3",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // head_tok3 ::= 
            { parser.Tree.reduce(0,"head_tok3",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("head_tok3",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // commands ::= command command command command command_list 
            { parser.Tree.reduce(5,"commands",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("commands",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // command_list ::= command command command_list 
            { parser.Tree.reduce(3,"command_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command_list",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // command_list ::= 
            { parser.Tree.reduce(0,"command_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command_list",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // exp ::= exp PLUS exp 
            { parser.Tree.reduce(3,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // exp ::= exp DASH exp 
            { parser.Tree.reduce(3,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // exp ::= exp STAR exp 
            { parser.Tree.reduce(3,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // exp ::= exp SL exp 
            { parser.Tree.reduce(3,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // exp ::= DASH exp 
            { parser.Tree.reduce(2,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // exp ::= OP exp CP 
            { parser.Tree.reduce(3,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // exp ::= INUM 
            { parser.Tree.reduce(1,"exp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // command ::= INS_WD ins SC 
            { parser.Tree.reduce(3,"command",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // command ::= CMP_WD cmp SC 
            { parser.Tree.reduce(3,"command",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // command ::= SUM_WD sum SC 
            { parser.Tree.reduce(3,"command",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // ins ::= OB exp CB 
            { parser.Tree.reduce(3,"ins",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ins",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cmp ::= OB exp CB 
            { parser.Tree.reduce(3,"cmp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cmp ::= OB exp CB CM OB exp CB 
            { parser.Tree.reduce(7,"cmp",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cmp",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // sum ::= sum CM OB exp CB 
            { parser.Tree.reduce(5,"sum",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sum",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // sum ::= OB exp CB 
            { parser.Tree.reduce(3,"sum",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sum",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
