import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    ArrayList<Integer> arr = new ArrayList<>();

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

    public void printStatck(){
        System.out.println("---Stack---");
        for(int position=0; position<8; position++){
            Object obj = (((Symbol)stack.elementAt(tos + -position)).value);
            System.out.println("Element: " + obj + " At position: " + -position );
        }
    }
:};

// expression
// E ::= E PLUS E
// | E MINUS E
// | E STAR E
// | E DIV E
// | MINUS E    %prec uminus
// | OP E CP
// | INTEGER
// ;

/////////////////////////////
//// Symbols Delaration
////////////////////////////

// terminal QUM;
// terminal EXM;
// terminal ATM;
// terminal HAM;
// terminal DOM;
// terminal PAM;
// terminal CIM;
// terminal AND;
// terminal EQ;
terminal OP;
terminal CP;
// terminal OC;
// terminal CC;
// terminal GT;
// terminal LT;
// terminal BSL;
// terminal DOT;
// terminal CO;
terminal CM;
terminal SC;
terminal STAR;
terminal DASH;
terminal PLUS;
terminal OB;
terminal CB;
terminal SL;

// terminal QU;
// terminal DQU;
// terminal GRAVE;
// terminal TIL;
// terminal OR;
// terminal US;

// terminal String VAR;
// terminal String QSTRING;
// terminal Double FNUM;
terminal Integer INUM;
// terminal Integer SINUM;

// terminal TOK1, TOK2, SEP;
terminal TOKEN1, TOKEN2, TOKEN3, SEP;
terminal String INS_WD, CMP_WD, SUM_WD;


non terminal prog ;
non terminal header, head_tok3, TOK1, TOK2, TOK3;
non terminal commands, command, command_list, cmp;
// non terminal ;
// non terminal ;
// non terminal String ;
// non terminal HashMap ;
non terminal Integer exp, sum, ins;
// non terminal Double ;

precedence left PLUS, DASH;
precedence left STAR, SL;
// precedence left CIM;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= header SEP commands
;

// header

TOK1 ::= TOKEN1 SC;
TOK2 ::= TOKEN2 SC;
TOK3 ::= TOKEN3 SC;


header ::= head_tok3 TOK1 head_tok3 TOK2 head_tok3 |
           head_tok3 TOK2 head_tok3 TOK1 head_tok3 |
           head_tok3 TOK1 head_tok3 TOK2 head_tok3 TOK2 head_tok3 |
           head_tok3 TOK2 head_tok3 TOK1 head_tok3 TOK2 head_tok3 |
           head_tok3 TOK2 head_tok3 TOK2 head_tok3 TOK1 head_tok3
;

head_tok3 ::= head_tok3 TOK3 |
;

// commands

commands ::= command command command command command_list
;

command_list ::= command command command_list |
;

exp ::= exp:el PLUS exp:er
{:
RESULT = el + er;
:}
| exp:el DASH exp:er
{:
RESULT = el - er;
:}
| exp:el STAR exp:er
{:
RESULT = el * er;
:}
| exp:el SL exp:er
{:
RESULT = el / er;
:}
| DASH exp:e 
{:
RESULT = -e;
:} 
| OP exp:e CP
{:
RESULT = e;
:}
| INUM:inum
{:
RESULT = inum;
:}
;

command ::= INS_WD ins SC | CMP_WD cmp SC  | SUM_WD sum:sum
{:
    System.out.println("sum: " + sum);
    arr.add(sum);
:}
SC 
;

ins ::= OB exp:e CB
{:
    System.out.println("ins:" + e);
    arr.add(e);
    RESULT = e;
:}
;
           
cmp ::= OB exp:e CB
{:
    Integer r1 = arr.get(arr.size() -1);
    Integer r2 = arr.get(arr.size() -2);
    if (r1.equals(r2)){
        System.out.println("cmp: " + e);
        arr.add(e);
    }else{
        System.out.println("cmp: " + 0);
        arr.add(0);
    }
:}
 | OB exp:e1 CB CM OB exp:e2 CB
 {:
    Integer r1 = arr.get(arr.size() -1);
    Integer r2 = arr.get(arr.size() -2);
    if (r1.equals(r2)){
        System.out.println("cmp: " + e1);
        arr.add(e1);
    }else{
        System.out.println("cmp: " + e2);
        arr.add(e2);
    }
 :}  
;

sum ::= sum:sum CM OB exp:e CB
{:
    sum += e;
    RESULT = sum;
:}
| OB exp:e CB
{:
    RESULT = e;
:}
; 
