// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: scanner.jflex

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\2\0"+
    "\1\5\1\6\1\0\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\0\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\0"+
    "\1\30\5\0\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\2\0\1\37\1\40\2\0\1\41\1\42\1\43\1\44"+
    "\2\0\1\45\1\0\1\46\5\0\1\47\1\0\1\50"+
    "\1\0\1\51\1\0\1\52\1\53\1\54\1\35\1\55"+
    "\1\35\6\0\1\56\1\57\1\60\1\61\1\0\1\62"+
    "\1\0\1\63\1\64\1\65\2\0\1\66\13\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\5\1\1\14\1\15"+
    "\1\16\17\0\1\17\1\0\1\20\1\21\62\0\1\22"+
    "\2\0\1\22\2\0\1\22\17\0\1\22\23\0\1\22"+
    "\20\0\1\23\36\0\1\22\2\0\1\22\2\0\1\22"+
    "\7\0\1\22\10\0\1\22\36\0\1\24\4\0\1\22"+
    "\2\0\1\22\2\0\1\22\3\0\1\22\1\0\1\22"+
    "\1\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\67\0\156\0\245\0\67\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\334\0\67\0\u0113\0\u014a"+
    "\0\u0181\0\u01b8\0\u01ef\0\u0226\0\67\0\67\0\u025d\0\u0294"+
    "\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c"+
    "\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f\0\67\0\u0596\0\67"+
    "\0\67\0\u05cd\0\u0604\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717"+
    "\0\u074e\0\u0785\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87"+
    "\0\u0abe\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f"+
    "\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7"+
    "\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf"+
    "\0\u0fe6\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167"+
    "\0\u119e\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f"+
    "\0\u1356\0\u138d\0\u13c4\0\u13fb\0\u1432\0\u1469\0\u14a0\0\u14d7"+
    "\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea\0\u1621\0\u1658\0\u168f"+
    "\0\u16c6\0\u16fd\0\u1734\0\u176b\0\u17a2\0\u17d9\0\u1810\0\u1847"+
    "\0\u187e\0\u18b5\0\u18ec\0\u1923\0\u195a\0\u1991\0\u19c8\0\u19ff"+
    "\0\u1a36\0\u1a6d\0\u1aa4\0\u1adb\0\u1b12\0\u1b49\0\u1b80\0\u1bb7"+
    "\0\u1bee\0\u1c25\0\u1c5c\0\u1c93\0\u1cca\0\u1d01\0\67\0\u1d38"+
    "\0\u1d6f\0\u1da6\0\u1ddd\0\u1e14\0\u1e4b\0\u1e82\0\u1eb9\0\u1ef0"+
    "\0\u1f27\0\u1f5e\0\u1f95\0\u1fcc\0\u2003\0\u203a\0\u2071\0\u20a8"+
    "\0\u20df\0\u2116\0\u214d\0\u2184\0\u21bb\0\u21f2\0\u2229\0\u2260"+
    "\0\u2297\0\u22ce\0\u2305\0\u233c\0\u2373\0\u23aa\0\u23e1\0\u2418"+
    "\0\u244f\0\u2486\0\u24bd\0\u24f4\0\u252b\0\u2562\0\u2599\0\u25d0"+
    "\0\u2607\0\u263e\0\u2675\0\u26ac\0\u26e3\0\u271a\0\u2751\0\u2788"+
    "\0\u27bf\0\u27f6\0\u282d\0\u2864\0\u289b\0\u28d2\0\u2909\0\u2940"+
    "\0\u2977\0\u29ae\0\u29e5\0\u2a1c\0\u2a53\0\u2a8a\0\u2ac1\0\u2af8"+
    "\0\u2b2f\0\u2b66\0\u2b9d\0\u2bd4\0\u2c0b\0\u2c42\0\u2c79\0\u2cb0"+
    "\0\u2ce7\0\u2d1e\0\u2d55\0\u2d8c\0\u2dc3\0\u2dfa\0\u2e31\0\u2e68"+
    "\0\u2e9f\0\u2ed6\0\u2f0d\0\u2f44\0\u2f7b\0\u2fb2\0\u2fe9\0\u3020"+
    "\0\67\0\u3057\0\u308e\0\u30c5\0\u30c5\0\u30fc\0\u308e\0\u3133"+
    "\0\u316a\0\u31a1\0\u31d8\0\u320f\0\u3246\0\u2607";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\2\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\2\11\15\1\16"+
    "\1\17\1\20\1\21\3\2\1\22\5\2\1\23\1\2"+
    "\1\24\1\25\16\2\71\0\1\3\71\0\1\26\77\0"+
    "\12\15\110\0\1\27\66\0\1\30\56\0\1\31\7\0"+
    "\1\32\57\0\1\33\72\0\1\34\67\0\1\35\32\0"+
    "\1\36\1\37\1\0\1\40\1\41\1\42\1\41\1\43"+
    "\1\44\1\40\1\44\1\40\1\44\57\0\1\45\112\0"+
    "\1\46\41\0\11\47\1\0\6\47\13\0\4\47\56\0"+
    "\1\50\62\0\1\51\37\0\1\52\65\0\1\53\70\0"+
    "\1\36\2\0\1\40\1\41\1\54\1\44\1\40\1\44"+
    "\1\40\1\44\1\40\1\44\52\0\1\36\3\0\1\36"+
    "\1\0\1\36\1\0\1\36\1\0\1\36\1\0\1\36"+
    "\50\0\1\53\1\0\1\36\2\0\1\40\1\44\1\40"+
    "\1\44\1\40\1\44\1\40\1\44\1\40\1\44\52\0"+
    "\1\36\2\0\1\40\1\44\1\40\1\44\1\40\1\44"+
    "\1\40\1\44\1\40\1\44\52\0\1\36\2\0\1\40"+
    "\1\44\1\40\1\44\1\40\1\55\1\0\1\36\1\0"+
    "\1\36\50\0\1\53\1\0\1\36\3\0\1\36\1\0"+
    "\1\36\1\0\1\36\1\0\1\36\1\0\1\36\55\0"+
    "\1\56\66\0\12\57\1\0\6\57\13\0\4\57\11\0"+
    "\12\52\1\60\54\52\13\0\1\61\1\62\1\0\1\63"+
    "\1\64\1\65\1\64\1\66\1\67\1\63\1\67\1\63"+
    "\1\67\52\0\1\36\2\0\1\40\1\44\1\40\1\44"+
    "\1\40\1\44\1\40\1\70\1\0\1\36\50\0\1\53"+
    "\1\0\1\36\3\0\1\36\1\0\1\36\1\0\1\36"+
    "\1\0\1\36\61\0\1\71\64\0\12\72\1\0\6\72"+
    "\13\0\4\72\11\0\12\52\1\60\35\52\1\73\16\52"+
    "\11\0\1\74\70\0\1\61\2\0\1\63\1\64\1\75"+
    "\1\67\1\63\1\67\1\63\1\67\1\63\1\67\52\0"+
    "\1\61\3\0\1\61\1\0\1\61\1\0\1\61\1\0"+
    "\1\61\1\0\1\61\50\0\1\74\1\0\1\61\2\0"+
    "\1\63\1\67\1\63\1\67\1\63\1\67\1\63\1\67"+
    "\1\63\1\67\52\0\1\61\2\0\1\63\1\67\1\63"+
    "\1\67\1\63\1\67\1\63\1\67\1\63\1\67\52\0"+
    "\1\61\2\0\1\63\1\67\1\63\1\67\1\63\1\76"+
    "\1\0\1\61\1\0\1\61\50\0\1\74\1\0\1\61"+
    "\3\0\1\61\1\0\1\61\1\0\1\61\1\0\1\61"+
    "\1\0\1\61\50\0\1\53\1\0\1\36\3\0\1\36"+
    "\1\0\1\36\66\0\1\77\1\100\62\0\12\101\1\0"+
    "\6\101\13\0\4\101\11\0\12\52\1\60\35\52\1\3"+
    "\16\52\13\0\1\102\1\103\1\0\1\104\1\105\1\106"+
    "\1\105\1\107\1\110\1\104\1\110\1\104\1\110\52\0"+
    "\1\61\2\0\1\63\1\67\1\63\1\67\1\63\1\67"+
    "\1\63\1\111\1\0\1\61\50\0\1\74\1\0\1\61"+
    "\3\0\1\61\1\0\1\61\1\0\1\61\1\0\1\61"+
    "\56\0\1\112\66\0\1\113\57\0\1\114\2\0\1\114"+
    "\4\0\12\115\1\0\6\115\13\0\4\115\22\0\1\116"+
    "\70\0\1\102\2\0\1\104\1\105\1\117\1\110\1\104"+
    "\1\110\1\104\1\110\1\104\1\110\52\0\1\102\3\0"+
    "\1\102\1\0\1\102\1\0\1\102\1\0\1\102\1\0"+
    "\1\102\50\0\1\116\1\0\1\102\2\0\1\104\1\110"+
    "\1\104\1\110\1\104\1\110\1\104\1\110\1\104\1\110"+
    "\52\0\1\102\2\0\1\104\1\110\1\104\1\110\1\104"+
    "\1\110\1\104\1\110\1\104\1\110\52\0\1\102\2\0"+
    "\1\104\1\110\1\104\1\110\1\104\1\120\1\0\1\102"+
    "\1\0\1\102\50\0\1\116\1\0\1\102\3\0\1\102"+
    "\1\0\1\102\1\0\1\102\1\0\1\102\1\0\1\102"+
    "\50\0\1\74\1\0\1\61\3\0\1\61\1\0\1\61"+
    "\63\0\1\121\1\122\14\0\1\123\5\0\1\124\1\125"+
    "\1\0\1\126\37\0\1\127\17\0\1\130\1\0\1\131"+
    "\45\0\11\132\1\0\6\132\13\0\4\132\27\0\12\133"+
    "\1\0\6\133\13\0\4\133\24\0\1\134\1\135\1\0"+
    "\1\136\1\137\1\140\1\137\1\141\1\142\1\136\1\142"+
    "\1\136\1\142\52\0\1\102\2\0\1\104\1\110\1\104"+
    "\1\110\1\104\1\110\1\104\1\143\1\0\1\102\50\0"+
    "\1\116\1\0\1\102\3\0\1\102\1\0\1\102\1\0"+
    "\1\102\1\0\1\102\70\0\1\144\55\0\1\145\1\146"+
    "\1\145\123\0\1\147\71\0\1\150\62\0\1\151\67\0"+
    "\1\152\30\0\1\145\1\153\123\0\1\154\63\0\1\155"+
    "\32\0\12\156\1\0\6\156\13\0\4\156\27\0\12\157"+
    "\1\0\6\157\13\0\4\157\22\0\1\160\70\0\1\134"+
    "\2\0\1\136\1\137\1\161\1\142\1\136\1\142\1\136"+
    "\1\142\1\136\1\142\52\0\1\134\3\0\1\134\1\0"+
    "\1\134\1\0\1\134\1\0\1\134\1\0\1\134\50\0"+
    "\1\160\1\0\1\134\2\0\1\136\1\142\1\136\1\142"+
    "\1\136\1\142\1\136\1\142\1\136\1\142\52\0\1\134"+
    "\2\0\1\136\1\142\1\136\1\142\1\136\1\142\1\136"+
    "\1\142\1\136\1\142\52\0\1\134\2\0\1\136\1\142"+
    "\1\136\1\142\1\136\1\162\1\0\1\134\1\0\1\134"+
    "\50\0\1\160\1\0\1\134\3\0\1\134\1\0\1\134"+
    "\1\0\1\134\1\0\1\134\1\0\1\134\50\0\1\116"+
    "\1\0\1\102\3\0\1\102\1\0\1\102\62\0\1\163"+
    "\66\0\1\164\66\0\1\165\125\0\1\166\77\0\1\167"+
    "\64\0\1\170\64\0\1\171\22\0\1\172\124\0\1\173"+
    "\72\0\1\174\25\0\12\175\1\0\6\175\13\0\4\175"+
    "\27\0\12\176\1\0\6\176\13\0\4\176\24\0\1\177"+
    "\1\200\1\0\1\201\1\202\1\203\1\202\1\204\1\205"+
    "\1\201\1\205\1\201\1\205\52\0\1\134\2\0\1\136"+
    "\1\142\1\136\1\142\1\136\1\142\1\136\1\206\1\0"+
    "\1\134\50\0\1\160\1\0\1\134\3\0\1\134\1\0"+
    "\1\134\1\0\1\134\1\0\1\134\61\0\1\207\1\210"+
    "\63\0\1\211\2\212\1\213\63\0\1\211\2\212\1\210"+
    "\122\0\1\214\66\0\1\215\71\0\1\216\71\0\1\217"+
    "\21\0\1\220\132\0\1\221\70\0\1\222\20\0\12\223"+
    "\1\0\6\223\13\0\4\223\17\0\1\114\2\0\1\114"+
    "\66\0\1\224\70\0\1\177\2\0\1\201\1\202\1\225"+
    "\1\205\1\201\1\205\1\201\1\205\1\201\1\205\52\0"+
    "\1\177\3\0\1\177\1\0\1\177\1\0\1\177\1\0"+
    "\1\177\1\0\1\177\50\0\1\224\1\0\1\177\2\0"+
    "\1\201\1\205\1\201\1\205\1\201\1\205\1\201\1\205"+
    "\1\201\1\205\52\0\1\177\2\0\1\201\1\205\1\201"+
    "\1\205\1\201\1\205\1\201\1\205\1\201\1\205\52\0"+
    "\1\177\2\0\1\201\1\205\1\201\1\205\1\201\1\226"+
    "\1\0\1\177\1\0\1\177\50\0\1\224\1\0\1\177"+
    "\3\0\1\177\1\0\1\177\1\0\1\177\1\0\1\177"+
    "\1\0\1\177\50\0\1\160\1\0\1\134\3\0\1\134"+
    "\1\0\1\134\65\0\10\227\55\0\1\227\67\0\11\227"+
    "\55\0\12\227\55\0\2\227\125\0\1\216\72\0\1\230"+
    "\57\0\1\231\70\0\1\232\30\0\7\227\125\0\1\233"+
    "\54\0\1\234\22\0\1\235\2\0\1\235\4\0\12\236"+
    "\1\0\6\236\13\0\4\236\24\0\1\237\1\240\1\0"+
    "\1\241\1\242\1\243\1\242\1\244\1\245\1\241\1\245"+
    "\1\241\1\245\52\0\1\177\2\0\1\201\1\205\1\201"+
    "\1\205\1\201\1\205\1\201\1\246\1\0\1\177\50\0"+
    "\1\224\1\0\1\177\3\0\1\177\1\0\1\177\1\0"+
    "\1\177\1\0\1\177\117\0\1\247\65\0\1\250\67\0"+
    "\1\251\62\0\1\252\76\0\1\253\23\0\11\254\1\0"+
    "\6\254\13\0\4\254\27\0\12\255\1\0\6\255\13\0"+
    "\4\255\22\0\1\256\70\0\1\237\2\0\1\241\1\242"+
    "\1\257\1\245\1\241\1\245\1\241\1\245\1\241\1\245"+
    "\52\0\1\237\3\0\1\237\1\0\1\237\1\0\1\237"+
    "\1\0\1\237\1\0\1\237\50\0\1\256\1\0\1\237"+
    "\2\0\1\241\1\245\1\241\1\245\1\241\1\245\1\241"+
    "\1\245\1\241\1\245\52\0\1\237\2\0\1\241\1\245"+
    "\1\241\1\245\1\241\1\245\1\241\1\245\1\241\1\245"+
    "\52\0\1\237\2\0\1\241\1\245\1\241\1\245\1\241"+
    "\1\260\1\0\1\237\1\0\1\237\50\0\1\256\1\0"+
    "\1\237\3\0\1\237\1\0\1\237\1\0\1\237\1\0"+
    "\1\237\1\0\1\237\50\0\1\224\1\0\1\177\3\0"+
    "\1\177\1\0\1\177\120\0\1\261\75\0\1\145\57\0"+
    "\1\262\75\0\1\263\72\0\1\145\16\0\12\264\1\0"+
    "\6\264\13\0\4\264\27\0\12\265\1\0\6\265\13\0"+
    "\4\265\24\0\1\266\1\267\1\0\1\270\1\271\1\272"+
    "\1\271\1\273\1\274\1\270\1\274\1\270\1\274\52\0"+
    "\1\237\2\0\1\241\1\245\1\241\1\245\1\241\1\245"+
    "\1\241\1\275\1\0\1\237\50\0\1\256\1\0\1\237"+
    "\3\0\1\237\1\0\1\237\1\0\1\237\1\0\1\237"+
    "\116\0\1\276\66\0\1\277\77\0\1\153\16\0\12\300"+
    "\1\0\6\300\13\0\4\300\27\0\12\301\1\0\6\301"+
    "\13\0\4\301\22\0\1\302\70\0\1\266\2\0\1\270"+
    "\1\271\1\303\1\274\1\270\1\274\1\270\1\274\1\270"+
    "\1\274\52\0\1\266\3\0\1\266\1\0\1\266\1\0"+
    "\1\266\1\0\1\266\1\0\1\266\50\0\1\302\1\0"+
    "\1\266\2\0\1\270\1\274\1\270\1\274\1\270\1\274"+
    "\1\270\1\274\1\270\1\274\52\0\1\266\2\0\1\270"+
    "\1\274\1\270\1\274\1\270\1\274\1\270\1\274\1\270"+
    "\1\274\52\0\1\266\2\0\1\270\1\274\1\270\1\274"+
    "\1\270\1\304\1\0\1\266\1\0\1\266\50\0\1\302"+
    "\1\0\1\266\3\0\1\266\1\0\1\266\1\0\1\266"+
    "\1\0\1\266\1\0\1\266\50\0\1\256\1\0\1\237"+
    "\3\0\1\237\1\0\1\237\127\0\1\146\66\0\1\144"+
    "\22\0\12\305\1\0\6\305\13\0\4\305\17\0\1\235"+
    "\2\0\1\235\70\0\1\306\1\307\1\0\1\310\1\311"+
    "\1\312\1\311\1\313\1\314\1\310\1\314\1\310\1\314"+
    "\52\0\1\266\2\0\1\270\1\274\1\270\1\274\1\270"+
    "\1\274\1\270\1\315\1\0\1\266\50\0\1\302\1\0"+
    "\1\266\3\0\1\266\1\0\1\266\1\0\1\266\1\0"+
    "\1\266\47\0\1\316\2\0\1\316\4\0\12\317\1\0"+
    "\6\317\13\0\4\317\22\0\1\320\70\0\1\306\2\0"+
    "\1\310\1\311\1\321\1\314\1\310\1\314\1\310\1\314"+
    "\1\310\1\314\52\0\1\306\3\0\1\306\1\0\1\306"+
    "\1\0\1\306\1\0\1\306\1\0\1\306\50\0\1\320"+
    "\1\0\1\306\2\0\1\310\1\314\1\310\1\314\1\310"+
    "\1\314\1\310\1\314\1\310\1\314\52\0\1\306\2\0"+
    "\1\310\1\314\1\310\1\314\1\310\1\314\1\310\1\314"+
    "\1\310\1\314\52\0\1\306\2\0\1\310\1\314\1\310"+
    "\1\314\1\310\1\322\1\0\1\306\1\0\1\306\50\0"+
    "\1\320\1\0\1\306\3\0\1\306\1\0\1\306\1\0"+
    "\1\306\1\0\1\306\1\0\1\306\50\0\1\302\1\0"+
    "\1\266\3\0\1\266\1\0\1\266\64\0\11\323\1\0"+
    "\6\323\13\0\4\323\27\0\12\324\1\0\6\324\13\0"+
    "\4\324\24\0\1\325\1\326\1\0\1\327\1\330\1\331"+
    "\1\330\1\332\1\333\1\327\1\333\1\327\1\333\52\0"+
    "\1\306\2\0\1\310\1\314\1\310\1\314\1\310\1\314"+
    "\1\310\1\334\1\0\1\306\50\0\1\320\1\0\1\306"+
    "\3\0\1\306\1\0\1\306\1\0\1\306\1\0\1\306"+
    "\57\0\12\335\1\0\6\335\13\0\4\335\27\0\12\336"+
    "\1\0\6\336\13\0\4\336\22\0\1\337\70\0\1\325"+
    "\2\0\1\327\1\330\1\340\1\333\1\327\1\333\1\327"+
    "\1\333\1\327\1\333\52\0\1\325\3\0\1\325\1\0"+
    "\1\325\1\0\1\325\1\0\1\325\1\0\1\325\50\0"+
    "\1\337\1\0\1\325\2\0\1\327\1\333\1\327\1\333"+
    "\1\327\1\333\1\327\1\333\1\327\1\333\52\0\1\325"+
    "\2\0\1\327\1\333\1\327\1\333\1\327\1\333\1\327"+
    "\1\333\1\327\1\333\52\0\1\325\2\0\1\327\1\333"+
    "\1\327\1\333\1\327\1\341\1\0\1\325\1\0\1\325"+
    "\50\0\1\337\1\0\1\325\3\0\1\325\1\0\1\325"+
    "\1\0\1\325\1\0\1\325\1\0\1\325\50\0\1\320"+
    "\1\0\1\306\3\0\1\306\1\0\1\306\63\0\12\342"+
    "\1\0\6\342\13\0\4\342\27\0\12\343\1\0\6\343"+
    "\13\0\4\343\24\0\1\344\1\345\1\0\1\346\1\347"+
    "\1\350\1\347\1\351\1\352\1\346\1\352\1\346\1\352"+
    "\52\0\1\325\2\0\1\327\1\333\1\327\1\333\1\327"+
    "\1\333\1\327\1\353\1\0\1\325\50\0\1\337\1\0"+
    "\1\325\3\0\1\325\1\0\1\325\1\0\1\325\1\0"+
    "\1\325\57\0\12\354\1\0\6\354\13\0\4\354\17\0"+
    "\1\316\2\0\1\316\66\0\1\355\70\0\1\344\2\0"+
    "\1\346\1\347\1\356\1\352\1\346\1\352\1\346\1\352"+
    "\1\346\1\352\52\0\1\344\3\0\1\344\1\0\1\344"+
    "\1\0\1\344\1\0\1\344\1\0\1\344\50\0\1\355"+
    "\1\0\1\344\2\0\1\346\1\352\1\346\1\352\1\346"+
    "\1\352\1\346\1\352\1\346\1\352\52\0\1\344\2\0"+
    "\1\346\1\352\1\346\1\352\1\346\1\352\1\346\1\352"+
    "\1\346\1\352\52\0\1\344\2\0\1\346\1\352\1\346"+
    "\1\352\1\346\1\357\1\0\1\344\1\0\1\344\50\0"+
    "\1\355\1\0\1\344\3\0\1\344\1\0\1\344\1\0"+
    "\1\344\1\0\1\344\1\0\1\344\50\0\1\337\1\0"+
    "\1\325\3\0\1\325\1\0\1\325\53\0\1\235\2\0"+
    "\1\235\4\0\12\360\1\0\6\360\13\0\4\360\24\0"+
    "\1\361\1\362\1\0\1\363\1\364\1\365\1\364\1\366"+
    "\1\367\1\363\1\367\1\363\1\367\52\0\1\344\2\0"+
    "\1\346\1\352\1\346\1\352\1\346\1\352\1\346\1\370"+
    "\1\0\1\344\50\0\1\355\1\0\1\344\3\0\1\344"+
    "\1\0\1\344\1\0\1\344\1\0\1\344\57\0\12\371"+
    "\1\0\6\371\13\0\4\371\24\0\1\361\2\0\1\363"+
    "\1\364\1\372\1\367\1\363\1\367\1\363\1\367\1\363"+
    "\1\367\52\0\1\361\3\0\1\361\1\0\1\361\1\0"+
    "\1\361\1\0\1\361\1\0\1\361\52\0\1\361\2\0"+
    "\1\363\1\367\1\363\1\367\1\363\1\367\1\363\1\367"+
    "\1\363\1\367\52\0\1\361\2\0\1\363\1\367\1\363"+
    "\1\367\1\363\1\373\1\0\1\361\1\0\1\361\50\0"+
    "\1\355\1\0\1\344\3\0\1\344\1\0\1\344\63\0"+
    "\12\374\1\0\6\374\13\0\4\374\24\0\1\361\2\0"+
    "\1\363\1\367\1\363\1\367\1\363\1\367\1\363\1\375"+
    "\1\0\1\361\52\0\1\361\3\0\1\361\1\0\1\361"+
    "\1\0\1\361\1\0\1\361\57\0\12\376\1\0\6\376"+
    "\13\0\4\376\24\0\1\361\3\0\1\361\1\0\1\361"+
    "\45\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12925];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\7\11\1\1\1\11\6\1\2\11"+
    "\17\0\1\11\1\0\2\11\62\0\1\1\2\0\1\1"+
    "\2\0\1\1\17\0\1\1\23\0\1\1\20\0\1\11"+
    "\36\0\1\1\2\0\1\1\2\0\1\1\7\0\1\1"+
    "\10\0\1\1\36\0\1\1\4\0\1\11\2\0\1\1"+
    "\2\0\1\1\3\0\1\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[254];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol sym(int type){
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol sym(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Scanner Error: " + yytext());
            }
          // fall through
          case 21: break;
          case 2:
            { ;
            }
          // fall through
          case 22: break;
          case 3:
            { return sym(sym.OP);
            }
          // fall through
          case 23: break;
          case 4:
            { return sym(sym.CP);
            }
          // fall through
          case 24: break;
          case 5:
            { return sym(sym.STAR);
            }
          // fall through
          case 25: break;
          case 6:
            { return sym(sym.PLUS);
            }
          // fall through
          case 26: break;
          case 7:
            { return sym(sym.CM);
            }
          // fall through
          case 27: break;
          case 8:
            { return sym(sym.DASH);
            }
          // fall through
          case 28: break;
          case 9:
            { return sym(sym.SL);
            }
          // fall through
          case 29: break;
          case 10:
            { return sym(sym.INUM, new Integer(yytext()));
            }
          // fall through
          case 30: break;
          case 11:
            { return sym(sym.SC);
            }
          // fall through
          case 31: break;
          case 12:
            { return sym(sym.OB);
            }
          // fall through
          case 32: break;
          case 13:
            { return sym(sym.CB);
            }
          // fall through
          case 33: break;
          case 14:
            { return sym(sym.SEP);
            }
          // fall through
          case 34: break;
          case 15:
            { return sym(sym.CMP_WD, new String(yytext()));
            }
          // fall through
          case 35: break;
          case 16:
            { return sym(sym.INS_WD, new String(yytext()));
            }
          // fall through
          case 36: break;
          case 17:
            { return sym(sym.SUM_WD, new String(yytext()));
            }
          // fall through
          case 37: break;
          case 18:
            { return sym(sym.TOKEN1);
            }
          // fall through
          case 38: break;
          case 19:
            { return sym(sym.TOKEN2);
            }
          // fall through
          case 39: break;
          case 20:
            { return sym(sym.TOKEN3);
            }
          // fall through
          case 40: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
