import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, String>();
:};

parser code {:
    public HashMap <String, String> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

    public void printStatck(){
        System.out.println("---Stack---");
        for(int position=0; position<10; position++){
            Object obj = (((Symbol)stack.elementAt(tos + -position)).value);
            System.out.println("Element: " + obj + " At position: " + -position );
        }
    }

    public void test(){
        HashMap hm1 = new HashMap<String, Integer>();
        hm1.put("x", 1);
        HashMap hm2 = new HashMap<String, Integer>();
        hm2.put("y", 2);
        
        hm1.putAll(hm2);
        System.out.println("hm1: " + hm1);
        
        for (Object key : hm1.keySet()) {
            Integer value = (Integer) hm1.get(key);
            System.out.println("Key: " + key + " Value: " + value);
        }

        ArrayList<Integer> arr = new ArrayList<>();
        arr.add(1);
        arr.add(1);
        Integer index0 = arr.get(0);
        Integer index1 = arr.get(1);
        System.out.println("arr: " + arr);
        System.out.println("arr.size(): " + arr.size());
        System.out.println("arr.get(0): " + arr.get(0));
        System.out.println("compare equal: " + index0.equals(index1));
    }

:};

// expression
// exp ::= exp:el PLUS exp:er {: RESULT = el + er; :} |
// exp:el DASH exp:er {: RESULT = el - er; :} |
// exp:el STAR exp:er {: RESULT = el * er; :} |
// exp:el SL exp:er {: RESULT = el / er; :} |
// DASH exp:e  {: RESULT = -e; :}  |
// OP exp:e CP {: RESULT = e; :} |
// INUM:inum {: RESULT = inum; :}
// ;

/////////////////////////////
//// Symbols Delaration
////////////////////////////

// terminal QUM;
// terminal EXM;
// terminal ATM;
// terminal HAM;
// terminal DOM;
// terminal PAM;
// terminal CIM;
// terminal AND;
// terminal STAR;
terminal DASH;
terminal EQ;
// terminal PLUS;
terminal OP;
terminal CP;
terminal OB;
terminal CB;
// terminal OC;
// terminal CC;
terminal GT;
terminal LT;
// terminal SL;
// terminal BSL;
// terminal DOT;
// terminal CO;
terminal CM;
terminal SC;
// terminal QU;
// terminal DQU;
// terminal GRAVE;
// terminal TIL;
// terminal OR;
// terminal US;

terminal String VAR;
terminal String QSTRING;
// terminal Double FNUM;
// terminal Double RNUM;
// terminal Integer INUM;
// terminal Integer SINUM;

// terminal TOKEN1, TOKEN2, SEP;
terminal TOKEN1, TOKEN2, TOKEN3, SEP;
terminal String IF_WD, TS_WD, FS_WD, MAX_WD, OR_WD, AND_WD, NOT_WD, T_WD, F_WD;


non terminal prog;
non terminal header, TOK1, TOK2, TOK3;
non terminal head1, exec ;
non terminal ins, ins_list;
non terminal ass;
non terminal max, var_list;
non terminal if, ass_list, if_opt;
non terminal String oper;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;
non terminal Boolean opr, exp ;


// precedence left PLUS, DASH;
// precedence left STAR, SL;
// precedence left CIM;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= header SEP exec
;

TOK1 ::= TOKEN1 SC
;

TOK2 ::= TOKEN2 SC
;

TOK3 ::= TOKEN3 SC
;

// header

header ::= head1 |
           head1 TOK2 head1 |
           head1 TOK2 head1 TOK2 head1 TOK2 head1 TOK2 head1 TOK2 head1 TOK2 head1 TOK2 head1
           
;

head1 ::= TOK1 | TOK3 | head1 TOK1 | head1 TOK3
;

// exec 

exec ::= ins ins ins ins ins_list
;

ins_list ::= ins ins ins_list | ins ins
;

ins ::= ass | max | if
; 

// ass

ass ::= VAR:id DASH GT QSTRING:value SC
{:
    parser.table.put(id, value);
:}
| VAR:id LT DASH QSTRING:value SC
{:
    parser.table.put(id, value);
:}
;

// max

max ::= MAX_WD var_list SC
;

var_list ::= VAR CM var_list | VAR
;

//if

if ::= IF_WD OB exp CB TS_WD OP ass_list CP if_opt
;

ass_list ::= ass ass_list | ass
;

if_opt ::= FS_WD OP ass_list CP SC | SC
;

// exp

exp ::= opr:opr_val
{:
  RESULT = opr_val;
:}
| opr:opr_val oper:op exp:e_val
{:
    // if (op == "or"){
    //     RESULT = opr_val || e_val;
    // }
    // if (op == "and"){
    //     RESULT = opr_val && e_val;
    // }
    // if (op == "not"){
    // }
:}
;

opr ::= VAR:id EQ EQ QSTRING:value
{:
  String val = parser.table.get(id);
  RESULT = val.equals(value);
:}
| T_WD
{:
  RESULT = true;
:}
| F_WD
{:
  RESULT = false;
:}
| NOT_WD opr
{:
//   RESULT = !(opr);
:}
;

oper ::= OR_WD
{:
    RESULT = "or";
:}
| AND_WD
{:
    RESULT = "and";
:}
| NOT_WD
{:
    RESULT = "not";
:}
;
