import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>>table;

    public void report_error(String message, Object info) {
        System.err.print("ERROR: Syntax error");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.print(" (line "+line+", column "+column+"): ");
            } else System.err.print(": ");
        else System.err.print(": ");
    }

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

:};

/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal SEP, TOK1, TOK2, START_WD, DASH, SC,BATTERY_WD, KWH_WD, FUEL_WD, LITERS_WD, PLUS, STAR, MAX_WD, CM, MOD_WD, USE_WD, DO_WD,DONE_WD, KM_WD, UNITKM_WD, OP, CP;
terminal Double REAL_NUM;

non terminal prog ,HEADER,RUN;
non terminal TOK1S, COMMANDS, COMAND,  MOD, USE ;
non terminal Double EXP, FUEL_ASS, BATTERY_ASS,EXPS;
non terminal Double[] START, CONS;

precedence left PLUS;
precedence left STAR;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP RUN
;

HEADER ::=  TOK1S
        |   TOK1S TOK2 TOK1S TOK2 TOK1S
        |   TOK1S TOK2 TOK1S TOK2 TOK1S TOK2 TOK1S
;

TOK1S ::= TOK1S TOK1 | 
;


//RUN


RUN ::= START COMMANDS
;

COMMANDS ::= COMMANDS COMAND COMAND | COMAND COMAND COMAND COMAND
; 

START ::=   START_WD BATTERY_ASS:x DASH FUEL_ASS:y SC {:Double[] arr = new Double[2]; arr[0] = x; arr[1]= y; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
        |   START_WD FUEL_ASS:y DASH BATTERY_ASS:x SC {:Double[] arr = new Double[2]; arr[0] = x; arr[1]= y; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
        |   START_WD BATTERY_ASS:x DASH SC {:Double[] arr = new Double[2]; arr[0] = x; arr[1]= 100.0; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
        |   START_WD DASH BATTERY_ASS:x SC {:Double[] arr = new Double[2]; arr[0] = x; arr[1]= 100.0; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
        |   START_WD FUEL_ASS:y DASH SC {:Double[] arr = new Double[2]; arr[0] = 100.0; arr[1]= y; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
        |   START_WD DASH FUEL_ASS:y SC {:Double[] arr = new Double[2]; arr[0] = 100.0; arr[1]= y; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
        |   START_WD DASH SC {:Double[] arr = new Double[2]; arr[0] = 100.0; arr[1]= 100.0; RESULT = arr; System.out.println("battery="+arr[0]+" fuel="+arr[1]);:}
;

BATTERY_ASS ::= BATTERY_WD EXP:x KWH_WD {:RESULT =x; :}
;

FUEL_ASS ::= FUEL_WD EXP:x LITERS_WD {:RESULT =x; :}
;

EXP ::= EXP:x PLUS EXP:y {:RESULT = x + y ;:}
    |   EXP:x STAR EXP:y {:RESULT = x * y ;:}
    |   MAX_WD OP EXPS:x CP  {:RESULT =x; :}
    |   REAL_NUM:x {:RESULT =x; :}
;


EXPS ::= EXPS:x CM EXP:y{:
if(x>y){
    RESULT = x;
}else{
    RESULT = y;
};
:} 
| EXP:x {:RESULT = x;:}   
;

COMAND ::= MOD:x{:RESULT = x;:} SC | USE:x SC{:RESULT = x;:}
;

MOD ::= MOD_WD BATTERY_WD EXP:x{:
    Double[] arr = (Double[])parser.stack(-4);
    arr[0] = arr[0] + x;
    RESULT = arr;
      System.out.println("battery="+arr[0]+" fuel="+arr[1]);
    :}  | 
    MOD_WD FUEL_WD EXP:x{:
    Double[] arr = (Double[])parser.stack(-4);
    arr[1] = arr[1]+ x;
    RESULT = arr;
      System.out.println("battery="+arr[0]+" fuel="+arr[1]);
    :}
;

USE ::= USE_WD BATTERY_WD DO_WD CONS:x DONE_WD {:RESULT = x;:} | USE_WD FUEL_WD DO_WD CONS:x DONE_WD {:RESULT = x;:} 
;

CONS ::= CONS:arr EXP:x KM_WD EXP:y UNITKM_WD SC {:
    if(parser.stack(-7).equals("FUEL")){
        arr[1] = arr[1] - (x * y );
        RESULT = arr;
    }else if(parser.stack(-7).equals("BATTREY")){
        arr[0] = arr[0] - (x * y );
        RESULT = arr;
    };
    System.out.println("battery="+arr[0]+" fuel="+arr[1]);
:} | EXP:x KM_WD EXP:y UNITKM_WD SC {:

    Double[] arr = (Double[]) parser.stack(-8);
    if(parser.stack(-6).equals("FUEL")){
        arr[1] = arr[1] - (x * y );
        RESULT = arr;
    }
    if(parser.stack(-6).equals("BATTERY")){
        
        arr[0] = arr[0] - (x * y );
        RESULT = arr;
    };
     System.out.println("battery="+arr[0]+" fuel="+arr[1]);
    :}
;
