import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOK1, TOK2, SEP;
// terminal TOK1, TOK2, TOK3, SEP;
terminal SC, DASH, OP, CP, CM;
terminal String START_WD, BATTERY_WD, FUEL_WD, USE_WD, DO_WD, DONE_WD, MOD_WD, UNITS_KM_WD, PLUS_WD,
                 STAR_WD, KWH_WD, LITERS_WD, MAX_WD, KM_WD;
terminal Double FNUM;
terminal Integer SINUM;

non terminal prog ;
non terminal HEADER, RUN;
non terminal HEAD1;
non terminal START, COMMAND, COMMANDS, BATTERY_ASS, FUEL_ASS, EXP, MOD, USE,
                    POWER_TYPE, CONS, CON, OPER, OPR, MAX, EXPS;
// non terminal ;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP RUN
;

// header

HEADER ::= HEAD1 |
           HEAD1 TOK2 SC HEAD1 TOK2 SC HEAD1 |
           HEAD1 TOK2 SC HEAD1 TOK2 SC HEAD1 TOK2 SC HEAD1 
;

HEAD1 ::= HEAD1 TOK1 SC | 
;

// run
RUN ::= START COMMAND COMMAND COMMAND COMMAND
;

START ::= START_WD BATTERY_ASS DASH FUEL_ASS SC |
          START_WD FUEL_ASS DASH BATTERY_ASS SC |
          START_WD BATTERY_ASS DASH SC |
          START_WD FUEL_ASS DASH SC
;

BATTERY_ASS ::= BATTERY_WD EXP KWH_WD
;

FUEL_ASS ::= FUEL_WD EXP LITERS_WD
;

EXP ::=  OPR | OPR OPER EXP
;

OPR ::= SINUM | FNUM | MAX
;

OPER ::= PLUS_WD | STAR_WD
;

MAX ::= MAX_WD OP EXPS CP
;

EXPS ::= EXPS CM EXP | EXP
;

COMMANDS ::= COMMANDS COMMAND COMMAND;

COMMAND ::= MOD | USE
;

MOD ::= MOD_WD POWER_TYPE EXP SC
;

USE ::= USE_WD POWER_TYPE DO_WD CONS DONE_WD SC
;

POWER_TYPE ::= BATTERY_WD |  FUEL_WD
;

CONS ::= CONS CON | CON
;

CON ::= EXP KM_WD EXP UNITS_KM_WD SC
;
