import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};

/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal TOK1, TOK2;
terminal String PRINT_WD, COMPARE_WD, WITH_WD, END_WD;
terminal SEP, STAR, DASH, EQ, PLUS, OP, CP, OC, CC, SC, SL;
terminal String VAR;
// terminal Double test;
terminal Integer INUM;

non terminal prog ;
non terminal HEADER, HEADER1, HEADER2;
non terminal SEC1, SEC2, SEC2_3, SEC2_7, TOK1_REPEAT, TOK1_OCCURS;
non terminal COMMANDS, COMMAND;
non terminal ASSIGNMENT,EXPR, EXP, OPER, BLOCK;
non terminal COMPARE, COMP_LIST, COMP, PRINT_LIST;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double ;

// precedence left ;
precedence left PLUS, DASH;
precedence left STAR, SL;
precedence left OP, CP;

/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER | HEADER SEP COMMANDS
;
HEADER ::= HEADER1 | HEADER2
;

//
HEADER1 ::= SEC1 SEC2
;
SEC1 ::= TOK1 TOK1 TOK1 TOK1_REPEAT
;
TOK1_REPEAT ::= TOK1 TOK1 | TOK1 TOK1 TOK1_REPEAT 
;
SEC2 ::= SEC2_3 | SEC2_7 SEC2_7 SEC2_7
;
SEC2_3 ::= TOK2 TOK2 TOK2
;
SEC2_7 ::= TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2  
; 
//
HEADER2 ::= TOK2 TOK1_OCCURS  TOK2 TOK1_OCCURS  TOK2 TOK1_OCCURS |
            
            TOK2              TOK2 TOK1_OCCURS  TOK2 TOK1_OCCURS |
            TOK2 TOK1_OCCURS  TOK2              TOK2 TOK1_OCCURS |
            TOK2 TOK1_OCCURS  TOK2 TOK1_OCCURS  TOK2             |

            TOK2 TOK1_OCCURS TOK2 TOK2 |
            TOK2 TOK2 TOK1_OCCURS TOK2 |
            TOK2 TOK2 TOK2 TOK1_OCCURS |
        
;
TOK1_OCCURS ::= TOK1 | TOK1_OCCURS TOK1
;

//
COMMANDS ::= COMMAND | COMMANDS COMMAND
;
COMMAND ::= ASSIGNMENT | COMPARE 
;

//
ASSIGNMENT ::= VAR EQ EXPR SC
;
OPER ::= PLUS | DASH | STAR | SL
;
EXPR ::= EXPR OPER EXPR | OP EXPR CP | EXP
;
EXP ::=  BLOCK OPER BLOCK | BLOCK
;
BLOCK ::= INUM | VAR
;

//
COMPARE ::= COMPARE_WD EXPR  WITH_WD COMP_LIST END_WD SC
;
COMP_LIST ::= COMP COMP_LIST | COMP
; 
COMP ::= EXPR OC PRINT_LIST CC
;
PRINT_LIST ::= PRINT_WD EXPR SC
;