
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.io.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\054\000\002\002\004\000\002\002\003\000\002\002" +
    "\005\000\002\003\003\000\002\003\003\000\002\004\004" +
    "\000\002\006\006\000\002\012\004\000\002\012\005\000" +
    "\002\007\003\000\002\007\005\000\002\010\005\000\002" +
    "\011\011\000\002\005\013\000\002\005\012\000\002\005" +
    "\012\000\002\005\012\000\002\005\011\000\002\005\011" +
    "\000\002\005\011\000\002\005\002\000\002\013\004\000" +
    "\002\013\005\000\002\014\003\000\002\014\004\000\002" +
    "\015\003\000\002\015\003\000\002\016\006\000\002\021" +
    "\003\000\002\021\003\000\002\021\003\000\002\021\003" +
    "\000\002\017\005\000\002\017\005\000\002\017\003\000" +
    "\002\020\005\000\002\020\003\000\002\022\003\000\002" +
    "\022\003\000\002\023\010\000\002\024\004\000\002\024" +
    "\003\000\002\025\006\000\002\026\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\136\000\012\002\uffed\004\007\005\005\012\uffed\001" +
    "\002\000\006\002\ufffd\012\ufffd\001\002\000\004\023\111" +
    "\001\002\000\006\002\ufffe\012\ufffe\001\002\000\004\004" +
    "\103\001\002\000\006\002\000\012\033\001\002\000\004" +
    "\002\032\001\002\000\004\005\015\001\002\000\004\005" +
    "\026\001\002\000\006\002\ufff8\012\ufff8\001\002\000\004" +
    "\005\017\001\002\000\006\002\ufffc\012\ufffc\001\002\000" +
    "\004\005\020\001\002\000\010\002\ufff6\005\021\012\ufff6" +
    "\001\002\000\004\005\022\001\002\000\004\005\023\001" +
    "\002\000\004\005\024\001\002\000\010\002\ufff5\005\ufff5" +
    "\012\ufff5\001\002\000\004\005\026\001\002\000\004\005" +
    "\027\001\002\000\004\005\030\001\002\000\004\005\021" +
    "\001\002\000\006\002\ufff7\012\ufff7\001\002\000\004\002" +
    "\001\001\002\000\006\007\034\025\035\001\002\000\010" +
    "\017\044\025\045\026\046\001\002\000\004\015\043\001" +
    "\002\000\010\002\uffe8\007\uffe8\025\uffe8\001\002\000\010" +
    "\002\uffe7\007\uffe7\025\uffe7\001\002\000\010\002\uffea\007" +
    "\uffea\025\uffea\001\002\000\010\002\uffff\007\034\025\035" +
    "\001\002\000\010\002\uffe9\007\uffe9\025\uffe9\001\002\000" +
    "\010\017\044\025\045\026\046\001\002\000\010\017\044" +
    "\025\045\026\046\001\002\000\022\010\uffdb\013\uffdb\014" +
    "\uffdb\016\uffdb\020\uffdb\021\uffdb\023\uffdb\024\uffdb\001\002" +
    "\000\022\010\uffdc\013\uffdc\014\uffdc\016\uffdc\020\uffdc\021" +
    "\uffdc\023\uffdc\024\uffdc\001\002\000\014\013\053\014\054" +
    "\016\055\023\061\024\052\001\002\000\022\010\uffdf\013" +
    "\uffdf\014\uffdf\016\uffdf\020\uffdf\021\uffdf\023\uffdf\024\uffdf" +
    "\001\002\000\022\010\uffdd\013\053\014\054\016\055\020" +
    "\uffdd\021\uffdd\023\uffdd\024\052\001\002\000\010\017\uffe2" +
    "\025\uffe2\026\uffe2\001\002\000\010\017\uffe3\025\uffe3\026" +
    "\uffe3\001\002\000\010\017\uffe4\025\uffe4\026\uffe4\001\002" +
    "\000\010\017\uffe5\025\uffe5\026\uffe5\001\002\000\006\025" +
    "\045\026\046\001\002\000\022\010\uffde\013\uffde\014\uffde" +
    "\016\uffde\020\uffde\021\uffde\023\uffde\024\uffde\001\002\000" +
    "\010\017\044\025\045\026\046\001\002\000\010\002\uffe6" +
    "\007\uffe6\025\uffe6\001\002\000\022\010\uffe1\013\053\014" +
    "\054\016\055\020\uffe1\021\uffe1\023\uffe1\024\052\001\002" +
    "\000\014\013\053\014\054\016\055\020\064\024\052\001" +
    "\002\000\022\010\uffe0\013\uffe0\014\uffe0\016\uffe0\020\uffe0" +
    "\021\uffe0\023\uffe0\024\uffe0\001\002\000\014\010\066\013" +
    "\053\014\054\016\055\024\052\001\002\000\010\017\044" +
    "\025\045\026\046\001\002\000\014\013\053\014\054\016" +
    "\055\021\075\024\052\001\002\000\004\011\073\001\002" +
    "\000\012\011\uffd8\017\044\025\045\026\046\001\002\000" +
    "\004\011\uffd9\001\002\000\004\023\074\001\002\000\010" +
    "\002\uffda\007\uffda\025\uffda\001\002\000\004\006\076\001" +
    "\002\000\010\017\044\025\045\026\046\001\002\000\004" +
    "\022\100\001\002\000\012\011\uffd7\017\uffd7\025\uffd7\026" +
    "\uffd7\001\002\000\014\013\053\014\054\016\055\023\102" +
    "\024\052\001\002\000\004\022\uffd6\001\002\000\004\004" +
    "\104\001\002\000\004\004\105\001\002\000\004\004\107" +
    "\001\002\000\004\005\ufffb\001\002\000\006\004\105\005" +
    "\ufffa\001\002\000\004\005\ufff9\001\002\000\006\004\113" +
    "\005\112\001\002\000\004\023\131\001\002\000\004\023" +
    "\130\001\002\000\006\004\116\005\115\001\002\000\004" +
    "\023\120\001\002\000\004\023\117\001\002\000\012\002" +
    "\uffeb\004\uffeb\005\uffeb\012\uffeb\001\002\000\006\004\113" +
    "\005\121\001\002\000\004\023\126\001\002\000\006\004" +
    "\116\005\123\001\002\000\004\023\124\001\002\000\010" +
    "\002\ufff1\004\113\012\ufff1\001\002\000\010\002\ufff4\004" +
    "\116\012\ufff4\001\002\000\010\002\ufff0\004\113\012\ufff0" +
    "\001\002\000\010\002\ufff2\004\116\012\ufff2\001\002\000" +
    "\012\002\uffec\004\uffec\005\uffec\012\uffec\001\002\000\006" +
    "\004\113\005\132\001\002\000\004\023\137\001\002\000" +
    "\006\004\116\005\134\001\002\000\004\023\135\001\002" +
    "\000\010\002\uffef\004\113\012\uffef\001\002\000\010\002" +
    "\ufff3\004\116\012\ufff3\001\002\000\004\004\113\001\002" +
    "\000\010\002\uffee\004\116\012\uffee\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\136\000\014\002\010\003\007\004\005\005\003\006" +
    "\011\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\007\015\010\013\011\012\001\001\000\004" +
    "\011\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\030\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\014\040\015\037\016\035\023\036\001\001" +
    "\000\010\017\064\020\047\022\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\015\041\016\035\023\036\001\001\000\002\001" +
    "\001\000\010\017\046\020\047\022\050\001\001\000\010" +
    "\017\062\020\047\022\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\057\001\001\000\002\001\001" +
    "\000\004\021\055\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\022\056" +
    "\001\001\000\002\001\001\000\010\017\061\020\047\022" +
    "\050\001\001\000\002\001\001\000\004\021\057\001\001" +
    "\000\004\021\057\001\001\000\002\001\001\000\004\021" +
    "\057\001\001\000\014\017\066\020\047\022\050\024\067" +
    "\025\070\001\001\000\004\021\057\001\001\000\002\001" +
    "\001\000\014\017\066\020\047\022\050\024\071\025\070" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\026\076\001\001\000\010\017\100\020\047" +
    "\022\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\021\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\105\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\107\001\001\000\002\001\001\000\004" +
    "\013\113\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\121\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\013\124\001\001" +
    "\000\002\001\001\000\004\013\126\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\013\132\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\135\001\001\000\002\001\001\000\004\013\137\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    table = new HashMap <String, HashMap <String, Double>>();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= HEADER 
            { parser.Tree.reduce(1,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // prog ::= HEADER SEP COMMANDS 
            { parser.Tree.reduce(3,"prog",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // HEADER ::= HEADER1 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // HEADER ::= HEADER2 
            { parser.Tree.reduce(1,"HEADER",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // HEADER1 ::= SEC1 SEC2 
            { parser.Tree.reduce(2,"HEADER1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER1",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // SEC1 ::= TOK1 TOK1 TOK1 TOK1_REPEAT 
            { parser.Tree.reduce(4,"SEC1",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SEC1",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // TOK1_REPEAT ::= TOK1 TOK1 
            { parser.Tree.reduce(2,"TOK1_REPEAT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1_REPEAT",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // TOK1_REPEAT ::= TOK1 TOK1 TOK1_REPEAT 
            { parser.Tree.reduce(3,"TOK1_REPEAT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1_REPEAT",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SEC2 ::= SEC2_3 
            { parser.Tree.reduce(1,"SEC2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SEC2",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SEC2 ::= SEC2_7 SEC2_7 SEC2_7 
            { parser.Tree.reduce(3,"SEC2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SEC2",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SEC2_3 ::= TOK2 TOK2 TOK2 
            { parser.Tree.reduce(3,"SEC2_3",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SEC2_3",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SEC2_7 ::= TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 TOK2 
            { parser.Tree.reduce(7,"SEC2_7",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("SEC2_7",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // HEADER2 ::= TOK2 SC TOK1_OCCURS TOK2 SC TOK1_OCCURS TOK2 SC TOK1_OCCURS 
            { parser.Tree.reduce(9,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // HEADER2 ::= TOK2 SC TOK2 SC TOK1_OCCURS TOK2 SC TOK1_OCCURS 
            { parser.Tree.reduce(8,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // HEADER2 ::= TOK2 SC TOK1_OCCURS TOK2 SC TOK2 SC TOK1_OCCURS 
            { parser.Tree.reduce(8,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // HEADER2 ::= TOK2 SC TOK1_OCCURS TOK2 SC TOK1_OCCURS TOK2 SC 
            { parser.Tree.reduce(8,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // HEADER2 ::= TOK2 SC TOK1_OCCURS TOK2 SC TOK2 SC 
            { parser.Tree.reduce(7,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // HEADER2 ::= TOK2 SC TOK2 SC TOK1_OCCURS TOK2 SC 
            { parser.Tree.reduce(7,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // HEADER2 ::= TOK2 SC TOK2 SC TOK2 SC TOK1_OCCURS 
            { parser.Tree.reduce(7,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // HEADER2 ::= 
            { parser.Tree.reduce(0,"HEADER2",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("HEADER2",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // TOK1_OCCURS ::= TOK1 SC 
            { parser.Tree.reduce(2,"TOK1_OCCURS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1_OCCURS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // TOK1_OCCURS ::= TOK1_OCCURS TOK1 SC 
            { parser.Tree.reduce(3,"TOK1_OCCURS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("TOK1_OCCURS",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // COMMANDS ::= COMMAND 
            { parser.Tree.reduce(1,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // COMMANDS ::= COMMANDS COMMAND 
            { parser.Tree.reduce(2,"COMMANDS",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMANDS",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // COMMAND ::= ASSIGNMENT 
            { parser.Tree.reduce(1,"COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMAND",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // COMMAND ::= COMPARE 
            { parser.Tree.reduce(1,"COMMAND",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMMAND",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ASSIGNMENT ::= VAR EQ EXPR SC 
            { parser.Tree.reduce(4,"ASSIGNMENT",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASSIGNMENT",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPER ::= PLUS 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPER ::= DASH 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OPER ::= STAR 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // OPER ::= SL 
            { parser.Tree.reduce(1,"OPER",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPER",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // EXPR ::= EXPR OPER EXPR 
            { parser.Tree.reduce(3,"EXPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPR",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // EXPR ::= OP EXPR CP 
            { parser.Tree.reduce(3,"EXPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPR",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // EXPR ::= EXP 
            { parser.Tree.reduce(1,"EXPR",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXPR",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // EXP ::= BLOCK OPER BLOCK 
            { parser.Tree.reduce(3,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // EXP ::= BLOCK 
            { parser.Tree.reduce(1,"EXP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("EXP",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // BLOCK ::= INUM 
            { parser.Tree.reduce(1,"BLOCK",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLOCK",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // BLOCK ::= VAR 
            { parser.Tree.reduce(1,"BLOCK",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("BLOCK",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // COMPARE ::= COMPARE_WD EXPR WITH_WD COMP_LIST END_WD SC 
            { parser.Tree.reduce(6,"COMPARE",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMPARE",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // COMP_LIST ::= COMP COMP_LIST 
            { parser.Tree.reduce(2,"COMP_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP_LIST",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // COMP_LIST ::= COMP 
            { parser.Tree.reduce(1,"COMP_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP_LIST",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // COMP ::= EXPR OC PRINT_LIST CC 
            { parser.Tree.reduce(4,"COMP",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COMP",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // PRINT_LIST ::= PRINT_WD EXPR SC 
            { parser.Tree.reduce(3,"PRINT_LIST",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINT_LIST",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
