import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Integer>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Integer>>table;

    public void report_error(String message, Object info) {
        System.err.print("ERROR: Syntax error");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.print(" (line "+line+", column "+column+"): ");
            } else System.err.print(": ");
        else System.err.print(": ");
    }
    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }

   public HashMap<String, Integer> myList = new HashMap<>();
   public Double total = 0.0;


:};


/////////////////////////////
//// Symbols Delaration
////////////////////////////

terminal SEP, TOK1, TOK2, TOK3, SC, OC, CC, CM, EQ, MS_WD, PRINT_MIN_MAX_WD, OP, CP, NEXT, PART_WD, M_WD,CO, OR ;
terminal String QSTRING;
terminal Integer INUM;

non terminal prog, HEADER, CARS, RACE ;
non terminal  TOKEN1, TOKEN2, TOKEN3, TOKEN1S ;
non terminal CARLIST, CAR ;
non terminal HashMap<String, Integer> SPEEDLIST;

non terminal RACELIST, RACE_ITEM, PRINT_MIN_MAX, PARTLIST;
non terminal Integer[] SECTION_NAMES;
non terminal Double STATS_LIST;
non terminal Object [] PERFORMANCES,PERFORMANCES_LIST;
/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= HEADER SEP CARS SEP RACE
;


TOKEN1 ::= TOK1 SC
;
TOKEN2 ::= TOK2 SC
;
TOKEN3 ::= TOK3 SC
;

HEADER ::= TOKEN1S TOKEN2 TOKEN1S TOKEN3 TOKEN1S | TOKEN1S TOKEN3 TOKEN1S TOKEN2 TOKEN1S
;

TOKEN1S ::= TOKEN1S TOKEN1 |
;

//CARS

CARS ::= CARLIST
;

CARLIST ::= CARLIST CAR CAR | CAR CAR
;

CAR ::= QSTRING:var OC SPEEDLIST:list CC {:parser.table.put(var, list);:}
;

SPEEDLIST ::= SPEEDLIST:tab CM QSTRING:name EQ INUM:number MS_WD 
{:
tab.put(name, number);
RESULT = tab ;
:} 
| QSTRING:name EQ INUM:number MS_WD 
{:
HashMap<String, Integer> tab = new HashMap<String, Integer>();
tab.put(name, number);
RESULT = tab ;
:}
;



//RACE


RACE ::= RACELIST
;

RACELIST ::= RACELIST RACE_ITEM |
;

RACE_ITEM ::= PRINT_MIN_MAX PERFORMANCES_LIST
;

PRINT_MIN_MAX ::= PRINT_MIN_MAX_WD OP QSTRING:var {:
HashMap<String, Integer> list = parser.table.get(var);
RESULT = list ;
:} CP OP SECTION_NAMES:x CP SC {:
System.out.println("MIN: "+ x[0] + " MAX: " + x[1]);
:}

;
SECTION_NAMES ::= SECTION_NAMES:first CM QSTRING:x {:
HashMap<String, Integer> list = (HashMap<String, Integer>)parser.stack(-5);
Integer second = list.get(x);
Integer max = first[1];
Integer min = first[0];
if(first[1] < second){max = second;};
if(first[0] > second){min = second;};
Integer[] min_max = new Integer[2];
min_max[0] = min;
min_max[1] = max;
RESULT = min_max;
:}
| QSTRING:x  {:
HashMap<String, Integer> list = (HashMap<String, Integer>)parser.stack(-3);
Integer num = list.get(x);
Integer[] min_max = new Integer[2];
min_max[0] = num;
min_max[1] = num;
RESULT = min_max;
:}
;

PERFORMANCES_LIST ::= PERFORMANCES_LIST:x PERFORMANCES:y {:
Double best = (Double)x[1];
String name = (String)x[0];
if((Double)y[1] < (Double)x[1]){
    best = (Double)y[1];
    name = (String)y[0];
};
System.out.println("WINNER: "+name+" "+ best + " s");

:} | PERFORMANCES:x {:
RESULT = x;
:}
;

PERFORMANCES ::= QSTRING:x{:System.out.println(x);:} NEXT PARTLIST SC {:
System.out.println("TOTAL: "+ parser.total + " s");
Object [] arr = new Object[2];
arr[0] = x;
arr[1] = parser.total;
RESULT = arr ;
parser.total = 0.0 ; 
:}
;

PARTLIST ::= PARTLIST OR PART_WD:word {:
HashMap<String, Integer> list = parser.table.get(parser.stack(-5));
parser.myList = list;
RESULT = list;
:} INUM:num CO STATS_LIST:x {:
parser.total = parser.total + x;
System.out.println(word+""+num+": "+ x+" s");
:}  
| PART_WD:word {:HashMap<String, Integer> list = parser.table.get(parser.stack(-3));
parser.myList = list;
RESULT = list;
:} INUM:num CO STATS_LIST:x {:
parser.total = parser.total + x;
System.out.println(word+""+num+": "+ x+" s");
:}
;

STATS_LIST ::= STATS_LIST:res CM QSTRING:x INUM:y M_WD 
{:

Double second = y / (double)parser.myList.get(x);
RESULT = res + second;
:}
| QSTRING:x INUM:y M_WD {:
RESULT = y / (double)parser.myList.get(x);
:}
;


